### ISSUE TITLE
How to plot posterior density figure?

### ISSUE THREAD

**Issue by xiaofenghan** [jmaih/RISE_toolbox#10]
Hi Junior:
     
    My model is as same as FWZ(2011), and I check the FWZ example of RISE, I still have some  problem. To be more specific, after estimated the model, I want to plot the posterior density of these parameters by the function "plot_posterior" and I can't get anything. So I check the folder...\simutlations, it is empty. I don't why, can you help me?
    By the way, when i estimated the model, using command like "estimate(mymodel,'optimizer','fmincon');"  was I missed soming or some parameters in this command?
    thank you!!

**Comment by jmaih** [comment]
Hi Xiaofeng,

When you run estimate, you merely maximize the posterior mode. Simulating the posterior distribution is the next step. For instance, if I estimate my model as mest=estimate(m,...), then I can follow these steps

**create an objective function for posterior simulation**
[objective,lb,ub,x0,SIG]=pull_objective(mest);

**Set up the options for the Metropolis Hasting algorithm**
ndraws_mcmc         = 1500;  % number of parameter draws through MCMC.
ndraws_burnin       = floor(0.1*ndraws_mcmc); % number of parameter draws to be burned
mcmc_options=struct('burnin',ndraws_burnin,'N',ndraws_mcmc,'thin',1);

**Run the Metropolis hastings algorithm to sample from the posterior distribution**
Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG);

**Plot the posterior distribution of the parameters**
plot_posteriors(mest,Results.pop)

**Comment by xiaofenghan** [comment]
Hi Junior:
     Thank you！ Thanks for your specific steps , very useful !!!
Best wishes!

At 2016-05-28 17:05:03, "Junior Maih" <notifications@github.com> wrote:


Hi Xiaofeng,

When you run estimate, you merely maximize the posterior mode. Simulating the posterior distribution is the next step. For instance, if I estimate my model as mest=estimate(m,...), then I can follow these steps

create an objective function for posterior simulation
[objective,lb,ub,x0,SIG]=pull_objective(mest);

Set up the options for the Metropolis Hasting algorithm
ndraws_mcmc = 1500; % number of parameter draws through MCMC.
ndraws_burnin = floor(0.1*ndraws_mcmc); % number of parameter draws to be burned
mcmc_options=struct('burnin',ndraws_burnin,'N',ndraws_mcmc,'thin',1);

Run the Metropolis hastings algorithm to sample from the posterior distribution
Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG);

Plot the posterior distribution of the parameters
plot_posteriors(mest,Results.pop)
