### ISSUE TITLE
LWZ 2013 

### ISSUE THREAD

**Issue by gospurs666** [jmaih/RISE_toolbox#100]
Dear Junior,

Hope this email finds you well. I encounter the following error when I try to run the posterior sampling section of master_switch.m in LWZ2013:

Error using mcmc.process_draws/re_order_names (line 244)
Index exceeds matrix dimensions.

Error in mcmc.process_draws (line 72)
        [N,chains,stud]=re_order_names();

Error in mh_sampler>do_one_chain/reload_options (line 559)
                [~,~,~,summary]=mcmc.process_draws(options.save.location,chain);

Error in mh_sampler>do_one_chain (line 202)
[log_c,isave_batch,idraw,accept_ratio,bestSoFar]=reload_options(chain);

Error in mh_sampler (line 106)
parfor(ichain=1:nchain,nworkers)

Could you tell me how to fix this problem? Thank you!

By the way, do you have any plan to offer courses in RISE recently? Please tell me if there is one and I would like to go there to learn from you. Thank you!

Best,
Mike

**Comment by jmaih** [comment]
Hi Mike,

Will you, please, update RISE and try again?

With respect to courses, I seldom organize courses myself. Oftentimes what
happens is that I get invited by various institutions around the world to
teach. I think the next course I will organize myself will take place in
2020 but I have not started planning it yet.

If you send me an email, I can add your email to a mailing list and in that
way you will know when there is a course coming up.

Cheers,

Junior

**Comment by gospurs666** [comment]
Thanks Junior!
