### ISSUE TITLE
Different starting points for optimizer

### ISSUE THREAD

**Issue by anettbor** [jmaih/RISE_toolbox#101]
Hi Junior,
I was reading the paper by Liu, Waggoner and Zha (2011), where they start the optimization process from a number of different starting points. Is this possible to do in an easy way in RISE, and is it dependent on the optimizer I use? 

Thanks,

Anette

**Comment by jmaih** [comment]
Hi Anette,
I would rather take the problem from the end. What do you hope to achieve with such a procedure ? Such a procedure is not implemented directly in RISE but is relatively easy to code up. But it is computationally intensive: the authors of the paper use parallelization and a cluster of 50 computers. I doubt you need it. But should you want it I am more than happy to write such a procedure for RISE. 

Cheers,

Junior

**Comment by anettbor** [comment]
I'm not too familiar with what is usually done, but I had the impression that this is done to make sure that the global maximum is found? How do I know whether it is necessary or not?

Thanks,

Anette

**Comment by jmaih** [comment]
No matter what you do, you can never be certain that the point found is the global peak. 

Such a procedure is merely about increasing the confidence that the search is thorough.

Cheers,

J.

**Comment by anettbor** [comment]
Ok, I think I'll just leave it for now. But thanks anyway!

A.

**Comment by C1587S** [comment]
Hi Junior,

I am interested in doing an exercise using a thorough search for getting close to the global peak, and for the type of function that I'm using, it seems that the starting point is crucial for the optimization process. I would be extremely thankful if you could implement the procedure utilized by LWZ (2011) in RISE as you mentioned before, is it possible?

Thanks in advance,

Best,

S.
