### ISSUE TITLE
Some instruction questions about RISE.

### ISSUE THREAD

**Issue by Secretlovelmy** [jmaih/RISE_toolbox#102]
Dear Junior maih,

Hello, I am currently writing a paper on economics. I saw your rise_toolbox-master toolbox on GitHub. But I am a beginner, so I can't understand how the examples you gave are specifically used and the instructions for using the toolbox. The body of the article has reserved your email address, so I sent you this email with a feeling of embarrassment. I don't know if I have any chance to learn more about the application and identification of the verification code. If I am bothered to you, I hope to forgive me!

Looking forward to your reply!

**Comment by jmaih** [comment]
Dear Secretlovelmy,

There is nothing to be embarrassed about. However, if you want to use the
toolbox to your advantage, it is important that you know DSGE modeling and
have some notion of programming in Matlab.

If you have not done any DSGE modeling before, this is probably not the
right toolbox for you at this time. I would recommend starting with Dynare

Good luck,

Junior.

**Comment by Secretlovelmy** [comment]
Hi, Junior,
I am a postgraduate student of renmin university of China, and I need to use ms-dsge model in my thesis. I am very grateful that I was able to download such an excellent and widely used toolbox. But I had a problem using the Farmer WaggonerZha2010 example. First, it indicates that the file suffixed with.rs or.rz or.dsge cannot be found, but it does exist in the package. There are two more errors later, as shown in the picture below. By the way, what is the file with the suffix.rs? I changed it to the .m file. Then I checked it and found that it was the model used in the example. So how do I build my own model? Can I change the model directly and then change the suffix?  Thank you very much for answering my questions!

Looking forward to your reply!

**Comment by jmaih** [comment]
Hi,

You should not change the extension of the files. Model files have extensions .rs, .rz or .dsge. You choose whichever you prefer. Those files are very conveniently written in a simple text editor or even within matlab. 

Alongside the model files, you will usually find some .m files. Those are the one from which the programs are run.

As I said earlier, it would be useful to know a little bit of matlab programming if you want to use RISE. 

I am afraid I can’t be of more help.

Best of luck,

Junior
