### ISSUE TITLE
How to plot posterior results

### ISSUE THREAD

**Issue by Secretlovelmy** [jmaih/RISE_toolbox#104]
Hi, maih
I have some question about 'How to plot posterior results'. 
Matlab said that Referenced a field that does not exist 'pop'。

error mcmc.reload_draws/load_from_self (line 90)
                d=[dii.pop.x];

error mcmc.reload_draws (line 37)
    [d,fd,c,SIG,accept_ratio,dlast,best]=load_from_self();

error generic/plot_posteriors (line 171)
[d,~,~,~,~,~,~,best]=mcmc.reload_draws(simfold,subset);

Here is the code.

`%% Simulation of the posterior distribution
% obj below is a rise object with the simulation statistics included in
% obj{imod}.estimation.posterior_simulation for imod=1:nmodels
clc
Results=cell(1,nmodels);
objective=cell(1,nmodels);
lb=cell(1,nmodels);
ub=cell(1,nmodels);
ndraws_mcmc         = 1500;  % number of parameter draws through MCMC.
ndraws_burnin       = floor(0.1*ndraws_mcmc); % number of parameter draws to be burned
mcmc_options=struct('burnin',ndraws_burnin,'N',ndraws_mcmc,'thin',1);

for imod=1:nmodels
    % replace "for" by "parfor" if you want to use parallel computation
    disp('*--------------------------------------------------------------*')
    disp(['*----------- MCMC for ',model_names{imod},' model-------------*'])
    disp('*--------------------------------------------------------------*')
    % Here the simulations are stored in variable, which here we call
    % postSims.
    %-----------------------------------------------------------------
    [objective{imod},lb{imod},ub{imod},x0,SIG]=pull_objective(estim_models{imod});
    
    Results{imod}=mh_sampler(objective{imod},lb{imod},ub{imod},mcmc_options,x0,SIG);
    %%plot
    plot_posteriors(estim_models{imod},Results{imod}.pop)

end`
I hope you can help me see if there is any problem with the code. And .pop is there, but I can't quote it.

Looking forward to your reply!

**Comment by jmaih** [comment]
Try running

plot_posteriors(estim_models{imod},Results{imod})

instead of

plot_posteriors(estim_models{imod},Results{imod}.pop)


What example are you running?

**Comment by Secretlovelmy** [comment]
The plot command was added into the tutorial of TaoZha by myself. Thank you for your reply. I did as you said and it worked.

**Comment by jmaih** [comment]
Thanks for letting me know.

Cheers,

Junior
