### ISSUE TITLE
Plot posterior results: Reference to non-existent field 'pop'

### ISSUE THREAD

**Issue by dingliumath** [jmaih/RISE_toolbox#105]
Hi Junior,
With your guidance, I am getting the hang of the RISE toolbox. Thanks. 
I experimented with the simple example named "model01.rs" and added mcmc part to the corresponding drive file, as attached below (driver01_modified). Following the instructions given in the related closed issues, everything works fine, except incurring plot_posteriors. I got the following errors: 

Reference to non-existent field 'pop'.

Error in mcmc.reload_draws/load_from_self (line 90)
                d=[dii.pop.x];

Error in mcmc.reload_draws (line 37)
    [d,fd,c,SIG,accept_ratio,dlast,best]=load_from_self();

Error in generic/plot_posteriors (line 171)
[d,~,~,~,~,~,~,best]=mcmc.reload_draws(simfold,subset);

Could you please help me with this? Thank you.  

[driver01_modified.zip](https://github.com/jmaih/RISE_toolbox/files/2986148/driver01_modified.zip)

**Comment by jmaih** [comment]
Try this

plot_posteriors(mest,Results)

instead,

Cheers,

J.

**Comment by dingliumath** [comment]
Hi Junior, 
Thanks for your reply. I tried your suggestion. Unfortunately, it failed. Matlab says the following:

>> plot_posteriors(mest,Results)
Error using internal.stats.parseArgs (line 42)
Invalid parameter name: NumPoints.

Error in ksdensity>parse_args (line 189)
    u = internal.stats.parseArgs({'width'},{u},extra{:});

Error in ksdensity (line 114)
[axarg,yData,n,ymin,ymax,xispecified,xi,u,m,kernelname,...

Error in distributions.kernel_density (line 65)
[ff_,xx_] = ksdensity(data,[],'NumPoints',n,...

Error in generic/plot_posteriors/do_one_post (line 286)
        [ss.f_kdens,ss.x_kdens]=distributions.kernel_density(all_vals,[],[],'normal',N);

Error in generic/plot_posteriors (line 243)
    pdata_.(vnames{ipar})=do_one_post(ipar);

One thing I forgot to mention that when running "Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG);" there is a warning given below

Warning: File: initial_draws.m Line: 113 Column: 41
The temporary variable fx will be cleared at the beginning of each iteration of the parfor
loop.
Any value assigned to it before the loop will be lost.  If fx is used before it is assigned in
the parfor loop, a runtime error will occur.
See Parallel for Loops in MATLAB, "Temporary Variables". 
> In mh_sampler>do_one_chain at 248
  In mh_sampler>(parfor body) at 108
  In parallel_function at 474
  In mh_sampler at 106
  In driver01 at 63 

What do you think? 

Best, 
Ding
