### ISSUE TITLE
simplified StochasticReplanning: Index exceeds matrix dimensions

### ISSUE THREAD

**Issue by dingliumath** [jmaih/RISE_toolbox#106]
Hi Junior,

 I am really sorry to bother you again. I am getting the following error message when I am trying to estimate a simplified model under commitment (a special case of the example in StochasticReplanning). I checked several times and could not find any obvious errors in the files which are attached.
Many thanks in advance for your time and help.
Ding 

Index exceeds matrix dimensions.

Error in dsge_tools.evaluate_all_derivatives/calculate_weights (line 352)
            ww(deriv_locs(:,2))=lcd(deriv_locs(:,3));

Error in dsge_tools.evaluate_all_derivatives (line 326)
                planner.weights{s0}=calculate_weights(deriv2,s0);

Error in dsge/solve (line 353)
    [structural_matrices,retcode]=dsge_tools.evaluate_all_derivatives(obj,structural_matrices);

Error in likelihood_markov_switching_dsge (line 27)
[obj,retcode]=solve(obj);

Error in generic/log_posterior_kernel (line 125)
    [log_lik,Incr,retcode,obj,filtration]=likelihood_func(param,obj);

Error in generic/estimation_wrapper/fh_wrapper (line 197)
                [fval(mo),loglik,~,~,retcode,obj(mo)]=log_posterior_kernel(obj(mo),x);

Error in generic/estimation_wrapper (line 130)
        [f1,retcode_0,max_pen]=fh_wrapper(x0);

Error in generic/find_posterior_mode (line 40)
[x0(:,1),f0(1),~,retcode0,viol,obj,funevals]=estimation_wrapper(obj,[],x0(:,1),lb,ub,funevals);

Error in generic/estimate (line 181)
[x1,f1,H,x0,f0,viol,funevals,issue,obj]=find_posterior_mode(obj,x0,lb_short,ub_short);
%#ok<ASGLU>

Error in dsge/estimate (line 217)
    [obj,filtration]=estimate@generic(obj,varargin{:});

Error in howto (line 50)
mest=estimate(m,'data_demean',false,'data',data,'estim_start_date','1992Q2','estim_end_date','2018Q2'); 

[junior.zip](https://github.com/jmaih/RISE_toolbox/files/2995362/junior.zip)

**Comment by jmaih** [comment]
Hi Ding,

I am investigating the issue. In the meantime replace delta in your model
with DELTA.

Cheers,

Junior

**Comment by dingliumath** [comment]
Hi Junior, 
It's quite interesting that no errors returned after changing delta to DELTA. Thanks a lot. I will let you know how the experiment turns out. 
Cheers,
Ding

**Comment by jmaih** [comment]
Problem solved.

Cheers,

Juior
