### ISSUE TITLE
RISE solvers mn and mfi

### ISSUE THREAD

**Issue by jmaih** [jmaih/RISE_toolbox#108]
Dear Professor Maih:
Thank you for your very helpful suggestion. I have encountered another question about RISE.

The attachment file is my code. When I run my code, I found that the result is very different with different "slover"( "mn" or "mfi" ), and these two solver can solve the regime-switching model without reporting an error. The result with "mn" is similar with the result of Dynare, but the result with "mfi" is totally different.I can't find where the problem is.

The other question is, with "slover" of "mn", RISE often can not solve the regime-switching model when I change the transition probability to another value.

look forward to your kind reply.

Thank you very much!

Best wishes,

Xiong Chen

**Comment by jmaih** [comment]
Dear Chen,

Solvers mn and mfi find one solution out of possibly many. The fact that they find different solutions is perfectly normal and is to be expected in general. Those solvers are iterative procedures and the answer they return crucially depends on the starting point, the properties of the problem to solve and the strategy they use to compute a solution. The newton algorithm mn is locally stable around an equilibrium while the main strength of mfi is to handle large systems.

Starting from different points may deliver different solutions. This is what the method solve_alternatives in the dsge/rise class does as it attempts to find multiple solutions.

None of those solvers is suited for solving constant-parameter models WHEN the user is interested in finding a unique stable solution which has, unfortunately, become the convention in the narrow field of constant-parameter DSGE models solved with perturbation methods.

Clearly, there is a difference between saying that for a particular parameter vector, the model admits a unique stable solution and saying that for a problem to be relevant or interesting it should have a unique stable solution.

Cheers,

Junior

**Comment by xiongcheneco** [comment]
Dear Junior,
I want to know if I can control the the starting point and get a different solution when I use "mfi" solver ? The second question is,  newton algorithm mn often fail to find a solution, is there anything I can do to make sure that the solver mn always can solve the model for a larger parameter range ?
Best,
Chen

**Comment by jmaih** [comment]
Hi Chen,

Look up option solve_initialization in help dsge.solve

Solvers mn and mfi are initialized by default using the solution of the
system when there are no forward-looking terms. This option is called
"backward". There are two other options "zeros", which initializes the
solution with zeros and "random" which initializes the solution with random
numbers.

Best,

Junior

**Comment by xiongcheneco** [comment]
Thanks  for your guidance !
Best,
Chen
