### ISSUE TITLE
Bayesian estimation

### ISSUE THREAD

**Issue by xiongcheneco** [jmaih/RISE_toolbox#109]
Dear Junior,
I am seeking your help again.  After Bayesian estimation, I found that the Expected_filtered_variables dose not match the data for some exogenous variables ( specified by AR(1) in model ).  Is there any way to match these  exogenous observable variables when doing Bayesian estimation ? 
Many thanks.
Best,
Chen

**Comment by jmaih** [comment]
Filtered variables are forecasts

Maybe what you are looking for is smoothed variables?

Cheers,

J.

**Comment by xiongcheneco** [comment]
Smoothed variables not match data too.  Is it possible that my estimation settings has a problem?

**Comment by jmaih** [comment]
Do you have measurement errors ?

**Comment by xiongcheneco** [comment]
Yes,  I  have,

**Comment by jmaih** [comment]
Then that is the reason

**Comment by xiongcheneco** [comment]
It works. Many thanks !
Best,
Chen

**Comment by jmaih** [comment]
Thanks for letting me know 

Cheers 

J. 

Sendt fra min iPhone
