### ISSUE TITLE
How to read filtering.smoothed_regime_probabilities id there are two Markov chaines

### ISSUE THREAD

**Issue by AnastasiaZh** [jmaih/RISE_toolbox#11]
Dear Junior,

I have two Markov chains, one that controls policy coefficients and the other controls parameters characterizing exogenous processes. Say (a,1) (a,2) and (b,1) (b,2). In this case, what is the combination of those chains in filtering.smoothed_regime_probabilities.regime_i ? After some experiments, I guess it should be this way:

regime_1 : (a1),(b,1)
regime_2 : (a2),(b,1)
regime_3 : (a1),(b,2)
regime_4 : (a2),(b,2)

Is that correct?

Thanks in advance,

**Comment by AnastasiaZh** [comment]
P.S. 'a' stand for the regimes being first declared in model file.

**Comment by jmaih** [comment]
Hi Anastazia,

This is simple. You don't have to compute it yourself, RISE has already done the math for you. Suppose your model object is called "m". Then you can just go to 

```
m.markov_chains.regimes

```
and read what the regimes are.

Cheers,

J.

**Comment by AnastasiaZh** [comment]
Works. Thanks a lot!
