### ISSUE TITLE
loose commitment with switching volatility

### ISSUE THREAD

**Issue by dingliumath** [jmaih/RISE_toolbox#110]
Hi Junior,
Hope everything goes well. 
I am trying to introduce switching volatility into the example in RISE_toolbox\examples\StochasticReplanning\Estimation_examples\usmodel_sr_switch.rs. The model was rised without any errors. However, when running the estimate command, I got the following errors:

Error using regexprep
Evaluation of 'convert_the_guy($1,$2,$3,$4,$5,$6)' failed:

Index exceeds matrix dimensions.

Error in generic_tools.nonlinear_restrictions_engine (line 32)
        RestrictionsBlock{irow}=regexprep(eqtn,expr,replace);

Error in generic/setup_nonlinear_restrictions (line 47)
    param_names,regimes,chain_names,governing_chain,...

Error in generic/setup_restrictions (line 27)
    obj=setup_nonlinear_restrictions(obj);

Error in generic/transform_parameters (line 70)
obj=setup_restrictions(obj);

Error in generic/estimate (line 177)
[obj,x0,lb_short,ub_short]=transform_parameters(obj,x0,lb,ub);

Error in dsge/estimate (line 217)
    [obj,filtration]=estimate@generic(obj,varargin{:});

I have no idea how to debug this problem. Could you please have a look if time allows? The codes are attached. 
[junior.zip](https://github.com/jmaih/RISE_toolbox/files/3141006/junior.zip)

Thank you very much.

Cheers,
Ding

**Comment by jmaih** [comment]
Are you still interested in this topic?

Let me know,

J.

**Comment by dingliumath** [comment]
Hi Junior, 
Glad to hear from you. 
I did not solve the issue. Any help from you is appreciated. 
Best wishes,
Ding
