### ISSUE TITLE
numbers are printed when the model is solved

### ISSUE THREAD

**Issue by KonstantinosTheodoridis** [jmaih/RISE_toolbox#111]
Junior,
I trust you are well. I am sorry to bother you. 
When the model is solved the following numbers are printed
no of equations 0 no of equations
This is no big issue but when it comes to the estimation it becomes quite annoying as we cannot actually see how the estimation progresses.
Many thanks in advance for your time and help.
Kostas

**Comment by jmaih** [comment]
Kostas,

An update has been pushed.

Let me know if the problem persists.

Thanks,

J.

**Comment by KonstantinosTheodoridis** [comment]
Junior,
Many thanks for your prompt response. This is very much appreciated. Is it going to take time to be uploaded to the system (I am using the Unix terminal to download it)?
Many thanks again.
Kostas

**Comment by KonstantinosTheodoridis** [comment]
Junior,
I am really sorry to bother you about this again. For some reason, I cannot get the update.
Many thanks in advance for your time and help.
Kostas

**Comment by jmaih** [comment]
Kostas,

I don't know how to fix such a problem on my end. This is a new problem you
have never had before and nobody else has complained about it, at least not
yet. Maybe you can download it as a zip file in the meantime?

Best,

J.

**Comment by KonstantinosTheodoridis** [comment]
Hi Junior,
I am sorry to bother you again about this. As you suggested, I downloaded the zip file but the issue seems to persist.
Many thanks in advance for your time and help.
Kostas

**Comment by jmaih** [comment]
Hi Kostas,

I have been teaching in the past days with the codes posted on github and I
have not received any complaint. Could you please check again and let me
know?'

thanks,

J.
