### ISSUE TITLE
representation of a MSDSGE as a VAR

### ISSUE THREAD

**Issue by aserafini75** [jmaih/RISE_toolbox#112]
Dear Maih,

I am actually I interesting on the representation of a MSDSGE as a VAR. In doing so I basically need the A and the B matrix (x_t+1=A*x_t+1+B* \epsilon_t). As you suggested such information can be obtained in the field Tz but it is not a n*n*r matrix (n=number of variables,r= number of regimes) but n*(n-k)*r. What about the missing k elements? And what about the B matrix? Can you give me some more information?

Thank you in advance!

**Comment by jmaih** [comment]
This is an undocumented function of RISE. Try the following:

[A,B]=load_solution(m)

**Comment by aserafini75** [comment]
This is perfect! Thank you!
    Il martedì 13 agosto 2019, 15:13:57 CEST, Junior Maih <notifications@github.com> ha scritto:  
 
 This is an undocumented function of RISE. Try the following:

[A,B]=load_solution(m)

**Comment by aserafini75** [comment]
Dear Maih,
thank you for your reply. The very last question related to the previous one. What about the ms-constant term. The A matrix does not contain such information.

Thank you again!

**Comment by jmaih** [comment]
[T,R,Qfunc,steady_state]=load_solution(m)

will give you the steady state in each regime as well. The constant term is
transformed into steady state so that the model is

x_t-xss(rt)=A*(x_t-xss(rt))+1+B*E

where rt stands for the regime.

Why do you need all that anyway?

J.

**Comment by aserafini75** [comment]
Thank you Maih again. I need all that information because, basically, I am preparing a file for doing some counterfactual exercises (I didn't find the  "counterfactual(m,[],[],shock_list,'kf_filtering_level',1)" function in order to perform one automatically from RISE (in Tao_report)). I have performed an exercise but at the same time I was wondering why the errors obtained were relatively large and this is why I asked you regarding the constant term, in particular, and of the VAR formulation more in general.
    Il domenica 18 agosto 2019, 15:12:05 CEST, Junior Maih <notifications@github.com> ha scritto:  
 
 [T,R,Qfunc,steady_state]=load_solution(m)

will give you the steady state in each regime as well. The constant term is
transformed into steady state so that the model is

x_t-xss(rt)=A*(x_t-xss(rt))+1+B*E

where rt stands for the regime.

Why do you need all that anyway?

J.
