### ISSUE TITLE
Issue with TaoZha tutorial

### ISSUE THREAD

**Issue by 1801k** [jmaih/RISE_toolbox#114]
Warm regards Junior!

There seems to be two issues with the file driver6.m in the tutorial. The path being
\RISE_toolbox-master\examples\VariousModels\TaoZha\Tutorials\SVAR

In the part of the file where the marginal data density is computed, the results of the posterior draws could not be read. That is line 288 which has the command mddobj=mdd(results.pop,ff,lb,ub);
  gives the error
"Struct contents reference from a non-struct array object."

The second error is when using the fancharts function. Even if myirfs2=irf(sv,shock_names); is run instead of using the posterior results from results.pop for the irf function, which would return the same error as above, running  line 380 where the command to use the fanchart function gives the following error

"Subscript indices must either be real positive integers or logicals."

Thanks for the amazing toolbox btw. Your work is much appreciated,

**Comment by jmaih** [comment]
Dear 1801k,

Sorry for the delay, the example should work better now. Please let me know if there are any further problems.

Cheers,

Junior
