### ISSUE TITLE
Steady state options in RISE

### ISSUE THREAD

**Issue by jkrenz** [jmaih/RISE_toolbox#115]
Hi Junior, 

I asked about what RISE reports as "steady state" values in the solution and your answer was that it is "simply the deterministic steady state. RISE does not formally compute the ergodic mean at least for the purpose of presenting the solution. This is why RISE reports in separate expressions (@sig, @sig@sig,...), the elements related to the perturbation parameter." I have some follow up questions on this which are related to the different options of specifying around which point RISE should approximate the model (steady_state_unique, steady_state_imposed, "no specification").

I should first mention, that I have a model with an occasionally binding incentive constraint for banks. In my steady state file, I provide accurate values for the binding regime, but I don't tell RISE that it is the steady state for the binding regime, i.e., I only enter v."varname" = "some value" without using the bind-nobind-parameters.

When comparing some of the solutions from steady_state_unique, steady_state_imposed, "no specification", I noticed the following: 

**steady_state_unique** (--> approximation around the ergodic mean)
- RISE takes pretty much my given steady state values as deterministic steady state values for both regimes. 
- Hence, the user_resids reported in m are very small and pretty much the same as mine (i.e. those which appear when I use resid(m) command right after the rise command).
- The values provided in @sig are rather small and different between the two regimes. 

**steady_state_fixed** (--> approximation around an arbitrary point)
- in most cases RISE takes my given steady state values as deterministic steady state values for both regimes, but in some cases the deterministic steady state values differ quite a bit from mine but are still the same for both regimes. 
- Hence, the user_resids become quite large (up to 1) for some of the equations. 
-  The values provided in @sig are sometimes very big and differ quite a bit between NB and B.

**"no specification of the point around which RISE should approx. the model"** (--> default option: approximation around regime-specific steady states)
- RISE apparently recognizes that I provide the values for the binding regime, and takes them as deterministic steady state values for the binding regime. For the NB regime it calculates an entirely new deterministic steady state (the values seem plausible to me for the non-binding case).
- The user_resids are exactly the same I get with my values (i.e. those which appear when I use resid(m) command right after the rise command) so, I think RISE does not calculate them for its own steady state values (?).
-  The values provided in @sig are very small (essentially zero for binding regime and also very small for non-binding regime). 

My resulting questions are:
1. Why are the deterministic steady states different between fixed and imposed? And particularly in the case of steady_state_fixed, why does RISE settle on a deterministic steady state which creates much bigger residuals in the model equations than the values I provide?
2. What do the values in @sig tell me under the three different steady state options? 
3.  How can I find out the point around which the system is approximated? From Maih (2015), I understand that for steady_state_unique and steady_state_imposed, RISE should approximate around just one point, i.e. the approximation point can't found by deterministic steady state + @sig or just @sig, because the resulting points would be different between the two regimes, i.e., there would be two approximation points.
4. The irfs I get from the irf command are shown in deviations from the respective approximation point or from the deterministic steady state?

Thank you in advance. 

Best, 
Johanna

**Comment by jmaih** [comment]
Hi Johanna,

1.  Fixed refers to some variables being fixed while imposed says that RISE should not check whether the approximation point is indeed the steady state
1.  Whenever a vector of variables does not solve the steady state, in the version of RISE you are running, the discrepancy is stored in @sig. RISE then tries to solve for the dynamics in such a way that the original problem `Ef(x(+1),x,x(-1),e)=0` despite the fact that the point we take the expansion around is not the steady state
1.  The point around which the expansion is done is the steady state or the imposed point. The only difference is that if the point taken say, x is not such that `f(x,x,x,0)=0`, then the resulting residual has to be dealt with such that we still have that the approximated problem is zero in expectation. Obviously the steady state is the only point such that `f(x,x,x,0)=0`.
1.  The IRFs are computed in deviation from the initial condition, which is the steady state.

Cheers,
J.
