### ISSUE TITLE
issue with KaijiTutorial

### ISSUE THREAD

**Issue by Kairey** [jmaih/RISE_toolbox#116]
Dear Maih,
     I encountered with some problems when using the code as follows:
 simple_irfs=irf(kaiji,'irf_periods',20);
kaiji_unant=kaiji.set('irf_anticipate',false);
myvector=[kaiji,kaiji_unant];
myirfs=irf(myvector,'irf_periods',20,'irf_horizon',3,'irf_shock_sign',1);
(sentence in "RISE-toolbox\examples\VariousModels\KaijiTutorial\howto_exp.m") 
     Then the error occurs:
Error using generic/set/set_one_at_a_time (line 232)
irf_horizon' is not a settable option or property of class rise
     My question is what's the correct sentence for definating the irf horizon for anticipation shocks in "myirfs=irf(...)"?
     Best,
     Kairey

**Comment by jmaih** [comment]
Hi Kairey,
I have tried to update the example but it is an old one that I should remove from the list of examples actually. It might work to some extent but I would recommend trying other examples.

Cheers,

J.

**Comment by Kairey** [comment]
Many thanks!
Best,
Kairey
