### ISSUE TITLE
Error using generic/irf

### ISSUE THREAD

**Issue by jkrenz** [jmaih/RISE_toolbox#118]
Hi Junior, 

after rising the model, solving it using [m,retcode]=solve(m) and printing the solution, I can see the steady state values as well as policy functions. So, I guess the model was solved?

However, when I then try to run some IR with myirfs=irf(m,'irf_regime_specific',true , 'irf_periods',20); I get the following error message:

Error using generic/irf
model cannot be solved

Error in generic/irf

Error in generic/irf

Error in dsge/irf

Error in driver_AQ_nophi (line 109)
myirfs=irf(m,'irf_regime_specific',true , 'irf_periods',20);

Where could this be coming from? Why can the model be solved but no IRFs can be computed?

Thanks in advance!
Best, Johanna

**Comment by jmaih** [comment]
Hi Johanna,

I do not understand how this could happen. Could, please, send me the replication files for the error?

Thanks,

J.

**Comment by jkrenz** [comment]
Hi Junior,
I got the error message only with a certain calibration of the model, I
will try to replicate the error and send you the files as soon as I'm back
to work (sometime by the middle of next week).
Best, Johanna

Am Do., 3. Okt. 2019 um 14:49 Uhr schrieb Junior Maih <
notifications@github.com>:

**Comment by jmaih** [comment]
Ok Johanna,

Have a good weekend. 

J. 

Sendt fra min iPhone
