### ISSUE TITLE
Error with estimating a model

### ISSUE THREAD

**Issue by tonyxia324** [jmaih/RISE_toolbox#119]
Hello Junior,

I am learning to use RISE to estimate Alstadheim et al. (2013) with a dataset of my own. I started with a model with no Markov switching and was able to solve the model by assuming the parameters following the posterior mode you estimated in your paper. However, while estimating the model with my own dataset, I receive the following error message: 
'find_posterior_mode:: No admissible starting value after 500 trials.'

This message is preceded by messages showing that the covariance of forecast errors not positive definite. I'm not sure what should I do to solve this problem. 

Thanks in advance!
Best,
Tony

Reference
Alstadheim, R., Bjørnland, H. C., & Maih, J. (2013). Do central banks respond to exchange rate movements? A Markov-switching structural investigation.

**Comment by jmaih** [comment]
Hi Tony,
It looks like you ran into a problem of stochastic singularity. Given that the initial parameter vector does not result in a successful computation of the likelihood, RISE attempts to start from different points by drawing random parameter vectors and then bails out after 500 trials. Perhaps you should consider adding measurement errors to the model. 

The way you add measurement errors is that you declare parameters with names "stderr_OBSNAME",  where OBSNAME is the name given to an endogenous observable variable. Let's say you have an observable variable called "Y". The corresponding measurement error parameter will be stderr_Y.

Then the measurement error parameters, or more exactly the standard deviation of measurement errors, can be treated like any other parameter in the model. That is, you can estimate or calibrate them.

Cheers,
J.

**Comment by tonyxia324** [comment]
Thank you for your prompt response!

Best,
Tony
