### ISSUE TITLE
Hessian Matrix

### ISSUE THREAD

**Issue by Alexfjs** [jmaih/RISE_toolbox#121]
Dear Junior

I write to you because I have a doubt with the Hessian in a model that I want to estimate.

Once the maximization of the posterior ends, it's yields the following:
posterior_maximization_variable_quantities :: gentle warning: The Hessian is Invalid

My question is why does this happen?
How can I solve that?

Beforehand thank you very much

**Comment by jmaih** [comment]
Dear Alex,

It is quite common to get a bad hessian/covariance matrix at the end of a posterior/likelihood maximization process. It is usually a sign that the optimizer could not reach the top but of a peak or that some estimated parameter lies up against the boundaries of the parameter space. 

However, the most important question, in my opinion, not wether you have a good or bad covariance matrix. The real question is what do you need the covariance matrix for. 

1-) you want to compute the numerical standard errors of the parameters (especially in the classical inference) or you want to compute the Laplace approximation of the marginal data density. You definitely need a well-behaved covariance matrix. In this case I would suggest using an optimizer that will get you to a peak and or making sure the priors are “informative enough” to help guide the optimizer towards a peak. 

2-) you want to use the covariance matrix for sampling the posterior distribution. The theory says that all you need is a well defined covariance matrix. You can either “repair” the covariance matrix, forcing it to be positive definite or use any good covariance matrix. In both cases I would recommend using a sampling algorithm that updates the covariance matrix during the sampling process. 

RISE has a utility function “utils.cov.nearest” that would turn any covariance matrix into a positive definite covariance matrix. But obviously the resulting covariance does not necessarily reflect the “true” correlations between the parameters. 

Cheers,

J. 

Sendt fra min iPhone

**Comment by Alexfjs** [comment]
Thanks a lot Junior

Cheers
