### ISSUE TITLE
Endogenous Markov-Switching and estimation

### ISSUE THREAD

**Issue by luishb1** [jmaih/RISE_toolbox#123]
Hi,
first thank you so much for sharing this toolbox. I am new here, I would like to know whether is posible to estimate a DSGE model that incorporates endogenous Markov-Switching.

Thanks in advance

**Comment by jmaih** [comment]
Hi,

Yes it is possible. But if you are new to RISE you may need to learn the
basics first.

Cheers,

J.

**Comment by luishb1** [comment]
ok, thank you very much. Is there any user manual?

**Comment by jmaih** [comment]
Hi,

The best way to learn is to locate the examples folder and run the examples.

There used to be a user manual but it is currently under revision.

Cheers,

J.

**Comment by luishb1** [comment]
Ok. I really appreciate it. It is nice to have found this useful tool!

**Comment by luishb1** [comment]
Sorry for disturbing you again. I have been going through the examples and I realized that the way of writting down the model, variables, priors… is quite similar to dynare (so quite intuitive). Nevertheless, I do not find any example which estimates an endogenous Markov-Switching model. 
I do not know if you have uploaded the codes of your paper "State Space Models with Endogenous Regime Switching" because I think it would be the best example for understanding how to do what I have in mind.

Thank you very much in advanced.

**Comment by jmaih** [comment]
Hi,
We have not yet released the codes for the paper "State-Space Models with Endogenous Regime Switching", but Issue #29 shows how to set up endogenous probabilities.

Cheers,

J.
