### ISSUE TITLE
Estimate

### ISSUE THREAD

**Issue by xiongcheneco** [jmaih/RISE_toolbox#124]
Dear Junior,
I encountered a problem with RISE. I want to change the default optimization settings of  estimate command. But it report an error that:
'Options' is not a settable option or property of class rise
I have no idea how to debug this problem. Could you please help me?
 Many thanks !
 Best,
 Chen

**Comment by jmaih** [comment]
Hi Chen,

What do you want to change exactly?

J.

**Comment by xiongcheneco** [comment]
I want to parallel fmincon to accelerated calculation, 
options = optimoptions(@fmincon,'Algorithm','interior-point','UseParallel',true);
[estimate,filtration]=estimate(estimate,'optimizer','fmincon','Options',options );

**Comment by jmaih** [comment]
In that case
options=struct('Algorithm','interior-point','UseParallel',true);
[estimate,filtration]=estimate(estimate,'optimizer','fmincon','optimset',options )

Note that estimation is a difficult process. An accelerated estimation does not guarantee that you will get to the global peak or that you will even reach a peak.

**Comment by xiongcheneco** [comment]
Thank you very much for your reply. I know estimation is not easy, but I still want to know wheter there is anyway to change the default options of  optimization function ?
Many thanks !
Best,
Chen

**Comment by xiongcheneco** [comment]
Thank you very much for your reply. I know estimation is not easy, but I still want to know wheter there is anyway to change the default options of  optimization function ?
Many thanks !
Best,
Chen

**Comment by xiongcheneco** [comment]
Sorry !  I am very sorry that I did not see clearly and I know now.
Many thanks !
 Best,
 Chen
