### ISSUE TITLE
Some fundamental issues

### ISSUE THREAD

**Issue by Kairey** [jmaih/RISE_toolbox#126]
Dear Maih,
I have learned your RISE for a long time, now I am confused with some fundamental issues, I searched a lot, but still haven't solved.
1. I wan't to estimate the correlation between two shocks(eps_a,eps_b), and I wan't to set the scale of shocks. I wanna know how to define them in the rs file.
2. Are the command "m=estimate(m)" based on Maximum likelihood estimation? While command "Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG)" depends on Bayesian estimation?
3.  If I wanna do some further analysis based on Bayesian estimation, should I create an new object (new_m) after I get the Results of MCMC sampling, and then just run irfs=irf(new_m), histdec=historical_decomposition(new_m)? But how to create the new object (new_m)?
I don't know whether these thoughts can be done in RISE. Could you help me? Thanks in advance!
Best,
Kairey

**Comment by jmaih** [comment]
Hi Karey,

   1. RISE does not handle correlated shocks. But you can always rewrite a
   vector of correlated shocks as a combination of uncorrelated shocks.
   Suppose for instance that e1 and e2 are correlated. Then I can always write
   e1=a1*u1+b1*u2   and  e2=a2*u1+b2*u2   where u1 and u2 are uncorrelated.
   That means that you have to declare e1 and e2 as endogenous variables
   2. m=estimate(m) maximizes the posterior distribution, that is the
   combination of the likelihood and the prior. The results is a single
   parameter vector. Whether you do maximum likelihood or Bayesian
   estimation depends on your prior distribution on the parameters. mh_sampler
   takes a sample from the posterior distribution. The results is a group of
   parameter vectors.
   3. https://github.com/jmaih/RISE_toolbox/issues/80#issuecomment-396876805

Cheers,

J.

**Comment by Kairey** [comment]
Now I understand, it's so nice of you, many thanks.
Best,
Kairey
