### ISSUE TITLE
How to declare a transformation of a parameter

### ISSUE THREAD

**Issue by eleonoraoliveira** [jmaih/RISE_toolbox#127]
Hello, Mr. Maih

I'm working with a simple New Keynesian model with two exogenous regimes, adapted from the model in Hirose and Naganuma (2007) avaiable here (https://www.boj.or.jp/en/research/wps_rev/wps_2007/data/wp07e24.pdf).

I want to declare beta, the discount factor, as a transformation of another parameter. In Dynare, according to the UserGuide, this is possible by adding a pound sign (#) at the beginning of the
corresponding line. So I did the same in my .rs file, but an error message appears:
" Error using file2blocks/construct_list (line 652)
 atom '#' in dissertacao at line 94 is not a valid variable or parameter name "

I tried to withdraw the the pound sign, but then I have another error message:
" Error using file2blocks/construct_list (line 652)
 atom '100' in dissertacao at line 94 is not a valid variable or parameter name "

How can I declare this transformation?
My codes are attached.
I really appreciate your patience and help.

Best regards,
Eleonora.

[parameter_transformation.zip](https://github.com/jmaih/RISE_toolbox/files/4333618/parameter_transformation.zip)

**Comment by jmaih** [comment]
Hi Eleonora,

Your mistakes are as follows:

   1. you did not issue a declaration for  the model block. As a
   consequence, the equations were read as if they were parameters or variables
   2. after adding "model", you should add a # sign in front of beta
   3. you should end every equation with a semi-colon. beta =.... ;
   4. you declared psi_y twice. If the parameter is switching, it cannot be
   declared both in the list of constant parameters and in a list of switching
   parameters
   5. you are confused between setting parameters and declaring parameters.
   In particular, right after declaring "parameters coef_tp_1_2 coef_tp_2_1"
   "parameters(coef,2) psi_y", you start assigning values to parameters
   without declaring that this is "parameterization" block
   6. The following statement "psi_Pi,     1,50, 1.25, 1.74,
   gamma_pdf(0.90);" is wrong. You probably meant "psi_Pi,     1.50, 1.25,
   1.74, gamma_pdf(0.90);"
   7. In the statement "gamma_star, 0.75, 0.88, 0.99, gamma_pdf(0.90);" it
   is not possible to find a gamma distribution that satisfies the requirement
   that 0.88 and 0.99 covers 90% of the probability mass. In addition, the
   start value of 0.75 is clearly below the lower quantile of 0.88
   8. You declared scales on shocks: 'sigma_a'    'sigma_d'    'sigma_r'
    'sigma_z' but you did not attach them to the corresponding shocks


I attach a corrected version of your code that you may want to update.

Cheers,

J.

**Comment by eleonoraoliveira** [comment]
Hello, Mr. Maih

Thank you so much for your avaiability. 
Now I see the silly mistakes that were preventing me from running the code, and I´m sorry to occupy your time with them.
I will correct them.
Where did you attach your corrected version? I may be letting go, but I didn't found it. 

Thanks for your help!

Cheers, 

Eleonora.

**Comment by jmaih** [comment]
Sorry,
Here it is!

Cheers,
J.

[dissertacao_corrected.zip](https://github.com/jmaih/RISE_toolbox/files/4336456/dissertacao_corrected.zip)

**Comment by eleonoraoliveira** [comment]
Hi, Mr. Maih

Could you help me solve a problem with the estimation?
When I run my file howto., a message appears several times, saying that there is a problem with the transition matrix. 
And then appears this message:

Error using find_posterior_mode (line 96)
find_posterior_mode:: No admissible starting value after 500 trials

Error in C:\Users\Eleonora\Documents\GitHub\RISE_toolbox\classes\models\@generic\estimate.p>estimate
(line 181)
%      D, and finally Mean0 and Cov0. Additionally, if the observation equation

Error in C:\Users\Eleonora\Documents\GitHub\RISE_toolbox\classes\models\@dsge\estimate.p>estimate (line
217)
%      observations, such that the deflated data is given by y(t) - z(t)*b.

What do I need to correct?

Thanks so much for your help!

Best regards,
Eleonora.

[Estimation.zip](https://github.com/jmaih/RISE_toolbox/files/4397120/Estimation.zip)

**Comment by jmaih** [comment]
The lines 175 and 176 in your model file are as follows

coef_tp_1_2,        0.0128 ,    0.001,    0.3,   beta_pdf(0.9); %Andreza
coef_tp_1_2,        0.0128,     0.001,    0.3,   beta_pdf(0.9): %Andreza

As you can see, it is the same transition probability in both cases

My guess is that one of the them should have been :

coef_tp_2_1

Cheers,

J.

**Comment by eleonoraoliveira** [comment]
Thank you for your help, Mr. Maih.

In fact, the transition probabilities were wrong, but even after the correction, the same error appeared.
So I changed the paramter´s distribution and now it runs.

Thank you so much for your help!

Best regards!

Eleonora.

**Comment by jmaih** [comment]
Cheers,

J. 

Sendt fra min iPhone
