### ISSUE TITLE
Splanar and Short-Circuiting

### ISSUE THREAD

**Issue by edugca** [jmaih/RISE_toolbox#128]
Hi Hunior,

I wonder whether there is a technical reason for splanar operations to not allow for short-circuiting such as && and || . I found this issue by evaluating the following line inside of an external function that I call in my model.

Let d1 and d2 be splanars and n be a double
d1 == -d2 && n > 2

It gives the following error message: "Conversion to logical from splanar is not possible."

The same will happen evaluating the expression d1 == -d2 || n > 2

One can reproduce the error with the following code:
d1 = splanar();
d2 = splanar();
n = 2;
d1 == -d2 && n > 2

Best regards,
Eduardo Amaral

**Comment by jmaih** [comment]
Hi Eduardo,

Try writing your function with single & or |.

Cheers,

J. 

Sendt fra min iPhone

**Comment by edugca** [comment]
Thanks for the prompt answer!

I can certainly do as you suggested in the example that I gave you.

I bumped into that issue because my function called the Matlab function
"linspace", which has these && and || inside of it. In my code, I can
simply replace "linspace" by something like "initial:interval:end", but I
wonder that in more complicated Matlab functions this situation can happen
again.

Best regards,
Eduardo Amaral

Em qua., 25 de mar. de 2020 às 19:23, Junior Maih <notifications@github.com>
escreveu:

**Comment by jmaih** [comment]
RISE needs to symbolically differentiate all the functions in the model block. This could well be an instance where RISE doesn’t know how to behave. Could you send me the example?

Cheers,
J.

**Comment by edugca** [comment]
Yes, I guess this is exactly what happens.

I noticed 3 cases in which RISE doesn’t know how to behave (splanar operations):

1) Short-circuiting: && and ||
2) "initial:interval:final", where {initial, interval, final} are splanars
3) Min(vector of splanars)

My code is attached. It stucks at a line which is an example of the third case (most urgent). Just run "helpModel.m".

To give a context, I am trying to solve a closed-economy model with an upper limit on the tax rate (occasionally binding constraint) and an endogenous regime switching (default or not default). The probability of defaulting is state-dependent on the shocks and it is given by an external function which maps the shocks with the values of a matrix obtained outside of RISE.

[Help.zip](https://github.com/jmaih/RISE_toolbox/files/4396209/Help.zip)

**Comment by jmaih** [comment]
I have not looked at your model yet but following your explanations, you are calling a function with potentially discrete support and discontinuities. This is not the kind of game that RISE plays. 

Whenever you have a function that is unknown to RISE you have to provide its derivatives yourself. Do you know how to differentiate the external function?

J. 

Sendt fra min iPhone

**Comment by edugca** [comment]
There is, in fact, a discrete support which I interpolate using cubic spline. In case I am able to differentiate an approximation function, how can I provide its derivative to RISE?

**Comment by jmaih** [comment]
function y=edugca(z,a1,...an,varargin)
% - put the key argument in first position
% - varargin can be empty in which case we evaluate the main function
% - if varargin is not empty, it should have two elements
%   - the first element should be 'diff'
%   - the second is the order of differentiation
%

Sendt fra min iPhone

**Comment by edugca** [comment]
Thanks for the answer, Junior. I ended up approximating my discrete support with a polynomial so that derivatives are not an issue anymore.

I have another doubt now that I will include in a different thread.
