### ISSUE TITLE
irf problem

### ISSUE THREAD

**Issue by narmindavoudi** [jmaih/RISE_toolbox#129]
Hi Dear Junior
while solving my model, I  faced  an error in computing irfs, the model was solved by any solver except fwz,
but when I want to compute irfs, after solving, it gives me error noting that optimal policy irfs will be computed for a perturbation of order 1......and...very surprisingly the error: model can not be solved, but I have result of solving!!!!!!!
As I got from your papers, one of the advantages of new solvers is their ability to solve the model not just for perturbation order 1, 
Now, I will be appreciate so much if you kindly guide me for this error.
Thank you so much

**Comment by jmaih** [comment]
Hi,

I am not sure I understand your problem. You are talking about different
solvers, optimal policy, fwz, perturbation of possibly higher order,
impulse responses, etc. Is your model a regime-switching model? Is it an
optimal policy model? At what order of perturbation are you solving it?
What is the error you are getting?

J.

**Comment by narmindavoudi** [comment]
Hi,
I really appreciate spending your time to answer my questions, I got that my model is not stable, 
thank you again,
sincerely
Narmin Davoudi
Urmia university, phD student

**Comment by jmaih** [comment]
Dear Narmin,

Keep up the good work.

Cheers,

J.

**Comment by narmindavoudi** [comment]
so what is the reason of instability of the model in rs-dsge models? is there any special condition for stability in these models?
I must change my constant parameters, or switching one?

**Comment by jmaih** [comment]
For any model, the stability depends on the specific details of the
equations, the parametrization, etc.

The stability criterion used in constant-parameter DSGE models is the
Blanchard-Kahn conditions that determine both uniqueness and stability.

Unfortunately those conditions do not extend to RS-DSGE models. RISE
borrows the concept of Mean Square Stability (MSS) from the engineering
literature, following the work of Svensson, Tao Zha and Dan Waggoner among
others.

A RS-DSGE model is going to be mean square stable if for any initial
condition x0, there exists a finite vector MU and a covariance matrix SIGMA
such that in the limit, the expected value E(x_t) converges to MU and the
covariance V(x_t) converges to SIGMA.

Cheers,

J.
