### ISSUE TITLE
steady state caculate 

### ISSUE THREAD

**Issue by guderian2015** [jmaih/RISE_toolbox#130]
dear Junior:
I try a ms-dsge model in rise toolbox and I have a problem. Firstly I try my model on dynare and it can run with standard irfs, but when I try to modify it on rise toolkit and I get the information:"Steady state could not solve
MODEL  HAS NOT BEEN SOLVED AT LEAST UP TO THE FIRST ORDER
MODEL  HAS NOT BEEN SOLVED AT LEAST UP TO THE FIRST ORDER" 
Now, I will be appreciate so much if you kindly guide me for this error.
Thank you so much.
Regards
Shentu

**Comment by jmaih** [comment]
Hi Shentu,

Did you correctly translate the file from dynare to RISE?

Could you send me the dynare file and possibly your RISE file so that I can
see what is going on?

Cheers,

J.

**Comment by guderian2015** [comment]
> Hi Shentu,
> 
> Did you correctly translate the file from dynare to RISE?
> 
> Could you send me the dynare file and possibly your RISE file so that I can
> see what is going on?
> 
> Cheers,
> 
> J.
> …

dear Junior:
Thank you for your reply, I will check my rs file and post it to you through e-mail.
Regards
Shentu

**Comment by jmaih** [comment]
Hi Shentu,

I have not looked at your RISE file. But in the original dynare file, the equation at line 139 is

`pwf=s*pfs;`

where pfs is an exogenous shock. But then, the steady state of pwf is ZERO.

However, there is another equation (line 95)

`xf=pf/pwf;`

which implies that we cannot have pwf = 0 , contradicting what we found above.

Cheers,

J.

**Comment by guderian2015** [comment]
> Hi Shentu,
> I have not looked at your RISE file. But in the original dynare file, the equation at line 139 is
> pwf=s*pfs;
> where pfs is an exogenous shock. But then, the steady state of pwf is ZERO.
> However, there is another equation (line 95)
> xf=pf/pwf;
> which implies that we cannot have pwf = 0 , contradicting what we found above.
> Cheers,
> J.

thank for your reply! I have solved my problem and the rs file can successfully run.><
Regards
Shenru

**Comment by jmaih** [comment]
Cheers,

J. 

Sendt fra min iPhone
