### ISSUE TITLE
Metropolis Hastings in Parallel

### ISSUE THREAD

**Issue by edugca** [jmaih/RISE_toolbox#131]
Hi Junior,

Is it possible to parallelize the MH sampler function in the RISE? If yes, do you have any example of how to do that?

Best regards,
Eduardo

**Comment by jmaih** [comment]
Hi Eduardo,

Parallelization is the default mode of the sampler. 

If you start the parallel computing toolbox on your computer, the sampler will use the workers available. All you have to do is have the workers ready. 

Cheers,

J. 

Sendt fra min iPhone
