### ISSUE TITLE
optimizers

### ISSUE THREAD

**Issue by Kairey** [jmaih/RISE_toolbox#132]
Dear Maih,
      I know RISE can easily implement fmincon and bee_gate, but how to implement other Matlab's optimizers like "Marco Ratto’s newrat" and "Monte-Carlo based optimization routine"? 
      How to use these optimizers in RISE? Is there any example for referance? Thanks in advance.
Best,
Kairey

**Comment by Kairey** [comment]
Hi Maih,
Thanks very much, but I am a little confused. Could you please explain more specifically? or could you please programe it when you are free? Thanks again.
Best,
Kairey

**Comment by jmaih** [comment]
Please see Post #26

**Comment by Kairey** [comment]
Hi Maih,
Thanks very much. I have another stupid question. I wonder if I want to definite the scale and direction of shocks, what should I do? Is there any place to change in the rs file? 
Best,
Kairey

**Comment by jmaih** [comment]
Hi Karey,

Please open a new thread if you want to ask a different question.

You don't need to change anything to the model file. 

You can find the default option of the irf function by running

`irf(dsge,empty)`

The relevant option for you is "irf_shock_sign", whose default falue is 1. Now if you want to compute irfs with a 2 standard deviation shock, you can simply run

`myirfs=irf(m,'irf_shock_sign',2)
`
If instead you want to run an irf with a negative shock, simply run

`myirfs=irf(m,'irf_shock_sign',-1)`

In general then, running 

`myirfs=irf(m,'irf_shock_sign',a)` will scale the shocks by the value "a", which will be positive if you want a positive shock and negative if you want a negative shock.

Cheers,

J.

**Comment by Kairey** [comment]
So nice of you, Thanks very much.
Best,
Kairey
