### ISSUE TITLE
Comparing Models

### ISSUE THREAD

**Issue by edugca** [jmaih/RISE_toolbox#133]
Hi Junior,

Is there any example of RISE in which different DSGE model specifications are compared to find the one that best explains the data? Are there specific routines in RISE to do this comparison?

Best regards,
Eduardo

**Comment by jmaih** [comment]
Hi Eduardo,

There are no examples that do model comparison explicitly. In a Bayesian context, we typically compare models by looking at their marginal data densities (MDD). When you do posterior maximization you will get the Laplace approximation of the MDD. The model with highest MDD explains the data best.

If instead you are doing maximum likelihood, that is you are doing classical inference, you can compare models using the likelihood ratio test, the Wald test, etc. You can look up those tests in any basic econometrics book.

cheers,

J.
