### ISSUE TITLE
error in running 

### ISSUE THREAD

**Issue by narmindavoudi** [jmaih/RISE_toolbox#135]
Hi dear Mr. Maih
Hope you are ok and far from corona virus,
while running 'the plot impulse response code, this error occurs:
Error in set (line 17)
    self=set@abstvar(varargin{:});
'abstvar' is not a valid base class.
and a warning like this:
Warning: Error updating AxesLayoutManager.
 Unable to compute axes layout information
what should I do for this error?
sincerely,
Narmin Davoudi
PhD student
Urmia university

**Comment by jmaih** [comment]
Hi Narmin,

I do not understand the problem without seeing the setup. If you don't mind
sending me what I need to be able to replicate the problem, I will look
into it when time permits.

Do you follow the exact steps you see in the example files?

Cheers,

J.
