### ISSUE TITLE
the problems of trials and singularity

### ISSUE THREAD

**Issue by 55Kidd** [jmaih/RISE_toolbox#137]
Dear Junior Maih:
Is the result reliable with only 2 trials？Could you please tell me how to deal with the problems of trials and singularity? Here is my code：
[1.zip](https://github.com/jmaih/RISE_toolbox/files/4837683/1.zip)
Many thanks!
Kidd
June 26, 2020

**Comment by jmaih** [comment]
I was able to perform the following estimation using a different optimizer. fmincon is not a good enough optimizer for your problem. Consider for instance using the following results as initial conditions in your estimation problem.

`
MODEL  ESTIMATION RESULTS 
                 distribution    initval     mode      mode_std 
                 ____________    _______    _______    _________

    g            BETA            0.65       0.91646    0.0080197
    ksi          GAMMA              3         3.049     0.057617
    fai_k        GAMMA             60        96.173       20.264
    rho_am       BETA             0.6       0.97439      0.10356
    sig_am       INV_GAMMA       5.09        1.8185       0.1138
    fai_p        GAMMA             60        102.36       24.083
    re           BETA             0.8       0.68121      0.11456
    de_g         BETA             0.3       0.29756     0.073699
    de_d         BETA             0.3       0.29638     0.074403
    rho_o        BETA             0.6       0.77455      0.10562
    sig_o        INV_GAMMA       9.81        8.3267      0.83134
    rho_ao       BETA             0.6       0.69619     0.097327
    sig_ao       INV_GAMMA        6.3        5.9955      0.26672
    rho_tao      BETA             0.6       0.95831       0.0567
    omega_y      GAMMA            0.5       0.55896      0.15041
    omega_pai    GAMMA            1.5         3.001      0.83377
    omega_r      GAMMA            0.5       0.38651      0.13968
    sig_tao      INV_GAMMA         10        7.9058      0.51555
                 ____________    _______    _______    _________

                 distribution    initval     mode      mode_std 

log-post: -354.7995 log-lik: -309.4384 log-prior: -45.3611 log-endog_prior   0.0000 numberOfActiveInequalities 0 
log-MDD(Laplace) -386.0387868 
estimation sample is:  1996Q1 : 2015Q4 (80 observations) 
solution algorithm is:  rise_1 
estimation algorithm is:  bee_gate 
number of estimated parameters is:  18 
number of function evaluations is:  32806 `
