### ISSUE TITLE
Filtering and smoothing without estimating

### ISSUE THREAD

**Issue by edugca** [jmaih/RISE_toolbox#138]
Hi Junior,

I am trying to filter and smooth my model before estimation, but I'm getting the error messages below (replication files are attached). Thanks a lot if you find any time to look into!

**1) When filtering**

>> myFiltSmooth = filter(mdlVector(iMdl),'data',data,'kf_tol',0);
Operands to the || and && operators must be convertible to logical scalar values.

Error in fix_point_iterator

Error in doubling_solve

Error in lyapunov_equation

Error in lyapunov_equation

Error in dsge/filter_initialization

Error in dsge/filter_initialization

Error in dsge/filter

**2) When smoothing**

myFiltSmooth = smooth(mdlVector(iMdl),'data',data);
Error using NaN
Input following 'like' is not a single or double array.

Error in smooth (line 163)
c = NaN(size(y),'like',y);

Best,
Eduardo

**Comment by jmaih** [comment]
Hi Eduardo,

RISE does not have a function called smooth. You are probably using Matlab's econometric toolbox ...

If that's the case, look for help within Matlab or contact the Mathworks directly.

Cheers,

J.

**Comment by edugca** [comment]
Hi Junior, thanks for the reply!

But, what about the error in the filter function? By the error message that I received it tells me that it is a Rise function.

**Comment by jmaih** [comment]
The exact filter function that you use depends on the inputs that are passed to the function. I cannot say more without seeing the codes. I presume mdlVector(iMdl) is a dsge object?

**Comment by edugca** [comment]
Exactly, mdlVector is a vector of DSGE objects. For whenever you have time, the code is attached.

Best
 
[errorReplication.zip](https://github.com/jmaih/RISE_toolbox/files/4972500/errorReplication.zip)

**Comment by jmaih** [comment]
I am using a different version of RISE. Can you post the full log of error you get?

**Comment by edugca** [comment]
Do you mean the message in the command window? This is what is displayed on it:

------------------------

Operands to the || and && operators must be convertible to logical scalar values.

Error in fix_point_iterator

Error in doubling_solve

Error in lyapunov_equation

Error in lyapunov_equation

Error in dsge/filter_initialization

Error in dsge/filter_initialization

Error in dsge/filter

Error in errorReplication (line 11)
myFiltSmooth = filter(mdlVector(1),'data',data);

**Comment by mvpaula** [comment]
Hi Junior!
I have a doubt about filtering and smoothing without estimating. 
After running the MCMC, will the filtered variables change? Do they not depend on the parameters? How can I learn about this? I am lost in this matter. If I don't run the MCMC, I won't have the posterior ones.

**Comment by jmaih** [comment]
> Do you mean the message in the command window? This is what is displayed on it:
> 
> Operands to the || and && operators must be convertible to logical scalar values.
> 
> Error in fix_point_iterator
> 
> Error in doubling_solve
> 
> Error in lyapunov_equation
> 
> Error in lyapunov_equation
> 
> Error in dsge/filter_initialization
> 
> Error in dsge/filter_initialization
> 
> Error in dsge/filter
> 
> Error in errorReplication (line 11)
> myFiltSmooth = filter(mdlVector(1),'data',data);

If possible, please, post the replication files for me to look into.

cheers,

J.

**Comment by edugca** [comment]
Hi Junior, I have already sent them, but I can send them again (attached).

Em qui., 30 de jul. de 2020 às 19:21, Junior Maih <notifications@github.com>
escreveu:

**Comment by jmaih** [comment]
I can't see anything attached to this message.

J.

**Comment by jmaih** [comment]
Hi Eduardo,
I have just looked at your files and tried to run them but there is a file missing "MultiPolRegress.m". But it is not necessary to send me the file. 

What I hope you can send me is (1) a model file, (2) the parameter values, (3) the data (4) possibly any function that is written in the model file and that is unknown to matlab.  Nothing else. With this I should be able to replicate the problem.

Do you think this is something you can do?

Cheers,

J.
