### ISSUE TITLE
error in tutorial1

### ISSUE THREAD

**Issue by narmindavoudi** [jmaih/RISE_toolbox#139]
Hi dear Maih
I tried to solve the problem printing impulse-response in tutorial1, but unfortunately I could not. I guess it is made because some problem in my matlab, but would you please check these error for me in tutorial 1:

while running "%% compare the irfs of the various models", these errors occures:
"Warning: Error occurred while executing the listener
callback for event Reparent defined for class
matlab.graphics.axis.Axes:
'abstvar' is not a valid base class.
Error in set (line 17)
    self=set@abstvar(varargin{:});
Error in matlab.graphics.shape.internal.AxesLayoutManager
Error in
matlab.graphics.shape.internal.AxesLayoutManager>@(h,e)localReparentCB(h,e,hObj)
Error in
matlab.graphics.shape.internal.AxesLayoutManager/insertAboveAxes
Error in
matlab.graphics.shape.internal.AxesLayoutManager.getManager
Error in legendcolorbarlayout (line 19)
hManager  =
matlab.graphics.shape.internal.AxesLayoutManager.getManager(hAx);
Error in matlab.graphics.illustration.Legend/setAxesImpl
Error in matlab.graphics.illustration.Legend/set.Axes_I
Error in matlab.graphics.illustration.Legend/set.Axes
Error in legend>make_legend (line 336)
        leg.Axes = ha;
Error in legend (line 261)
    make_legend(ha,args(arg:end),version);
Error in LiveEditorEvaluationHelperESectionEval (line 95)
                legend(labels(:,2))
Error in matlab.internal.editor.evaluateCode 
'abstvar' is not a valid base class.
Error in set (line 17)
    self=set@abstvar(varargin{:});
Error in legend (line 271)
    set(0,'CurrentFigure',old_currfig);
Error in howto (line 95)
                legend(labels(:,2))

Warning: Error updating AxesLayoutManager.

 Unable to compute axes layout information
 
Warning: Error updating Legend.

 narginchk: not enough input arguments
  
thank you in advanced, 
Narmin davoudi

**Comment by jmaih** [comment]
Hi,

There is not enough information in your post for me to determine what the problem is.

Cheers,

J.

**Comment by narmindavoudi** [comment]
Hi dear Mr. Maih
At first Thank you so much for spending your time answering our questions, your answers are so useful for us learning about RISE and enable us research more in these fields.
About errors mentioned in previous post, which occurs while running the 'print irfs', my question is "under what situation, matlab graphics shape error occurs?"  what is the meaning of "'abstvar' is not a valid base class."? which is written in 'set.m' line 17 (self=set@abstvar(varargin{:});), 
if you want to help me in this problem, what is the more information you need to determine the problem?
again thank you for your help
sincerely
Narmin

**Comment by TimMunday** [comment]
Hi - did you find a solution for this?

**Comment by jmaih** [comment]
I had to have a skype conversation with the lady and it turned out that she had conflict of functions due to the fact that she was permanently storing the paths for different toolboxes and their versions on the matlab path, which I strongly advise against.

**Comment by TimMunday** [comment]
OK great thanks for the reply - I will check in case I have the same issue
