### ISSUE TITLE
Error in endogenous transition probabilities

### ISSUE THREAD

**Issue by juanbaquero** [jmaih/RISE_toolbox#14]
DearJunior:

Im actually incorporating regime switching in the Curdia Woodford (2009) model. The model I did has an endogenous transition matrix which depends in a variable that has unique steady state.the model is successfully solved in first order but when I try to solve in second order ( with automatic derivatives) there is a problem in the derivatives. In the error appears the transition matrix multiplying an expression that RISE don't recognize. 

Thank you in advance

**Comment by jmaih** [comment]
Dear Juan,

Could you, please, past the entire error message you got so that I can see where the problem occurs? If would be even better if you could send me the files so that I can replicate the error myself.
thanks,

Junior

**Comment by jmaih** [comment]
Hi Juan,

Thanks for sending the files. I have investigated the problem. There are two ways to deal with it.

1. If you know that you are going to need higher-order derivatives, you may want to tell it to RISE when "rising" your model

```
m=rise(yourModel,'max_deriv_order',2)
```
with this you can solve a second order using symbolic derivatives.

2. There was a problem associated with automatic derivatives and it has now been corrected. If you want to use automatic derivatives then, you will have to update your version of RISE.

Cheers,

J.

**Comment by juanbaquero** [comment]
Thank you!
