### ISSUE TITLE
stability condition

### ISSUE THREAD

**Issue by narmindavoudi** [jmaih/RISE_toolbox#140]
Hi dear Mr Maih,
I had some problem in checking stability condition if you remember, you implied that the stability criterion used in constant-parameter DSGE models is the Blanchard-Kahn conditions, I figured out that if I can solve my model with constant parameters in dynare, so I can solve it in RISE too, so I have solved the model in dynare, and  Blanchard-Kahn condition was satisfied, but it is still unstable in RISE, is that possible, if yes, what's wrong in my model using RISE? 
Thank you really for your time spending to answer my questions, 
sincerely
Narmin

**Comment by jmaih** [comment]
Hi,

Could you share the dynare file?

Cheers,

J.

**Comment by narmindavoudi** [comment]
Hi Mr. Maih
Hope you are ok.
As you suggested for sharing dynare code to compare with rise code in stability problem,
I will send you dynare code in attachment,
I will be appreciated if you answer me the question: "why in dynare code the Blanchard-Khan condition is satisfied, while the same code in Rise is still unstable?"
sincerely
Narmin

________________________________

**Comment by jmaih** [comment]
Hi Narmin,

There is no disagreement between RISE and Dynare. The attachment below contains what you need to translate from dynare and solve the model in RISE.

[NoProblem.zip](https://github.com/jmaih/RISE_toolbox/files/5048069/NoProblem.zip)

Cheers,

J.
