### ISSUE TITLE
how to save results

### ISSUE THREAD

**Issue by drepalma** [jmaih/RISE_toolbox#143]
Dear Junior, 

I am trying to save the results (filtered and smoothed variables, posteriors, probabilities, etc), but without success.
How can I store the results to retrieve later? I'm using saveas, but it didn't work.

Thank you for your attention 
Best
Andreza

**Comment by jmaih** [comment]
Hi Andreza,

saveas is used for saving figures only

If you want to save variables, you should use "save" instead. 

If, say, you have a the model object which you have called, say, m

you can save it as `save andreza m`

if you have other variables, say v1 and v2, in the workspace you can add them to the statement above as `save andrez m v1 v2`

This is true for any variables whether it is smoothed variables, posteriors, probabilities, etc. 

Now when you want to load them back, you need to make sure that the version of RISE that computed the results you save is loaded. 

Lastly, make sure that the variables you are saving are really what you want to save, that is, they are not empty, they've been actually computed.

Cheers,

J.
