### ISSUE TITLE
Convergence diagnostic

### ISSUE THREAD

**Issue by drepalma** [jmaih/RISE_toolbox#144]
Dear Junior, 

I would like to check the convergence of MCMC (for example using Gelman-Rubin)
How can I implement the convergence diagnostic in RISE?

Thanks again for your attention and help.
Best Regards from Brazil
Andreza

**Comment by jmaih** [comment]
Dear Andreza,

The file ...\examples\VariousModels\TaoZha\LWZ_Econometrica2013\master.m shows how one can go about doing MCMC and then using the output of MCMC to check convergence diagnostics and do other things

- preparing the variables for posterior sampling `[objective,lb,ub,mu,SIG]=pull_objective(m);`
- running the Metropolis-Hastings algorithm `results=mh_sampler(objective,lb,ub,options,mu);`
- preparing the environment for convergence diagnostics `obj=mcmc(results,pnames)`, where pnames is the list of names of the estimated parameters
- then if you want to do the trace plots `traceplot(obj,name,chain_id)` where 'name' is the name of one particular parameter and 'chain_id' is the ID of the chain you want to do the traceplot from
- if you want to plot the density `densplot(obj,name,chain_id,N);` where N is the number of points to consider on the x-axis. The default is 250
- if you want to plot the recursive means `meanplot(obj,name,chain_id)`, where chain_id can be empty, in which case the recursive means of all the chains are plotted.
- If you want to plot the autocorrelation of a parameter `autocorrplot(obj,name,chain_id,order)` where 'order' is the maximum order of the autocorrelation to consider. It can be left empty in which case the default value is used. 
- if you want to plot the Potential Scale Reduction Factor (PSRF), `psrf_plot(obj,name)`
- if you want to do a scatter plot for two parameters, `scatterplot(obj,name1,name2,chain_id)`

cheers,
J.
