### ISSUE TITLE
The estimation about bee_gate

### ISSUE THREAD

**Issue by 55Kidd** [jmaih/RISE_toolbox#146]
Dear Junior:
I'm sorry to disturb you again. I changed fmincon to bee_gate as the optimizer to estimate the model in #137 .However, I got the massage: 
utils.optim.generate_candidates/loop_body (line 123)
generate_candidates:: could not generate a valid candidate after 5000 attempts. Exiting with
the best vector
How did you get the result? Could you please give me the code?
Many thanks!
Kidd
2020.08.07

**Comment by jmaih** [comment]
Attached

[KiddZip.zip](https://github.com/jmaih/RISE_toolbox/files/5044800/KiddZip.zip)
