### ISSUE TITLE
The question about counterfactual

### ISSUE THREAD

**Issue by 55Kidd** [jmaih/RISE_toolbox#147]
Dear Junior:
I'm sorry to disturb you again. I tried to use the function 'counterfactual' to defined the counterf following the example of KaijiTutorial. However, I got the massage: 
Reference to non-existent field 'solve_user_defined_shocks'
Error dsge/filter
Error dsge/counterfactual
And I found that there is no 'solve_user_defined_shocks' in the result of 'rise.options' when I use the newest RISE_toolbox. However, the result of 'rise.options' has 'solve_user_defined_shocks' when I use the previous version. So, could you tell me how to modify the code?
Many thanks!
Kidd
2020.08.14

**Comment by jmaih** [comment]
The example is deprecated. But do reopen the issue if you still want to run it.

**Comment by taherfahmi** [comment]
Dear Prof. Maih,

Is there any other example of counterfactuals available? I have searched and did not find any. I am trying to conduct my counterfactual scenarios, but I am having a hard time with the syntax.

Thank you so much!
