### ISSUE TITLE
check plot 

### ISSUE THREAD

**Issue by drepalma** [jmaih/RISE_toolbox#148]
Dear Junior, 

I would like to know if RISE has any options similar to the **check plot** available in Dynare?

Thank you in advance for your attention!
best regards from Brazil
Andreza

**Comment by jmaih** [comment]
Dear Andreza,

In RISE the function is called mode_curvature. For details, check the help
by running

help dsge.mode_curvature

Cheers,

J.

**Comment by drepalma** [comment]
Dear Junior, 

Thank you very much!
This worked, but the results that I found are not very adequate.
How can I improve the mode_curvature? Should I change the priors or change the optimizer? Could you give me some guide?
Thank you very much in advance for your help and attention. 
Best Regards , 
andreza

**Comment by jmaih** [comment]
Hi Andreza,

The mode curvature does what it does independently of the optimization
procedure used. If for some reason the optimization does not reach a peak,
this will most likely show up in your mode curvature.

Your intuition is correct that changing priors to more informative ones may
help... by masking the deficiencies of the optimization procedure.

If you don't have a better optimizer, that might be one way to go.

The most important question, however, is not about whether posterior
maximization was successful or not. The real question is what you plan to
do with your estimates. For instance, if your ultimate goal is to do
posterior simulation, you don't need to reach a peak, you don't even need
to do posterior maximization first : the peak you are looking for in the
posterior maximization phase is just one point in the entire posterior
surface.

But if having nice-looking pictures of the mode curvature is a goal in
itself, well, you need a good optimization procedure and good priors.

Cheers,

J.
