### ISSUE TITLE
plotting irfs in all RISE examples

### ISSUE THREAD

**Issue by narmindavoudi** [jmaih/RISE_toolbox#149]
Hi dear Mr. Maih
At first Thank you so much for spending your time answering our questions, your answers are so useful for us learning about RISE and enable us research more in these fields.
About errors mentioned in previous issue, which occurs while running the 'print irfs', I tried  all examples of RISE toolbox which has 'plot irfs' 's order,  like "GavinKeenRichterThrockMorton" and "Smets Wouters" in markovswitching example, I faced this error while running the order " plot irfs", (I sent you the print-screen of the error in attachment). I wonder if the problem is due to my matlab software (for example it needs some adjustments, or not? would you please give me some guide?
if you want to help me in this problem, what is the more information you need to determine the problem?
again thank you for your help
sincerely
Narmin
[screen shot.pdf](https://github.com/jmaih/RISE_toolbox/files/5203144/screen.shot.pdf)

**Comment by jmaih** [comment]
Dear Narmin,

What you are sending me is not an error message, it is a warning.

I can see from the address bar that you are in a folder with markov
switching dsge examples. There is no way running those examples is going to
call abstvar.

The relevant questions are whether :

   1. you loaded RISE properly
   2. you are running the codes properly

Unfortunately, just by seeing the warning message I cannot tell what
problem occurred.

Cheers,

J.

**Comment by narmindavoudi** [comment]
Hello Mr. junior
Thanks for your attention
you can see the errors in screenshot in attachment
best regard 
Narmin 
![Screenshot 2020-09-10 ](https://user-images.githubusercontent.com/47849581/92781794-ade22600-f3b9-11ea-9c8e-0e4cdcd6de36.png)

**Comment by jmaih** [comment]
Narmin,

As  I said before I don't know what you are doing to get that error
message. For sure you are doing something that Matlab or rise do not
recognize.

J

**Comment by narmindavoudi** [comment]
Dear Junior
I do really apologize for repeating my question,
actually, I do nothing by myself or on my own model, I am just running "howto.m" in Markov Switching example folder,  step by step. all steps run properly, but "Plot irfs" step, gives these errors
you think it is from my RISE installation? (something is wrong or incomplete? and it needs to be installed again?)
see the attachment please
thank you so much

________________________________

**Comment by jmaih** [comment]
Hi Narmin,

In that case you may want to check

   1. the version of matlab you are using
   2. whether you downloaded RISE properly
   3. whether you load rise correctly by calling rise_startup
   4. whether you have not mistakenly saved some paths from a different
   version of RISE
   5. whether you need to restart matlab

Please check this and let me know,

J.

**Comment by narmindavoudi** [comment]
Hi dear Junior,
As you guided me testing some cases in exploration some error reasons, I did all and got some results:

  1.  the version of matlab which I'm using is R2018b.
  2.  I downloaded RISE-toolbox-master from github.com az zip again, added it's path to matlab, ran rise_startup and faced attached error.

              I realized something:

  *   In new downloaded folder of rise_toolbox, rise_startup m_file is empty and uncomplete and any function not included in. I replaced the old rise_startup M_file, and again faced the same error but with identified the line that error occurred.
  *    the other M-files like rise_exit, Contents,  have the same problem.

matlab works properly, because in using dynare, irfs figures appear correctly.
I will be appreciated if you help me in these problems.
sincerely
Narmin Davoudi

________________________________

**Comment by jmaih** [comment]
I can imagine your frustration.

Can you share your screen in skype or google meet so that I see what are
the exact steps you are following?

If you have my email address, send me yours so that I can invite you on a
virtual google meet meeting.

J.

**Comment by narmindavoudi** [comment]
I really appreciate your attention, thank you so much dear junior,
I sent you a massage on skype, by Narmin Davoudi,
Thank you again


________________________________
