### ISSUE TITLE
Markov Chains in separated Files 

### ISSUE THREAD

**Issue by LeonardRW** [jmaih/RISE_toolbox#15]
Hi Junior,

I'm trying to setup the priors in a separate file using the syntax for Bayesian priors with mean an std. deviation:
 P.pname={start_value,prior_mean,prior_stdev,'distribution',lower_bound,upper_bound};

It works correctly for the constant parameter case. But when I try to use markov chains don't know how to do the correct syntax for the parameters. The standard syntax say:
 lambda_1(coef,1)={...}; 
lambda_1(coef,2)={...} ;
does not work. How can I do it in the correct form?

Thanks in advance,
Leonard.

**Comment by jmaih** [comment]
Hi Leonard,

This is simple
```
pname(chain,state) 
```
becomes 
```
pname_chain_state
```

Cheers,

Junior
