### ISSUE TITLE
Parameters must have same value in both states

### ISSUE THREAD

**Issue by VanessaKunzmann** [jmaih/RISE_toolbox#151]
I am working on a regime switching DSGE model and face the problem that my model only solves whenever I give the policy parameters the same value in both states/regimes. Thereby it does not matter what values as long as they are the same. 

What could be the reason for this? Thank you very much!

**Comment by jmaih** [comment]
Hi,

It could be anything including the structure of the transition probabilities. 

It is impossible for me to tell you what the problem is without seeing the model. 

Cheers 

Sendt fra min iPhone

**Comment by VanessaKunzmann** [comment]
Hi,
thanks for the quick response. Attached is my Model. I am working on a Two Country DSGE Model with Fiscal Regime Switching in both countries. The model has a similar setup as in Rabanal (2009).
[Rab_open2states.zip](https://github.com/jmaih/RISE_toolbox/files/5634736/Rab_open2states.zip)

I would really appreciate if you can find anything that causes this problem.
Thank you in advance!

**Comment by jmaih** [comment]
What should I run to replicate the problem you are having?

**Comment by VanessaKunzmann** [comment]
If you run run2states.m it is currently running through because all policy coefficients have the same values in each state (but I need different coefficients in each state) but as soon as I change just one number it is not working any more.

line 203-208:
This is working:
phi_b(a,1),-0.0122;
phi_b(a,2),-0.0122;
phi_g(a,1), 0.5172;
phi_g(a,2), 0.5172;
phi_y(a,1), 0.2025;
phi_y(a,2), 0.2025;

This is not:
phi_b(a,1),-0.0122;
phi_b(a,2),-0.0122;
phi_g(a,1), 0.5172;
phi_g(a,2), 0.5172;
phi_y(a,1), 0.2025;
phi_y(a,2), 0.202**6**;

Is this understandable?

**Comment by jmaih** [comment]
Please reopen this issue if it still a problem
