### ISSUE TITLE
Different posterior mode while re-estimating same model

### ISSUE THREAD

**Issue by narmindavoudi** [jmaih/RISE_toolbox#153]
Hi dear Mr. Maih
I really appreciate giving your time to solve our problems.
I run the estimation code with "bee_gate optimizer, model estimates posterior and  impulse- response are plotted, but if I re-estimate the  model with any changes, exactly the same model,  the estimated posterior and plot of impulse- responses are different and change surprisingly. 
Would you please help me know why it happens, and how I can have a fixed estimation and plots to rely on it?
sincerely
Narmin

**Comment by jmaih** [comment]
Hi Narmin,

Bee_gate is a stochastic optimizer and it may land on different peaks of
the objective function if it is not run long enough. This would explain why
running it multiple times gives different results.  This is probably a sign
that your objective function has multiple modes.

Another possibility is that some parameters are not well identified. And so
you may well identify some parameters that matter for the likelihood and
not identify others that matter for impulse responses.

I talked about running bee_gate. There are two other possibilities. One is
that after running bee_gate you can run fmincon to finish up the job in
case bee_gate was not run long enough.

The third possibility is that you use a deterministic optimizer such as
fmincon or something else. The advantage is that you will always get the
same peak but that peak is going to be close to where you started. You will
not be able to explore the objective function in a way that bee_gate would.

Cheers,

J

**Comment by narmindavoudi** [comment]
Thank you so much for your answer, but what is the reason of being multiple mode of objective function, and what can I do about that? 
Sorry for bothering you again

**Comment by jmaih** [comment]
There is no fundamental reason. If there was only one peak, optimization would be easy.

**Comment by narmindavoudi** [comment]
Dear Junior
Some other questions:
1.running bee_gate finished after 1000 iteration. Is it long enough for decision( which you mentioned it)?
2.you suggested that after running bee_gate,  fmincon should be run, would you please help about writing its code?

**Comment by jmaih** [comment]
You can change the default settings bee_gate. They follow the basic
settings of matlab. Increase the maximum number of iterations by changing
MaxIter

m=estimate(m,'optimizer','bee_gate')

m=estimate(m,'optimizer','fmincon', 'estim_start_from_mode',true)
