### ISSUE TITLE
GIRF draws

### ISSUE THREAD

**Issue by edugca** [jmaih/RISE_toolbox#154]
Hi, Junior.

I am working with that model with occasionally binding constraints that I told you about, and I have some doubts about the RISE's irf function. I tried to get the syntax of the dsge/irf function, but it is an "internal function".

1) Is there a command that returns the confidence interval of the girfs generated by the irf function, or, at least, that returns all the simulations used to calculate the girf?

2) I believe that the parameter "irf_regime_specific" becomes useless once we set "irf_type" to "girf". Is that right?

3) What is exactly the difference between the parameters "simul_honor_constraints" and "simul_honor_constraints_through_switch", most specifically in the context of occasionally-binding-constraint models?

4) The parameter "irf_girf_regime_uncertainty" assures all girf simulations will have the same regime sequence of the first simulation drawn. Is there any way of guaranteeing that in that first simulation the model remains at all periods in a specific regime, say regime 1? By doing that, I believe I would get the girf conditional to the model ex-post never switching, even though agents behaved all the time as it could happen. Does it make sense to you?

Best and thanks for all the help,
Eduardo

**Comment by jmaih** [comment]
I trust by now you have answers to all these questions.
