### ISSUE TITLE
Error in howto (line 121)

### ISSUE THREAD

**Issue by addsam004** [jmaih/RISE_toolbox#156]
Dear Junior 
Pleasem how do I resolve this.
Error in howto (line 121)
        [obj{imod},postSims{imod}]=posterior_simulator(estim_models{imod},'mcmc_number_of_simulations',...

**Comment by jmaih** [comment]
Hi I can't see what the problem is from your description.

J

**Comment by addsam004** [comment]
I  run the Tao Zha folder tutorial 3 and this bug reported.

**Comment by jmaih** [comment]
Please reopen the issue if you are still having a problem with this
