### ISSUE TITLE
Problem with Interfacing  Dynare's csminwel1 in RISE?

### ISSUE THREAD

**Issue by wangshaobobetter** [jmaih/RISE_toolbox#157]
Hi Junior, I modified the program code according to what you said, and the program run successfully, but the result is different from Dynare. Is there anything you should pay attention to during the initialization? This "epsilon" value, in particular, affected the results very much.
The process was used as follows
Dynare' result
parameters prior mean post. mean 90% HPD interval prior pstdev

beta 0.500 0.0014 0.0011 0.0017 beta 0.2000
delta 0.500 0.5224 0.1983 0.8378 beta 0.2000

Rise' result
beta BETA 0.5 0.00140901272969809 0+1598.62057453798i
delta BETA 0.5 0.437014490153793 0+5.15433756949308i

**Comment by jmaih** [comment]
Hi,

I do not know the details of the csminwel algorithm. I am not even sure
that if you run it twice in, say, dynare you will get back the same
results.

Now besides csminwel, it could also be the case that the things are set
differently in both dynare in RISE.

Cheers,

J.
