### ISSUE TITLE
Problem with Interfacing  Dynare's csminwel1 in RISE？

### ISSUE THREAD

**Issue by wangshaobobetter** [jmaih/RISE_toolbox#158]
On Sat, Jan 9, 2021 at 11:57 AM wangshaobobetter <notifications@github.com>
wrote:

> Hi Junior, I modified the program code according to what you said, and the
> program run successfully, but the result is different from Dynare. Is there
> anything you should pay attention to during the initialization? This
> "epsilon" value, in particular, affected the results very much.
> The process was used as follows
> Dynare' result
> parameters prior mean post. mean 90% HPD interval prior pstdev
>
> beta 0.500 0.0014 0.0011 0.0017 beta 0.2000
> delta 0.500 0.5224 0.1983 0.8378 beta 0.2000
>
> Rise' result
> beta BETA 0.5 0.00140901272969809 0+1598.62057453798i
> delta BETA 0.5 0.437014490153793 0+5.15433756949308i

I am  sure that if I run it twice in, I will get back the same results.
This is part of my revision of “estimation_engine.m” and " penalty_objective_function.m"
Looking forward to your reply, thanks in advance.

          
%%%%%%%%%%%%%%%%  estimation_engine.m     %%%%%%%%%%%%%%%    

            bounds=[lb,ub];
            hess_info.hto1=options.TolX;
            hess_info.hto1=1.e-4;
            n_params=size(x0,1);
            hess_info.h1=0.001*ones(n_params,1);
            Verbose=1;
            Save_files=1;
            nx=numel(x0);
            H0=1e-4*eye(nx);
            crit=1e-7;
            nit=options.MaxIter;
            grad=[];
            method=2;%2,3,5,15
            epsilon=1e-6;

           [fi,xh,gh,H,itct,fcount,retcodeh] = optimizer(fh,x0,H0,grad,crit,nit,method,epsilon,Verbose,
                                                                                 Save_files,vargs{:});
                                                                                           
            xfinal=xh;
            ffinal=fi;
            exitflag=1;
%%%%%%%%%%%%%     penalty_objective_function.m      %%%%%%%%%%
function [fval, exit_flag, arg1, arg2] = penalty_objective_function(x, fcn, base_penalty, varargin)
[fval, exit_flag, arg1] = fcn(x, varargin{:});
arg2=0;
info=1;
% if info(1)
%     fval = base_penalty + info(4);
%     fval = base_penalty ;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by wangshaobobetter** [comment]
When interfacing Dynare's csminwel, I modified the program code as you said in issue #155 , now it can run successfully, but I found the results (like posterior mode、posterior stderr、MDD) are quite different between Dynare and RISE. The results are robust, it will get back the same results every time I run. Comparing these two model files, the only difference seems to be the definition of exogenous shocks, Dynare need to define the standard error of shocks, but no need in RISE. 
Then I turn to optimizer fmincon for examination, since both Dynare (mode_compute=1) and RISE can implement fmincon, and I found the results are also quite different. I know fmincon is a kind of Matlab function, but why the results are so different? Didn't Dynare and RISE call the same Matlab function of fmincon?
I am confused about what's the real reason that caused such a big difference, the setting of exogenous shocks, the user-defined optimization function or the language environment? How to ensure the same results?
Here I posted the benchmark model files in an attachment. Looking forward to your reply, thanks in advance.
@jmaih 
[1fmincon.zip](https://github.com/jmaih/RISE_toolbox/files/5807167/1fmincon.zip)

**Comment by jmaih** [comment]
Hi,

Dynare stops at the prior mode

RISE does several iterations but the first iteration gives a log-posterior
kernel value that is identical to that of dynare.

In your example then, RISE goes further than Dynare. The optimum therefore
cannot be the same.

Also, when you call estimate in RISE, you should not put any restriction on
the presample information because there is none in dynare. You
should simply run estimation as

ms=estimate(m,'data',db)

Cheers,

J.

**Comment by wangshaobobetter** [comment]
Hi Junior,

I simplified the estimate options in “howto_rs.m" and  ran. Both results are separately saved in "result_mod"  and "result_rs" , but they are still quite different, such as  iteration times、posterior mode、posterior stderr and log-MDD.

Before interfacing other optimizers to RISE, first I need to eliminate the confusion caused by model matching problem. Thus I hope to find the explicit issues causing the discrepancy between Dynare and RISE when using the same optimizer of fmincon.

I checked these two files for multiple times, but I still haven't find the reasons, and can't ensure the consistency. Could you please have a look at my code when you are free, it is just a small scale model. My code file is posted in the attachment.

Thank you very much!

Best,

Wang.

@jmaih 
[Hansen_model.zip](https://github.com/jmaih/RISE_toolbox/files/5823846/Hansen_model.zip)

**Comment by wangshaobobetter** [comment]
Hi Junior,
Following your advice, I simplified the estimation option in RISE file as:

sw_old=estimate(sw,'data',data,'optimizer','fmincon')

While the estimation option in Dynare file is:

estimation(datafile=obsY,mode_compute=1,plot_priors=0,mh_replic=4000,mh_drop=0.5,sub_draws=2000,nograph,nodisplay)

I don't know why the two results are still different. Could you help to point out the problems?  Really need your help, thanks in advance.

Best,
Wang
@jmaih

**Comment by jmaih** [comment]
Hi Wang,

I don't know how to help you with this. I originally posted the results of
my investigations.

Would it help to have discussion on Skype so that you can explain to me
exactly what you think I should do?

Cheers,

J.

**Comment by wangshaobobetter** [comment]
Sorry for my confusing statement, and thank you for your attention. I sent you a message in Skype. My account name is wang   . 

Really appreciate for your help. Thanks again.
@jmaih

**Comment by wangshaobobetter** [comment]
Hi Junior, 
    I just confused about getting different results when using the same optimizer of fmincon in both RISE and Dynare.Have your ever checkedabout that? If so, could you give me an example, so I can find out the specific problem of my model settings.

Best, Wang
@jmaih

**Comment by jmaih** [comment]
Hi Wang,

Please feel free to reopen the issue if you are still having problems with this.
