### ISSUE TITLE
How to Get the sampler results

### ISSUE THREAD

**Issue by LeonardRW** [jmaih/RISE_toolbox#16]
Hi Junior,

How can I get the results after use a sampler?
For example after I run:
Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG);
for example how can I get the bayesian confidence intervals or other statistics?

Thanks in advance,
Leonard.

**Comment by jmaih** [comment]
Hi Leo,

You have to be very specific on what exactly you want. RISE tries to avoid doing standard things as much as possible. 

If you want, say 90%, credible (not confidence!) intervals for the parameters, you can compute them using the output of the simulations as follows

```
cr=90/100;
lq=(1-cr)/2; 
rq=cr+lq;
prctile([Results.pop.x],100*[lq,rq],2)
```

Cheers,

Junior

**Comment by LeonardRW** [comment]
Thank you very much for your response Junior!

And for example what instruction should I use to compute the 
Mean, mode and st. deviation for the posteriors? I am trying to compute it but I get an error,  maybe it's easier than I'm doing.

Thanks again

**Comment by jmaih** [comment]
Hi Leo,

Let's do one thing at a time:

1. Collect the simulations in a matrix
```
x=[Results.pop.x];
```

2. Compute the mean
```
mu=mean(x,2);
```
3. Compute the standard deviation
```
sig=std(x,1,2);
```

Cheers,
Junior

**Comment by LeonardRW** [comment]
Thank you very much for your specific steps Junior!

best,

Leo
