### ISSUE TITLE
Simulate only selected variables

### ISSUE THREAD

**Issue by edugca** [jmaih/RISE_toolbox#160]
Hi Junior,

Is it possible to simulate only selected variables using the RISE's command simulate?

I'm thinking of something like in Dynare     stoch_simul x;   where x is the name of the variable. The model has endogenous regime-switching, though.

Best,
Eduardo

**Comment by jmaih** [comment]
Hi Eduardo,

There is a difference between simulating a model and displaying the results
of the simulation for a subset of variables.

After simulation, you can always select the variables to display. But that
doesn't mean that only those variables were simulated.

In RISE too you can select the variables of interest after simulation.

Cheers,

J.

**Comment by edugca** [comment]
Thanks, Junior!
