### ISSUE TITLE
Stability of Endogenous Regime Switching

### ISSUE THREAD

**Issue by edugca** [jmaih/RISE_toolbox#161]
Hi Junior,

I was wondering whether the function "is_stable_system" that checks the stability by the Mean Squared Stability (MSS) concept has any use with endogenous transition probabilities. I know that in the working paper "Efficient Perturbation Methods for Solving Regime-Switching DSGE Models" you mention that it becomes useless in that case, but, when I sweep the policy parameters of my model, I note that instability under that criterion shows up in the range that I would normally expect it to be.

Can I interpret this result as the MSS of the model in case the transition probabilities never left their steady-state values, that is, whether the model was a MS-DSGE instead of a RS-DSGE?

Best,
Eduardo

**Comment by jmaih** [comment]
Just set solve_check_stability to false. Perhaps I should turn of the
checking of MSS under endogenously switching probabilities.

But then again, perhaps I should not. Although the MSS is useless as a
criterion under endogenous switching, heuristically I have observed that if
a model has a better chance of being stable (non exploding simulations) if
MSS is satisfied.

The intuition is straightforward in the sense that for one thing the model
is solved around the steady states, points where the time varying
probabilities become constant. Now if the simulations do not move far away
from the approximation points it's not difficult to imagine that local
stability could be satisfied.

J.

**Comment by edugca** [comment]
Thanks, Junior. That's what I had in mind.
