### ISSUE TITLE
Identification in IRF

### ISSUE THREAD

**Issue by timqzhang** [jmaih/RISE_toolbox#162]
Dear Junior,

I notice a issue when running the tutorials in Bjornland case (exchange rate). If I run the IRF code (tut06 entirely) twice or more times with nothing changed, I will get some different results (sometimes different a lot). I use the same identification schemes. Is it due to some unstableness in the identification or IRF engine? Thank you.

Best,
Tim

**Comment by jmaih** [comment]
There are lots of different impulse responses that satisfy sign
restrictions.

In general people average across a huge number of simulations to get
results that are approximately stable.

Cheers,

J.

**Comment by timqzhang** [comment]
Thank you for response. So I assume that for sign and long-run restrictions, currently RISE doesn't do the stableness part you mentioned to the identification and IRF?

**Comment by jmaih** [comment]
The answer is the one I gave you earlier. It is your responsibility to set
the number of simulations
