### ISSUE TITLE
rise_startup()

### ISSUE THREAD

**Issue by Guimin95** [jmaih/RISE_toolbox#164]
Hi, Dr.Maih
Thanks for your amazing work for RISE toolbox.
I read your 2018 paper, Oil and Macroeconomic (In)Stability. I tried to replicate the model but i faced the question at the beginning.
I have added the toolbox path to Matlab. and then I run the rise_startup(). But I get below information: 
'abstvar' is not a valid base class.

Error in set

Error in rise_startup

It works before, but I do not understand why does not work again. I even reinstalled matlab.

**Comment by jmaih** [comment]
Hi,

Most likely you have not fully downloaded or installed RISE.

Cheers,

J.

**Comment by TimMunday** [comment]
Hi - I'm having this issue too. Seems to be the same as closed issue #139

**Comment by jmaih** [comment]
Let me know if this is still an issue. It may be related to your operating system in the sense that you might be using an operating system that I have not thought about or used before. Should this be the case, the problem would be easy to solve.
