### ISSUE TITLE
Declaration of endogenous probabilities in model file

### ISSUE THREAD

**Issue by Piergiorgio2021** [jmaih/RISE_toolbox#166]
Hi all 

I have troubles when defining endogenous transition probabilities in the attached model file (it is an .rs file saved as .txt). Matlab returns this error message:

Error using parser.capture_equations
Error: Incorrect use of '=' operator. To assign a value to a variable, use '='. To compare values for equality, use '=='. between
line 20 and line 20 in "GK2011_2_test"

The syntax looks OK to me. I also tried to insert semicolumns at the end of the endogenous, exogenous or parameter blocks, but that makes no difference. Any ideas on what the problem might be?

Thanks very much,
Pg

[GK2011_2_test.txt](https://github.com/jmaih/RISE_toolbox/files/7580462/GK2011_2_test.txt)

**Comment by jmaih** [comment]
Do not declare time-varying probabilities as endogenous variables.

**Comment by Piergiorgio2021** [comment]
Right! Thanks
