### ISSUE TITLE
Question about solve and steady_state_model

### ISSUE THREAD

**Issue by maperrupato** [jmaih/RISE_toolbox#168]
Hi Junior,

I'm using the RISE toolbox for the first time and having a problem with an error when I run the solve function:
_"Error using lsqncommon (line 15): Objective function is returning undefined values at initial point. lsqnonlin cannot continue."_

I can imagine that could be something related to the steady_state_model block, but I'm not so sure. As you can see in the rs file, I've declared the steady state values for all variables. The code runned perfectly in Dynare, so I don't know if I've missed some specification when calling solve() or is another mistake

On Matlab:
_%% Solve model
m1=rise('ModelOpenBi_subsidy')
m1=solve(m1)_

Thanks in advance!
[ModelOpenBi_subsidy.zip](https://github.com/jmaih/RISE_toolbox/files/8092445/ModelOpenBi_subsidy.zip)
.

**Comment by jmaih** [comment]
Hi,
If you are using RISE for the first time, I would advise working your way through the existing examples.

In your particular example, the equations you provide for solving the steady state are not the solution of the steady state.

After RISE-ing your model `m=rise('ModelOpenBi_subsidy')`, you should first check that all your parameters, except perhaps those that are determined in the steady state, are set

`isnan(m)` will list the parameters that have not been assigned a value. Those parameters seem to affect the equations of the model and therefore you cannot afford to have them set to `nan`.

Cheers,
J.

**Comment by maperrupato** [comment]
Thanks a lot for the advice!

Cheers,
Marina
