### ISSUE TITLE
dot indexing not supported - smets wouters

### ISSUE THREAD

**Issue by TimMunday** [jmaih/RISE_toolbox#169]
Hello
I am trying to estimate the Smets Wouters model in examples/MarkovSwitching/SmetsWouters

When running this model I receive an error related to the estimate function (see below).

I can estimate other models (I've estimated the 3 equation model for example in the Tao Zha examples). And I can also solve the other Smets Wouters model in examples/VariousModels/SmetsWouters where estimation is not required. So not sure what makes this file different.

The error relates to code which is trying to access a structure by using dot indexing when the object isn't actually a structure. Unfortunately the error messages won't trace back to tell me which object is wrongly being dot indexed (perhaps because it is related to the hidden matlab P-code?) Any help on how to solve this would be much appreciated. Or indeed if anyone is able to run this model without this error that would be useful to know.

Thanks a lot in advance

Error message:
----------------------------------------------------------------
Dot indexing is not supported for variables of this type.

Error in generic/estimate

Error in dsge/estimate (line 217)
%      observations, such that the deflated data is given by y(t) - z(t)*b.

Error in howto (line 29)
sw =estimate(sw); % <--- sw=sw.estimate;

**Comment by jmaih** [comment]
Dear Tim,
I was unable to replicate the error you mentioned. If you were able to
estimate other models, the procedure is the same.
Should the error persist, please, do send me the files you are using so
that I can inspect them.

Cheers,
J.

**Comment by TimMunday** [comment]
Hi Junior, thanks for the reply. I'll try to run some of the other files and see whether there are any other that reproduce the same error which might give a hint to why it's happening.
As for the files I am using, its the files from the github that I forked a couple of weeks ago. The particular file is in examples/MarkovSwitching/SmetsWouters

**Comment by jmaih** [comment]
Yes, I was able to run it without errors.

**Comment by jmaih** [comment]
Are you still having problems on this? please let me know.
