### ISSUE TITLE
Questions about simulate outputs

### ISSUE THREAD

**Issue by maperrupato** [jmaih/RISE_toolbox#170]
Hi Junior,
Thanks for your help so far.

I am running a simulation of an endogenous regime switching model with occasionally binding constraint. My model has 4 regimes and I have a few questions regarding the outputs generated by the simulate function:

1) I was wondering if the data `mySimu.regime_1_4.data` is the transition probability from regime 1 to 4. But
I noticed that in the simulation I ran all the four values are the same (all equal to 1):

`mySimu.regime_1_4.data(1) = mySimu.regime_2_4.data(1) = mySimu.regime_3_2.data(1) = mySimu.regime_4_2.data(1) = 1`
So, I'm a little confused of what that result is telling me.

2) Just to confirm, the variables `mySimu.regime.data` shows in which regime my model is operating, and 
`mySimu.MarkovChainName_1_2.data` shows in which state of that Markov Chain the model is?

3) Also, I would like to know if could you recommend me some example where one simulation was used to generate a data that can be used as initial point in another simulation.
 My goal is to simulate the model, and then evaluate the response to some shocks in a situation where the model is close to a regime shifting instead of starting from a steady state.

Best,
Marina

**Comment by jmaih** [comment]
Would it be possible to send me that example of yours?
