### ISSUE TITLE
Estimation settings

### ISSUE THREAD

**Issue by joseortega31** [jmaih/RISE_toolbox#172]
Hi Mr. Maih,

I wanted to know ask you how can I customize estimation settings (say use Kalman filter or a modified version of Metropolis Hastings) and which are the available algorithms.

Thank you in advance,
Jose

**Comment by jmaih** [comment]
If you want to see all the default options related to estimation, run

estimate(dsge.empty)

if you want to see those related to solving

solve(dsge.empty)

This holds true for many functions including irf, forecast, simulate, etc.
and in particular, the option you are looking for is a filtering-related
option. Therefore, you want to run

filter(dsge.empty)

The option is called "kf_user_algo". You need to set that option to the
name of your filtering algorithm. Your filtering algorithm should be on the
Matlab search path and should accept the inputs that RISE requires and
return the outputs that RISE expects. For more information see help
dsge/filter.

To see the list of all options, simply run

m.options

where "m" is the name you gave to the model object.

**Comment by joseortega31** [comment]
Thank you very much for your answer!
