### ISSUE TITLE
Future regimes in model

### ISSUE THREAD

**Issue by joseortega31** [jmaih/RISE_toolbox#173]
Dear Mr. Maih,

I am currently working with a model which has just one regime-dependent parameter - say $\lambda(s_t)$ -, but this parameter appears both depending on $s_t$ and on $\mathbb{E} s_{t+1}$ in the equations of the model. 

I wanted to ask you if there is a recommended way to deal with future regimes appearing in the model. My current approach is to define a compund regime:

$$
\begin{equation}
s_t^* = 
\begin{cases}
1, \quad \text{if } \mathbb{E} s_{t+1} = 1, s_t=1 \\
2, \quad \text{if } \mathbb{E} s_{t+1} = 2, s_t=1 \\
3, \quad \text{if } \mathbb{E} s_{t+1} = 1, s_t=2 \\
4, \quad \text{if } \mathbb{E} s_{t+1} = 2, s_t=2
\end{cases}
\end{equation}
$$

and transition matrix given by:

$$
\begin{equation}
\begin{bmatrix}
p_{11} & p_{12} & 0 & 0 \\
0 & 0 & p_{21} & p_{22} \\
p_{11} & p_{12} & 0 & 0 \\
0 & 0 & p_{21} & p_{22}
\end{bmatrix}
\end{equation}
$$

where $p_{ij}$ are the original transition probabilities of $s_t$. Is this the right way or would you recommend using a different approach?

Thank yoy very much in advance,
Jose

**Comment by jmaih** [comment]
Hi Jose,

This is a big fat nothing burger :)

Just index the parameters with time and RISE will take care of the rest.

RISE solves the generic problem
Ef(x{t+1},x{t},x{t-1},e{t},theta{t},theta{t+1})=0

where x{t} is the vector of endogenous variables, e{t} the vector of
shocks, theta{t} the vector of parameters.

Cheers,

J.

**Comment by joseortega31** [comment]
Hi Mr. Maih,

Thank you very much for your answer!

I have just tried indexing the parameter and I got the following error:

`Assigning to 0 elements using a simple assignment statement is not supported. Consider using comma-separated list assignment.

Error in parser.capture_equations

Error in parser.capture_equations

Error in parser.capture_equations

Error in parser.parse_model

Error in parser.parse

Error in dsge

Error in rise (line 64)
%

Error in run (line 8)`

Do you have any idea of why is this error popping up?

Regards,
Jose

**Comment by jmaih** [comment]
I will need to update that version of RISE then.

There is a simple workaround.

Define an endogenous variable, say z, and an equation

z=lambda;

where lambda is the switching parameter occurring in the future.

then replace lambda{+1} with z{+1}

Cheers,

J.

**Comment by joseortega31** [comment]
This worked, thank you once again for all the help!

Jose
