### ISSUE TITLE
Filtering vs smoothed

### ISSUE THREAD

**Issue by jbejarro78** [jmaih/RISE_toolbox#175]
Dear Junior, as I understood:

1- filtered_variables refer to one-step ahead forecasts: a_{t|t-1}
2- updated_variables refer to the updates a_{t|t}
3- smoothed_variables refer to the final estimates conditional on all
available information a_t{t|n}

However, I did two estimations, with a two-regime model, for NAIRU. 

The first estimation was for the sample 1986Q1 to 2021Q2.
The second estimation was for the sample 1986Q1 to 2022Q2.

The only significant difference between estimated parameters was the NAIRU's mean under the second regime (or COVID-19 ( regime).

If I use Expected_smoothed.NAIRU, I expect that the estimated NAIRU (until 2021Q4) under the first sample and under the second sample would be different as long as smoothed uses past and future information.

However, when I use Expected_filtered.NAIRU,  I expect that the estimated NAIRU (until 2021Q4) under the first sample and under the second sample would be equal as long as filtered uses only past information.

Am I right? or Did I miss something?

Thank you

**Comment by jmaih** [comment]
Hi,

If the parameters are identical, then the filtered until 2021Q4 should be
identical.

The results can be very different if the parameters are different, even
slightly different.

Cheers,

J.

**Comment by jbejarro78** [comment]
Thank you very much
