### ISSUE TITLE
Estimation of MS-DSGE model

### ISSUE THREAD

**Issue by IrisHu7** [jmaih/RISE_toolbox#177]
Dear Junior,

I hope you are doing well.

I am currently using RISE to estimate a MS-DSGE model with a ZLB regime based on the code of Smets and Wouters (2003). However, I kept having the error below.
![error](https://user-images.githubusercontent.com/125613128/219500944-68b51843-4998-4b3e-ad6d-a650bbd74445.jpg)

Then, I changed the Taylor rule equation and regime settings, as you mentioned in other issues. Like this:
![Taylor_rule](https://user-images.githubusercontent.com/125613128/219501711-fb0db084-1eda-426f-9105-39daea6f5eb8.jpg)
![two-regime](https://user-images.githubusercontent.com/125613128/219501805-95940ad3-f443-4e28-bc20-29340ca926af.jpg)
My data contains the sample after 2008. So the data covers the ZLB period, and the interest rate can be zero.
However, I still have the error mentioned above. 

Could you please give me some suggestions? Do you know how I can solve this error?

I really appreciate any help you can provide. Thanks a lot in advance.

**Comment by jmaih** [comment]
Hi,

RISE informs you about the reason you are not able to estimate the model :
"Definitions are nan or imaginary"

Are all the parameters of the model set? Have you tried just solving the
model before estimating its parameters?

Cheers,
J.
--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by IrisHu7** [comment]
Thank you so much for your time and patience, Junior! 
I have checked the parameters, and now the model can be solved and estimated. I already have my estimation results.

Thank you again for everything!

**Comment by jmaih** [comment]
Thank you for your letting me know.Cheers,J. Sendt fra min iPhone19. feb. 2023 kl. 11:46 skrev IrisHu7 ***@***.***>:﻿
Thank you so much for your time and patience, Junior!
I have checked the parameters, and now the model can be solved and estimated. I already have my estimation results.
Thank you again for everything!
