### ISSUE TITLE
Posterior densities in the same plot

### ISSUE THREAD

**Issue by LeonardRW** [jmaih/RISE_toolbox#18]
Hi Junior,
I couldn't find an option in the plot_priors_and_posteriors(.) or plot_posterios (.) functions to do a unique plot for parameters that are defined in different regimes. For example rho_coef_1, rho_coef_2.
Am I missing it or it is better to do it manually?
Many thanks in advance,

Leonard.

**Comment by jmaih** [comment]
Hi Leo,

Your question is a bit unclear. The functions plot_priors, plot_posteriors and plot_priors_and_posteriors all allow you to select the parameters you would like to plot. If you do not select any, then all of them are plotted. They also have a documentation, try 
```
help rise.plot_priors
```
```
help rise.plot_posteriors
```
```
help rise.plot_priors_and_posteriors
```
In case you don't like the way the plots are done, the functions also give you the possibility of plotting things yourself. Just call any of those functions with one output. For instance
```
 data=plot_posteriors(m)
```
Note that with one output variable, the functions do not do plot. They only plot if there are no output arguments or if the number of output arguments is two.
Now if you want to plot or get the data for a subset of the parameters, say the ones you listed, you can do the following
```
plot_priors(m,{'rho_coef_1','rho_coef_2'})

plot_posteriors(m,simulation_folder,{'rho_coef_1','rho_coef_2'})

plot_priors_and_posteriors(m,simulation_folder,{'rho_coef_1','rho_coef_2'})
```
in the statements above, "simulation_folders" is either 

- the location of the simulations in case they are saved to disk. 

- Or the simulations themselves, i.e. the "pop" field of the results produced by for instance mh_sampler.

Cheers,

Junior

**Comment by LeonardRW** [comment]
Thanks for your response Junior,

For sure, my question was not clear enough. The options that you described above allow to plot for example rho:rho_coef_1 and rho_coef_2 in the same plot, but in two different subplots. What I'm trying to say is how you can plot the posterior density for rho_coef_1 and rho_coef_2 in just one subplot. So,  for example, in blue is the rho density for regime 1 and other color, say red, is the density for the regime 2, but both appear in the same subplot with the same axis. 

Regards, 

Leonard

**Comment by jmaih** [comment]
Leo,

For that you will have to do yourself, I am afraid. RISE does not do this on its own but gives you all the data you need to do it. It is quite simple.

1) First you collect the data you want to plot
```
data=plot_posteriors(m)
````
or
````
data=plot_posteriors(m,{'rho_coef_1','rho_coef_2'})
````

2) Then you plot what you have to plot
````
x1=data.rho_coef_1.x_kdens;

x2=data.rho_coef_2.x_kdens;

f1=data.rho_coef_1.f_kdens;

f2=data.rho_coef_2.f_kdens;

plot(x1,f1,x2,f2)

legend({'rho_coef_1','rho_coef_2'})
````

Cheers,

Junior

**Comment by LeonardRW** [comment]
Thank you very much Junior,
Best,
Leonard.
