### ISSUE TITLE
Estimate and filter functions

### ISSUE THREAD

**Issue by javiertasso** [jmaih/RISE_toolbox#181]
Dear Dr. Maih, 

I'm following TaoZha econometrica example and I have two questions about the estimate and filter functions. To give more context, I'm running line 55 of _examples\VariousModels\TaoZha\LWZ_Econometrica2013\master_switch.m_.

```
[ms,filtration]=estimate(m,'data',data,...
        'estim_priors',priors,...
        'kf_presample',3,...
        'kf_init_variance',10,...
        'estim_nonlinear_restrictions',myNormalization);
```

The first one is a more general question. What algorithm is this function using to produce the filtration? 

Now I try to do the filtration directly using the filter function with the same options. When I do this, there are small differences in the smoothed probabilities (see picture). Are these differences expected? 

```
filt = filter(m, 'data', data,...
         'estim_priors', priors,...
         'kf_presample', 3,...
         'kf_init_variance', 10,...
         'estim_nonlinear_restrictions', myNormalization);
``` 
![fig_smoothed_probabilities](https://github.com/jmaih/RISE_toolbox/assets/92757360/2ac0565f-d612-4e17-88d4-cefd07014699)

I appreciate any help or guidance you can give me. 

Thank you, 
Javier

**Comment by jmaih** [comment]
Hi Javier,

If the model and the parameters are the same, then there should not be any
difference.

The estimated model is ms, which contains the estimated parameters. That is
the model you should run filtration with. If you use that model, you don't
need to add further options. All the information is already contained in ms.

The algorithm used to produce filtration is a variant of the Kim and Nelson
(1999) filter. The algorithm in RISE is more efficient.

J.

**Comment by javiertasso** [comment]
Thank you so much for your answer. I used the filter function with the estimated model as an input and I got exactly the same output. 

Thanks again, 
Javier
