### ISSUE TITLE
Option 'data_demean' in estimate(...) 

### ISSUE THREAD

**Issue by UsernameUser100** [jmaih/RISE_toolbox#183]
Hello.

I’m in the middle of writing a paper using RSIE toolbox and always check RISE Toolbox Documentation Release 20230709 for reference.  I have a question about the code of “4.2.6 Maximizing the posterior” on page 115 of the documentation.

What differences does it make to add 'data_demean' option in estimate(...)? 

Do I need to add ‘data_demean' true in estimate(…,'data_demean',true,,‘data’ db, …) after I demean data (such as interest rate and inflation), which is db in estimate(...).

For Example (based on 4.2.5 Collecting and transforming the data on page 114)

d=fetch_fred({'CPALTT01USQ661S','BOGZ1FL072052006Q'});
db=struct();
db.P=log(d(1).series/d(1).series{-1}); 
db.R=d(2).series/100;

db.P=db.P-mean(db.P)    %%% Subtracting the sample mean from data
db.R=d(2).series/100-mean(db.P)   %%%Subtracting the sample mean from data
(In here, I assume that inflation and interest rate are 0 in steady state for simplicity, though I think interest rate is above 0 in the model of page 113.)

then execute the code of ‘4.2.6 Maximizing the posterior’.
Is that correct? 

Thank you.

**Comment by jmaih** [comment]
Hi,

The way you treat the data has to be consistent with the implications of
your model.

**Comment by UsernameUser100** [comment]
Thank you for the prompt response.
