### ISSUE TITLE
State_Space_Wrapper Function

### ISSUE THREAD

**Issue by khoilx** [jmaih/RISE_toolbox#184]
Dear Prof. Maih,
I am building my DSGE model based on your RISE Toolbox, and facing an error, I guess that (1) I am making a mistake when deriving several parts from the internal function: [T,R,Z,H,Q,sstate,init,growth] = dsge.state_space_wrapper(syst); or (2) It cannot find the solution from solve(). I don't know how I could find the 'syst' part and the forms of these outputs. Can you please let me know the forms of these outputs? And In what case will I have no solution (is it from the parameters' initialization)?.

Thank you so much for your help!
Khoi

**Comment by jmaih** [comment]
Hi Khoi,

What you are describing is not a natural use of the toolbox and it is not
surprising that you run into problems.

What are you exactly trying to do?

Cheers,
J.

**Comment by khoilx** [comment]
Hi Prof. Maih,
I'm trying to estimate the endogenous RS-DSGE model with 2 latent factors using my own filter. To do that, I extracted several matrices from the 'syst' part. When I tried 'filter' comma, it shows 'retcode = 306', and moreover, when I tried 'solve' comma to solve the rise model obj, I saw 'obj.solutions.H' is empty. So, I am not sure this problem is from no solution of the model or from the mistake of calling matrices from the 'syst'.

**Comment by jmaih** [comment]
Several issues to unpack:
1- what you need, it seems, is to connect your own filtering procedure to
RISE. RISE expects your procedure to accept certain inputs and return
certain outputs. If you make  mistake at that step, the procedure will fail.

2- If you want to understand what the error message means, run
decipher(306) or decipher(retcode)

3- the default filter will do the job of filtering and can be used for
estimating parameters but will not be able to generate the latent factors.
Should you go down this route, the only remaining question will be: do you
know how to extract latent factors and what inputs do you need in that
process.

**Comment by khoilx** [comment]
Thank you so much. I'll check it carefully.

**Comment by khoilx** [comment]
Hi Prof. Maih,
As your suggestion, I've checked the error message, it is 'unlikely parameter vector', I think I need to modify the setting of parameter vector. Thank you so much for your help. Happy New Year!

Best wishes,
Khoi

**Comment by jmaih** [comment]
Hi Khoi,

Unlikely parameter vector can come from different sources. Certainly a bad
parameter vector could be the culprit.

But you can also have that problem, among other things, if the initial
variance is too small and or the initial state is far away from what is
implied by the data. Should this be the case, sometimes a diffuse
initialization with a large variance may help.

Happy new year to you too!

J.
