### ISSUE TITLE
Filtering data using a MS-DSGE model

### ISSUE THREAD

**Issue by GabrielPestana81** [jmaih/RISE_toolbox#185]
Dear Dr. Maih,

I have a very simple model, and two calibrations that lead to two different regimes. In one calibration, I have a passive fiscal policy, which is a standard model. In the other calibration, I have an active fiscal policy. They differ only by two parameters, which are the monetary policy reaction to inflation ($\alpha_\pi$) and the fiscal policy reaction to the debt size ($\alpha_b$). 

Given a set of data, could please point me out how could I use the toolbox to obtain estimates of probability of being in each regime in sample? 

Later, I would also like to estimate the parameters in the model. However I would have to set as priors the relevant areas for the parameters that changes between regimes. That is, in the passive fiscal policy the prior must ensure $\alpha_\pi \geq 1$ and $\alpha_b > 1/\beta  - 1$, and with active fiscal policy $\alpha_\pi < 1$ and $0 < \alpha < 1/\beta  - 1$.

Thanks in advance !

**Comment by jmaih** [comment]
Dear Gabriel,

If you've set up your model properly, all you need to do is filtering.

e.g. f=filter(m)

where m is a parameterized model object containing all the relevant
information for filtration. or alternatively

f=filter(m,varargin)

where you pass the additional options you need.

Once you filter, f will be a structure containing information about the
filtered variables, the updated variables and the smoothed variables. Some
of those variables are going to be the probabilities of being in the
different regimes.

Estimation is just going to be a change in parameters but the same
principles will apply.

In terms of restrictions on the parameters, check out an example  in
\examples\VariousModels\TaoZha\LWZ_Econometrica2013\master_switch

Cheers,

J.

**Comment by GabrielPestana81** [comment]
Thank you so much! 

I'll try to implement it, and read the provided example.

Cheers !

**Comment by Zhanwenqing** [comment]
> Dear Gabriel,
> 
> If you've set up your model properly, all you need to do is filtering.
> 
> e.g. f=filter(m)
> 
> where m is a parameterized model object containing all the relevant
> information for filtration. or alternatively
> 
> f=filter(m,varargin)
> 
> where you pass the additional options you need.
> 
> Once you filter, f will be a structure containing information about the
> filtered variables, the updated variables and the smoothed variables. Some
> of those variables are going to be the probabilities of being in the
> different regimes.
> 
> Estimation is just going to be a change in parameters but the same
> principles will apply.
> 
> In terms of restrictions on the parameters, check out an example  in
> \examples\VariousModels\TaoZha\LWZ_Econometrica2013\master_switch
> 
> Cheers,
> 
> J.
> […](#)


Hi Professor,
    sorry to bothor you. After "f=filter(m,varargin)", do filtered variables refer to one-step ahead forecast? Why they are all zero like this?

0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i
0.00000000000000 + 1.00000000000000i	0.00000000000000 + 1.00000000000000i

   Hope to your reply,thanks!
Zhan

**Comment by jmaih** [comment]
Hi Zhan,

Unfortunately, I cannot tell you what is going on without seeing your
model, parameters, and data.

Best,

J.
