### ISSUE TITLE
Estimating model with the ZLB

### ISSUE THREAD

**Issue by AnasZa** [jmaih/RISE_toolbox#19]
Dear Junior,
I have a simple NK model with the zlb. I followed GavinKeenRichterMorton as in the “examples” file and assumes a Markov chain to control the states: “in” or “out” of the zlb.  Now I’d like to estimate a linear version of this model. But even if I estimate only 2 parameters  - transition probabilities zlb_tp_1_and zlb_tp_2_1  - I always get “Covariance of forecast errors not positive definite” , and at the end I have : 

“Error using rise_generic/find_posterior_mode (line 78)
find_posterior_mode:: No admissible starting value after 500 trials”

I've checked that the model solution is stable. Is it possible to estimate a model like this in RISE? 

Thanks a lot in advance.

**Comment by jmaih** [comment]
Hi Anastasia,

Could you please take a look at thread #13 ? Send me your files if none of the instructions given there works.

Let me know,

Greetings from Arcata,
Junior

**Comment by AnasZa** [comment]
Dear Junior,
Thank you for your quick answer. I did try everything. I simplified the model but it is already so simple. It's only when I add a Markov chain on zlb state that I have problems. I am sending you my files by email. 

Kind regards,

**Comment by AnasZa** [comment]
Dear Junior,
Thank you for your quick answer. I did try everything. I simplified the model but it is already so simple. It's only when I add a Markov chain on zlb state that I have problems. I am sending you my files by email.
Kind regards,
Anastasia

**Comment by jmaih** [comment]
Hi Anastasia,

I did not see your email with the files so I assumed you had solved the problem.

I have just taken a look at the new files you sent me and it turns out that the problem is the stochastic singularity arising from the specification of the ZLB equation for the interest rate.

1.  In the data, the interest rate is never identically zero as suggested by your model. RISE tries as best as it can but will never succeed in finding a parameterization that has a nonzero likelihood.

1. If you do FOR INSTANCE the following changes:

````
- R = zlb_flag*0+(1-zlb_flag)*RTAYLOR + sgm_rm*epsilon_rm;

- RTAYLOR = phi_r*RTAYLOR(-1) + (1-phi_r)*(phi_i*pit + phi_y*y);
````

That is moving the error term from the Taylor rule to the R equation, the stochastic singularity problem goes away but this might not be what you want in the end.

Cheers,

Junior

**Comment by addsam004** [comment]
Dear Junior
I have a similar problem but in different file TaoZha DSGE tutorial 2. I am estimating Lubik and Schorfheide 2003 small open economy model with export sector. Following TaoZha DSGE tutorial 2. It give me the bug below
499 :: Covariance of forecast errors not positive definite
Error using generic/find_posterior_mode (line 78)
find_posterior_mode:: No admissible starting value after 500 trials

Error in generic/estimate (line 287)
[x1,f1,H,x0,f0,viol,funevals,issue,obj]=find_posterior_mode(obj,x0,lb_short,ub_short); %#ok<ASGLU>

Error in dsge/estimate (line 31)
    obj=estimate@generic_switch(obj,varargin{:});

Error in howto (line 91)
    estim_models{imod}=estimate(estim_models{imod},'optimizer','fmincon');

How do I fix this.
Best,
[workexample.zip](https://github.com/jmaih/RISE_toolbox/files/736948/workexample.zip)

Sam

**Comment by AnasZa** [comment]
Hi Junior,
Hope you are doing great. Sorry for reopening the issue, but I think my question is better suited here.

**Comment by AnasZa** [comment]
Hi Junior,
Hope you are doing great. Sorry for reopening the issue, but I think my question is better suited here.
I’m re-estimating a model (basically it is Binning & Maih 2016) on the sample including recent data and I am having problems to recover zlb regime. When using sample 1987q1-2015Q1 I am able to find a zlb starting from 2009 and lasting till the end of the sample. When I extend it till 2016Q4, I am able to recover the zlb regime only if I set sigma_er to 0.001 (instead of 0.0001 as in your paper). If I include data till 2017Q4 and play with sigma_er and transition probabilities, I can’t get estimates with the zlb regime. Do you have an idea what might help in this case?
Thanks a lot in advance.

A

**Comment by jmaih** [comment]
Hi A,

The short answer is that I do not know what would work. The estimates you
get will depend on the data and the sample used, the model, and
(unfortunately perhaps) the power of the optimization procedure. It is very
easy to land on a local peak especially if a thorough search is not
conducted.

One thing you could try is to use the estimates that gave you the results
that you like (on the short sample) as initial values for the estimation on
the longer sample. The intuition is that perhaps those estimates continue
to yield a high density for the posterior when the sample is extended with
few observations. Plus it is certainly more difficult to estimate a model
over a long sample than over a short one. Therefore starting in a region of
low density, optimization should be harder the longer the sample.

I don't know whether this would work but it is probably worth trying. But
then again that would not compensate for a lack of thorough search.

Cheers,

J.
