### ISSUE TITLE
Replicating the ZLB paper

### ISSUE THREAD

**Issue by TANDINGYONG1980** [jmaih/RISE_toolbox#20]
Hi Dr Maih

I'm trying to replicate your joint paper on "Implementing the ZLB".  I've tried to write a .rs file as similar to the model equations as possible, but the error message I've gotten is that the "model has not been solved at least up to the first order" (which I take is a signal that obj.solution is empty). I looked at an earlier thread on a similar issue, #2, but that didn't seem to help.

At this point, the only Markov chain in the model is an exogenous one for shifting time preference factor d_t.  I also haven't included the restrictions in section 5.2. I would be grateful for any help you can provide!

**Comment by jmaih** [comment]
Dear Ding,

The questions have to be as specific as possible. While I can't help you replicate an entire paper, at least I can help debugging your codes. 

The issue you raise is that RISE returns the message "the model has not been solved at least up to the first order". RISE can tell you why this is the case if you set it in debug mode. You do this by calling solve with 2 additional arguments as follows

````
m=solve(m,'debug',true)
````

Cheers,

Junior

**Comment by TANDINGYONG1980** [comment]
Hi Junior,

Thanks for the reply. I'm sorry if the questions don't seem specific but I guess I'm stuck at an early stage of the replication process and am not quite sure how to proceed without the model getting past the "solve" process.

The error message received using the "debug" option is that the "steady state could not solve".  This was already with the "steady_state_imposed" enabled. At present the steady state portion of my .rs files corresponds to eq (26)-(41) of your paper:

    A = 1;

    AR = 1;

    PAI = paiss;

    Y = yss;

    C = Y;

    N = Y;

    RTAYLOR = paiss * exp(g_z) / bet;

    RE = Kbase;

    R = max(RE,RTAYLOR);

    PREF = paiss * exp(g_z) / (bet * R);

    MU = exp(g_z);

    LAMBDA = (C * (1 - chi/MU)) ^ (-sig);

    STODIS = 1 / R;

    W = 1 - 1/epsilon;

    kappa = LAMBDA * W / N ^ eta;

    YHAT = MU;

(PREF in this case corresponds with the variable d from your paper.)  Appreciate you taking the time!

Best,
Ding
