### ISSUE TITLE
Different estimation results using different computers but the same files

### ISSUE THREAD

**Issue by AnasZa** [jmaih/RISE_toolbox#21]
Dear Junior,
I ‘d be grateful if you could give me your opinion about a problem I am having using Rise. Though I am not sure it comes from the toolbox itself.
I have two computers I am working on and I use dropbox where my RISE toolbox is stored together with the files I am working with. 
Say I estimate model M on computer 1. I save the results and I check if I can improve my mode. For this I do:
load M
M_new = estimate(M,'optimizer', 'csminwelwrap', 'kf_init_variance', 5 ,'kf_presample', 16, 'estim_start_from_mode', true).
The second estimation starts exactly from the log_post of the estimated model M. No need even to put 'estim_start_from_mode', true. Everything’s good.  If I do this on computer 2, it does the same thing. It starts from the previous mode. 
But if I estimate model M using computer 2 (the same exactly model with the same priors and initial values as on the computer 1) then the estimation results are completely different. It delivers much better results: higher log_post, higher log_lik and higher data density. But if I do ‘re_estimation’ (M_new = estimate(M,…)) it doesn’t work on none of the computers.  Matlab starts estimation with weird values and never converges. The only hint I have is that log data density of model M estimated on computer 1 is always negative if you check in M.estimation.posterior_maximization, while on computer 2 it is positive.  

Do you have an idea what’s happening?
Thanks a lot in advance.
Kind regards,

**Comment by jmaih** [comment]
Hi Anastasia,

Holding the RISE code constant (as long as you do not try to sample the posterior distribution, all the processes in RISE are deterministic), there are potentially different things to investigate including the version of Matlab, the setting of the computers, whether the two computers process the exact same information, whether dropbox corrupts files, etc. 

Unfortunately it is difficult to say anything concrete without replicating the problem or having a more detailed description of the various steps. At first sight, it would appear as if the computers behave differently, unless you are not repeating exactly the same experiments in both environments.

Yet another source of uncertainty may come from the optimizer itself. I have not used csminwel for many years but I vaguely remember there is an element of randomness to it. Unless you start/restart estimation at the global peak, there is no guarantee that you will always get the same results.

If you would like to get to the bottom of the issue, you may want to test each element (dropbox, matlab, computers, csminwel separately). But this can be very costly.

Let me know what you come up with,

Greetings from San Francisco,

Junior

**Comment by AnasZa** [comment]
Dear Junior,

Thank you very much for your answer. I tried to change the seed and actually the results got closer on both computers. But now I wonder which result I shall chose. I have three modes: 

1) log_lik = 65.6; log_post = 76.3; log_prior=10.7; MDD laplace = 2.4. But if I start to re_estimate from this mode, optimization procedure using csminwel explode. 
2) log_lik = 59; log_post = 41; log_prior=-17; MDD laplace = -20. **And on top of that mode_stdev with complex double.**  Can mode_stdev contain complex numbers? 
3) log_lik = 15.33; log_post = 28.97; log_prior=13.6 ; MDD laplace = -36. But if I start again re-estimate from this mode I converge again to this mode.

What would you advise?

Kind regards,

**Comment by jmaih** [comment]
Hi Anastasia,

1. Which mode to choose: any or none ! All depends what you want to use the mode for. 

- If the objective is to reach global peak, a more thorough search is needed. The only paper that really discusses estimation and show how hard it is in practice is [this one by Liu, Waggoner and Zha (2011, page 17)](http://www.tzha.net/articles/lwz_rsdsge_rev4f.pdf).

- If the objective is to eventually do posterior simulation, say using the Metropolis Hastings algorithm, the theory says that all you need is a starting point and a covariance matrix. Posterior simulation could improve the mode, i.e. find a parameter vector with higher posterior than the one you found.

- If the objective is policy, ... no comment

1. When the standard deviations are complex, the hessian is not positive definite. The optimization most likely stopped before reaching a peak. This is very often the case for instance when you do not have a very good optimizer, when you have a corner solution or when identification is poor. Again, depending on, precisely, what you want to do, there are ways to proceed

- If you want to report the standard deviations, you will have to make the priors more informative or use a more powerful optimizer that lands estimation at a peak, an optimizer capable of traversing thin/narrow ridges.

- If you want to do posterior simulation and need an initial covariance matrix, there are (imperfect) ways to make a covariance matrix at hand positive definite.

Cheers,

Junior

**Comment by AnasZa** [comment]
Thank you very much for your answer!

I'd like to do simply IRF, variance decomposition, shock analysis... 

I understood about complex numbers in the standard deviations. But in the case when the standard deviation is not complex, Is it a problem that I can't re-estimate the model using the mode I've chosen?  Does it mean that the hessian is not positive definite? Is it a problem that the MDD laplace is positive? I just don't see other reason why the optimization does not converge again to this mode.

**Comment by jmaih** [comment]
I am not sure I understand what you mean by "re-estimate the model using the model I've chosen". The re-estimation setup might not be as simple as you think. It is crucial to understand exactly what the optimizer does in that case. 

Again, if I remember correctly, csminwel write some mat files to disk. I guess those files correspond to the state of the estimation, probably in terms of gradient and/or hessian. Re-starting estimation without those elements means that csminwel has to re-initialize estimation as it did when you did simple estimation. The only difference here is that you start at a different point. In other words, the state at the end of estimation is not the same as the state at the beginning of re-estimation.  If there are vagaries stemming from the optimizer, of course they should be taken into account.

Sometimes the laplace MDD still seems to be well defined even in the presence of a not so well defined covariance matrix.

The statement "I just don't see other reason why the optimization does not converge again to this mode" is potentially misleading. It assumes that at the end of the estimation, the parameter vector obtained is a mode, which is not always true. As I have been telling you, estimation can stop before reaching a peak. I say a peak, I am not even talking about the global peak.

Cheers,

Junior
