### ISSUE TITLE
Initial values for solving the steady state

### ISSUE THREAD

**Issue by tskrogh** [jmaih/RISE_toolbox#22]
Hi!

I'm running the example with initial values for solving the steady state in a separate file (RISE_toolbox/examples/NonlinearModels/), but I get the error below when trying to solve the model. Is there a bug, or am I doing something wrong? 

Best, 

Tord

************************** ERROR MESSAGE *****************************

Undefined function or variable "nvar".

Error in locate_variables (line 40)
IDs=nan(nvar,1);

Error in dsge/compute_steady_state>prepare_steady_state_program (line 947)
            locs=locate_variables(updated_param_list,obj.parameters.name);

Error in dsge/compute_steady_state (line 129)
[obj,sscode,blocks,unsolved]=prepare_steady_state_program(obj);

Error in dsge/solve/solve_zeroth_order (line 594)
            [obj,structural_matrices,retcode]=compute_steady_state(obj);

Error in dsge/solve (line 313)
retcode=solve_zeroth_order();

**Comment by jmaih** [comment]
Hi Tord,

The example was broken because the syntax changed a while back. I have now updated the example and checked that it runs as it should.

Cheers,

Junior
