### ISSUE TITLE
Modelling frontier

### ISSUE THREAD

**Issue by tompiechula** [jmaih/RISE_toolbox#28]
Dear Junior,

I try to make frontier of the Markov Switching DSGE model. I have 2 questions:
1)  I struggle to understand the difference between simulate (which is used by the function 'frontier'), 'simulate_nonlinear' and 'stoch_simul'. Can you tell me very briefly what is the difference between them in RISE and which of them is right to use for nonlinear MS DSGE models?

2) 'frontier' function: I can do the frontier for the 1st regime and 2nd regime (I enter the code and add 'simul_regime' to simulate command in 'frontier' funtion). When don't do this, the result is different. Am I right that this is the simulation for both regimes? 

I would be very grateful for your help.
Tom

**Comment by jmaih** [comment]
Hi Tom,

Sorry for the delay

1. All functions that involve some kind of forecasting use "simulate". stoch_simul is just a function that summarizes the main results of the model and nothing else. "frontier" is used in the calculation of policy frontiers.

1. I do not understand your second question. Have you looked at the help for that function? `help dsge/frontier`

Cheers,

Junior
