### ISSUE TITLE
external functions and endogenous probabilities

### ISSUE THREAD

**Issue by mhardinga** [jmaih/RISE_toolbox#29]
Hi Junior,
I'm working with a regime switching DSGE with endogenous probabilities. I would like to make these probabilities dependent on the deviations of a given variable (let's call it x) from its SS; even if x has different SS values in each regime, I guess this shouldn't be a problem since x_hat_ss is zero in both regimes. 
1) the first question concerns the use of external functions in RISE in general. In Dynare you would use the "external_function(name = myfun, nargs =integer)" command and then just use "myfun" in the code.  How does it work in RISE?
2) I would like to write the endogenous probabilities as:
! nk_tp_1_2 = myfun(x_hat,other_args); where myfun is an external matlab function of x_hat that returns a value between zero and one for each possible value of x_hat. Is it possible to specify the probabilities in this way in RISE?
Thank you,
Martin

**Comment by jmaih** [comment]
Hi Martin,

What you say is correct! As long as the variables entering the transition probabilities have a unique steady state RISE will not complain.

There is no problem with external functions either., As long as your function is on the matlab path RISE will see it. You don't need to declare it. There shouldn't be any problem as long as RISE recognizes the basic components of your function. For example the following "extermal" function will work fine.

```
function p=myfun(x,g)
p=1/(1+exp(-g*x));
end
```

Cheers,

Junior

**Comment by mhardinga** [comment]
Hi
Junior,

thank
you very much for the reply. For simple external functions my code runs;
however, I still get an error when my external function calls a particular
matlab function. In particular, I am trying to model the endogenous probability
as the cdf of the Beta distribution applied to the deviations from SS of one
variable. 

The
probability in the code reads: 

! nk_tp_1_2 = prob_l_h(k_e_hat_10,5,1);and
this is the external function: function [prob_l_h] = prob_l_h(val,par1,par2)

prob_l_h = cdf('Beta',val/100,par1,par2);

end
where
k_e_hat_10 is the deviations from SS of one of the variables of my model, 5 and
1 are the parameters of the Beta distribution. I
get the following error when running the code:

 

Now computing symbolic derivatives...
 
Undefined function 'all' for input arguments of type 'splanar'.

Error in betacdf (line 37)
allOK = all(k(:));

Error in cdf (line 97)
        p = betacdf(x,a1,a2,tail{:});

Error in prob_l_h (line 2)
prob_l_h = cdf('Beta',val/100,par1,par2);

Error in
parser.differentiate_system>@(s0,s1,y_44,y_48,y_49,y_76)(if_elseif(s0==1&s1==1,1-(prob_l_h(y_44,5,1)),s0==1&s1==2,prob_l_h(y_44,5,1),s0==2&s1==1,prob_h_l(y_44,5,1),s0==2&s1==2,1-(prob_h_l(y_44,5,1))))*(y_49-(y_48+y_76))

Error in parser.differentiate_system (line 34)
    myfunc{ifunc}=myfunc{ifunc}(arg_occur{:});

Error in parser.parse (line 428)
    original_funcs]=parser.differentiate_system(...

Error in dsge (line 260)
           
dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});



Do you have any idea of the error arises or how to get around this?Thank you again!MartinMartín Harding

German Institute for Economic Research (DIW Berlin)
Doctoral Student
Mohrenstrasse 58
10117 Berlin, Germany

Phone: +49 30 89789 614
Email: mharding@diw.de
www.diw.de
________________________________________________________
Executive Board: 
Prof. Marcel Fratzscher,
Ph.D. (President)
Dr. Cornelius Richter
(Managing Director) 
Prof. Dr. Gert G. Wagner
Chairman Board of
Trustees: 
Prof. Dr. Axel A. Weber
Registered Association
based in Berlin, Germany
Court of Registry:
Amtsgericht Berlin-Charlottenburg
Registry Number: 95 VR 136
NZ
________________________________________________________

DIW Berlin on Facebook and Twitter-----Junior Maih <notifications@github.com> schrieb: -----An: jmaih/RISE_toolbox <RISE_toolbox@noreply.github.com>Von: Junior Maih <notifications@github.com>Datum: 12.10.2016 12:59Kopie: mhardinga <mharding@diw.de>, Author <author@noreply.github.com>Betreff: Re: [jmaih/RISE_toolbox] external functions and endogenous probabilities (#29)Hi Martin,

What you say is correct! As long as the variables entering the transition probabilities have a unique steady state RISE will not complain.

There is no problem with external functions either., As long as your function is on the matlab path RISE will see it. You don't need to declare it. There shouldn't be any problem as long as RISE recognizes the basic components of your function. For example the following "extermal" function will work fine.

function p=myfun(x,g)p=1/(1+exp(-g*x));end

Cheers,

Junior

**Comment by jmaih** [comment]
Hi Martin,

This happens because RISE does not recognizes the internals of the function and therefore does not know how to differentiate it. I have now included some the beta distribution in the list of functions recognized by RISE. Update RISE on your end to get the changes.

Note you will have to use `betacdf(x,a,b)` instead of `cdf('beta',x,a,b)`.

Cheers,

Junior

**Comment by mhardinga** [comment]
Hi Junior,thanks again. I uploaded the toolkit and I see that the betacdf function now shows up in the splanar file. However, when trying to use it, an error remains, now in the char file:Error using splanar/char (line 117)unknown function :: betapdfError in splanar/char (line 64)        args{iarg}=char(args{iarg},long);Error in splanar/char (line 64)        args{iarg}=char(args{iarg},long);Error in splanar/char (line 64)        args{iarg}=char(args{iarg},long);Error in splanar/char (line 64)        args{iarg}=char(args{iarg},long);Error in splanar/char (line 64)        args{iarg}=char(args{iarg},long);Error in splanar/char (line 49)        c{irow}=char(x(irow),long);Error in splanar.print (line 84)    c=char(deriv.derivatives,long);Error in parser.differentiate_system (line 40)derivs=splanar.print(derivs,input_list);Error in parser.parse (line 428)    original_funcs]=parser.differentiate_system(...Error in dsge (line 260)            dictionary=parser.parse(model_filename,cmfArgins{:});Error in rise (line 64)            obj=obj@dsge(varargin{:}); I run the model using other cdfs supported by RISE, like the normcdf and this error doesn't show up. Cheers,Martin-----Junior Maih <notifications@github.com> schrieb: -----An: jmaih/RISE_toolbox <RISE_toolbox@noreply.github.com>Von: Junior Maih <notifications@github.com>Datum: 12.10.2016 17:54Kopie: mhardinga <mharding@diw.de>, Author <author@noreply.github.com>Betreff: Re: [jmaih/RISE_toolbox] external functions and endogenous probabilities (#29)Hi Martin,

This happens because RISE does not recognizes the internals of the function and therefore does not know how to differentiate it. I have now included some the beta distribution in the list of functions recognized by RISE. Update RISE on your end to get the changes.

Note you will have to use betacdf(x,a,b) instead of cdf('beta',x,a,b).

Cheers,

Junior

**Comment by jmaih** [comment]
Hi Martin,

Try again. Everything should work fine now.

Thanks,

J.

**Comment by mhardinga** [comment]
Hi Junior,it works, thanks a lot!Martin-----Junior Maih <notifications@github.com> schrieb: -----An: jmaih/RISE_toolbox <RISE_toolbox@noreply.github.com>Von: Junior Maih <notifications@github.com>Datum: 13.10.2016 11:53Kopie: mhardinga <mharding@diw.de>, Author <author@noreply.github.com>Betreff: Re: [jmaih/RISE_toolbox] external functions and endogenous probabilities (#29)Hi Martin,

Try again. Everything should work fine now.

Thanks,

J.
