### ISSUE TITLE
parameter_restrictions

### ISSUE THREAD

**Issue by AnasZa** [jmaih/RISE_toolbox#30]
Dear Junior,

I need to impose a restriction on parameters which looks like 
(1-zlb_tp_2_1)*Pi_star/K < 1

zlb_tp_2_1 is a transition probability

Which is exactly as the restriction (44) in your joint paper with Binning (2016). 
However it seems like RISE is not very happy, it returns:

Error using str2func
Error: Unbalanced or unexpected parenthesis or bracket.
Error in
rise_generic/setup_nonlinear_restrictions>reprocess_nonlinear_restrictions
(line 240)
    nonlcon=str2func(['@(M)[',nonlcon,']']);
Error in rise_generic/setup_nonlinear_restrictions (line 66)
nonlinear_restrictions=reprocess_nonlinear_restrictions(RestrictionsBlock);
Error in rise_generic/setup_restrictions (line 32)
    obj=setup_nonlinear_restrictions(obj);
Error in rise_generic/transform_parameters (line 68)
obj=setup_restrictions(obj);
Error in rise_generic/estimate (line 268)
[obj,x0,lb_short,ub_short]=transform_parameters(obj,x0,lb,ub);
Error in dsge/estimate (line 27)
...

What is the right way to write down such restriction? 

Thank you in advance.

**Comment by jmaih** [comment]
Hi Anastasia,

Did you remember to put a semi-colon at the end of the statement?

J.

**Comment by AnasZa** [comment]
Dear Junior,
Actually I thought there is no need in semi-colon.

If i have a restriction of this type:

	zlb_flag(zlb,2)>=zlb_flag(zlb,1)

It works perfectly well without any semi-colon. But I tried semi-colon anyway and it gives me:

Error using str2func
Error: Unbalanced or unexpected parenthesis or bracket.
Error in rise_generic/setup_nonlinear_restrictions (line 66)
nonlinear_restrictions=reprocess_nonlinear_restrictions(RestrictionsBlock);
Error in rise_generic/setup_restrictions (line 32)
    obj=setup_nonlinear_restrictions(obj);
Error in rise_generic/transform_parameters (line 68)
obj=setup_restrictions(obj);
...

And it is not to verify that there is no such problem in this expression : (1-zlb_tp_2_1)*Pi_star/K < 1

Do you have an idea what else may go wrong?
Thank you!

**Comment by jmaih** [comment]
Hi Anastasia,

Do you have many restrictions or only one? If you have many restrictions then each of them should end with a semi-colon.

I could not replicate the problem. I may have to see your model file.

Cheers,

J.
