### ISSUE TITLE
ARMA(1,1) process

### ISSUE THREAD

**Issue by gerreth** [jmaih/RISE_toolbox#33]
Dear Junior,

I recently updated the toolbox and now got a problem with my model. The last error message says:

```
Error using parser.create_auxiliary_equations>auxiliarize_exo_params/auxiliarize_one_equation (line 287)
Leads or lags on parameters or exogenous not allowed
```

I do have 2 ARMA(1,1) processes in my model, namely

```
laf_t   = rho_laf*laf_t(-1) + sig_laf*laf_sh - eta_laf*laf_sh(-1);
law_t   = rho_law*law_t(-1) + sig_law*law_sh - eta_law*law_sh(-1);
```

where laf_sh and law_sh are exogenous shocks. Is there a way around this issue?

Greetings
Gerret

**Comment by jmaih** [comment]
Hi Gerret,

Thanks for reporting this. There are two solutions:

1. You update RISE again

1. You create auxiliary variables.

Let me know if there is any further issue,

Cheers,

Junior
