### ISSUE TITLE
DSGE:Tutorial 1

### ISSUE THREAD

**Issue by Aiyetan52** [jmaih/RISE_toolbox#34]
Hello everyone, I need explanation on how Tao Zha Tutorial 1 under DSGE brought in his Data into the program. Reading the code I could not get the section. Please provide help as it very crucial for my Msc thesis.

**Comment by jmaih** [comment]
Hi, 

The raw data are first transformed into a RISE time series object ts and then passed to a DSGE/RISE model object.  Essentially this process is about assigning a date to every observation in the dataset. The advantage of having data in a time series format is that various transformations can be easily applied.

Cheers,

Junior

**Comment by Aiyetan52** [comment]
Prof I understand your explanation and that is how Tao zha DSGE tutorial 2 under various examples brought in his data. But  my Prof I could not see the same process in Tao zha DSGE tutorial 1 where we have the impulse response and historical decomposition (i.e. the simulated data). Prof sir, I need your explanation as it will help my M.sc thesis.

**Comment by jmaih** [comment]
Hi,

There is no other way to pass the data in RISE than what I explained. Impulse responses do not require data, they are simply a function of the solution of the model. Historical decomposition does not involve simulation, it decomposes the data passed by the user into contributions of shocks.

Cheers,

Junior

**Comment by Aiyetan52** [comment]
Prof Maih thank you for the powerful contribution so far.  But when solving the models does it not requires bringing in the data into program.  Also,  is simulated data graph the same as counterfactual analysis graph.  lastly,  how do I go about generating variance decomposition that is the programing code for variance decomposition. Prof sir,  your explanation is very important for the progress of my M. sc thesis.

**Comment by Aiyetan52** [comment]
Prof Maih thank you for the powerful contribution so far.  But when solving the models does it not requires bringing in the data into the program.  Also,  is simulated data graph the same as counterfactual analysis graph.  lastly,  how do I go about generating variance decomposition that is the programing code for variance decomposition. Prof sir,  your explanation is very important for the progress of my M. sc thesis.

**Comment by jmaih** [comment]
Hi,

The solution of the model takes the form `y(t)=T(y(t-1),e(t))` i.e. the solution is a function of the state variables `y(t-1)` and the shocks `e(t)`, with the function `T(.)` given. In the notation above, I assume that both `y(t)` and `e(t)` are vectors of variables. e.g. vector "y" may comprise consumption, investment, interest rate, output, etc. while vector "e" may include monetary policy shock, technology shock, etc.

1. For some given initial conditions `y(0)`, and a sequence of shocks `e(1), e(2),..., e(n)` one can recursively generate values for `y(1), y(2),...,y(n)`. This exercise is a simulation of artificial data.

1. A related exercise is the historical decomposition of the data into shocks. Again, given some initial condition y(0), one can find the sequence of shocks `e(1), e(2),..., e(n)` that replicate the observed time series `y(1), y(2),..., y(n)` for a given solution `y(t)=T(y(t-1),e(t))`. In this particular exercise we generate shocks given the data while in the previous one we generate data given shocks.

1. A counterfactual is a particular simulation in which we try to answer the question: what would have happened if different conditions had been in place. For instance, what would consumption, investment, output, etc. have looked like if there had been no monetary policy shocks. One way to answer that question is to set all the value of the monetary policy shocks (obtained from historical decomposition) to zero and re-simulate the model.

I am afraid I do not have time to provide further theoretical details. You can find more details on simulation, historical decomposition and counterfactual by a simple google search. I guess your supervisor can help too...

Good luck with your thesis,

Cheers,

Junior

**Comment by Aiyetan52** [comment]
Prof., thank you for the tremendous contribution you've made so far for the progress of my M. sc thesis. I am grateful sir. In addition,  I have been reading through something on this method since the last time you provided answer to my last question. later in the day, I will ask some fundamental questions so as to proceed to the next face of my thesis. Prof sir thank you once again for the wonderful contributions up till now.

**Comment by Aiyetan52** [comment]
Sir,  please I need explanation on how to generate initial values for  Markov Switching DSGE.  Having read Minimal state variable solutions to MSRE by Farmer,  Waggoner and Zha,  yet I find it difficult to understand how to generate initial values in the case of Nigeria. Please kindly help me.  In addition,  if there is code to generate it using Nigeria data provide it sir.

**Comment by jmaih** [comment]
Hi,

The strategies that RISE uses for generating initial values are described in the following paper

http://www.norges-bank.no/en/Published/Papers/Working-Papers/2015/12015/

Cheers,

Junior

**Comment by Aiyetan52** [comment]
Prof sir,  I am already in page 25 of the article you sent to me,  but,  before I proceed I want to ask that  is there not example (s) on how to generate the initial values on RISE toolbox. Thank you in anticipation of your response.

**Comment by jmaih** [comment]
Initial values are simply a guess. If the solution is unique, then with a robust solution algorithm, all initial conditions will arrive at the same result. If the model has multiple solutions, there is no guarantee that we will arrive at the same solution.

About how to generate initial values, search help for dsge/solve i.e. run in the command window `help dsge/solve`  one of the options is going to be about initialization.

**Comment by Aiyetan52** [comment]
[iowa prof1.docx](https://github.com/jmaih/RISE_toolbox/files/652528/iowa.prof1.docx)
Prof, up till now, I've not gotten how to code the model  attach above on Matlab using RISE interface to generate the posterior mean and transition probabilities. Please Prof provide help sir.

**Comment by Aiyetan52** [comment]
Prof, I understand the theoretical background of the model in terms of the prior, likelihood and posterior functions (Bayesian approach) but how to code it on Matlab is the challenge I am facing. Please  provide help.

**Comment by Aiyetan52** [comment]
Hello Prof thank you for all your contribution so far. I want to inform you that I've gotten the analysis and I'm about to finish my chapter four. I will properly send my message of appreciation to you and RISE team including Prof Drago for his material that I read for basic new-Keynesian model.
