### ISSUE TITLE
solving a 2-regime model around arbitrary point

### ISSUE THREAD

**Issue by mhardinga** [jmaih/RISE_toolbox#35]
Hi Junior,

I would like to solve a 2-regime switching model around an arbitrary point, say between the SS at regime 1 and the SS at regime 2. I guess this could be done using the option `'steady_state_imposed','true'`, am I right?

My question is that I am not sure if that is the correct option, or how to use it. I'm working with a SS file (that works just fine when I don't try to impose the SS), and so I tried the command `m=solve(m,'steady_state_file','mymodel_steadystate','steady_state_imposed','true')` 

but I get the following error:
`Operands to the || and && operators must be convertible to logical scalar values.
Error in dsge/compute_steady_state>prepare_steady_state_program (line 1024)
        if ~(sscode.is_imposed_steady_state||...
Error in dsge/compute_steady_state (line 129)
[obj,sscode,blocks,unsolved]=prepare_steady_state_program(obj);
Error in dsge/solve/solve_zeroth_order (line 551)
            [obj,structural_matrices,retcode]=compute_steady_state(obj);
Error in dsge/solve (line 340)
retcode=solve_zeroth_order();`

and when I go to the `compute_steady_state` function, the error reads: 

`errmsg=['With an initial guess for the steady state, the parameters cannot be modified in the steady state model or file'];`

Do you know how to do this properly?

Thanks a lot.

Martin

**Comment by jmaih** [comment]
Hi Martin,

1.  Yes the option is `'steady_state_imposed','true'` if you want to impose a particular point
1.  You can also solve the model around the ergodic mean in which case the option is `'steady_state_unique','true'`
1. I do not understand the error. Do you mind sending me your files so that I can take a close look?

Cheers,
Junior

**Comment by mhardinga** [comment]
Hi Junior,
thank you, I sent you the files. I will work with the model at the ergodic mean for now.
Cheers,
Martin

**Comment by jmaih** [comment]
Hi Martin,

Your problem appears to be just a typo. You should write `true` and not `'true'`.

Can you see the difference? If not, simply replace it with `logical(1)`

Cheers,
Junior

**Comment by mhardinga** [comment]
Hi Junior,
you're right, that was the mistake. Thanks!
Martin



Von:    Junior Maih <notifications@github.com>
An:     jmaih/RISE_toolbox <RISE_toolbox@noreply.github.com>
Kopie:  mhardinga <mharding@diw.de>, Author <author@noreply.github.com>
Datum:  24.01.2017 10:59
Betreff:        Re: [jmaih/RISE_toolbox] solving a 2-regime model around 
arbitrary point (#35)



Hi Martin,
Your problem appears to be just a typo. You should write true and not 
'true'.
Can you see the difference? If not, simply replace it with logical(1)
Cheers,
Junior
