### ISSUE TITLE
Error in parser.capture

### ISSUE THREAD

**Issue by addsam004** [jmaih/RISE_toolbox#36]
Hi Junior
I run the attached file and gives me the following error what has gone wrong and how do I fix it. 
error using parser.capture_parameterization/capture_parameterization_engine/process_normal (line 237)
Error: This statement is incomplete.

Error in parser.capture_parameterization/capture_parameterization_engine (line 153)
            process_normal()
[modelcodepapertwo1.zip](https://github.com/jmaih/RISE_toolbox/files/736865/modelcodepapertwo1.zip)
Best, 
Sam

**Comment by jmaih** [comment]
Hi Sam,

At line 76 and line 78 in file fwz_est.rs, you have added extra commas.

Cheers,

Junior

**Comment by addsam004** [comment]
Lovely! thank you for the swift response.

greetings Junior


Best,
