### ISSUE TITLE
Explosion Limit reached

### ISSUE THREAD

**Issue by addsam004** [jmaih/RISE_toolbox#37]
Dear Junior
I tried running a small open economy with export and it gives these errors
****Looking for good enough start values. Please wait...
  1 :: Explosion limit reached
483 :: Maximum Number of iterations reached or multiple solutions
499 :: Explosion limit reached
Error using generic/find_posterior_mode (line 78)
find_posterior_mode:: No admissible starting value after 500 trials****

What is the cause of this problem and how do I fix it.

regard
Sam

**Comment by jmaih** [comment]
Hi Sam,

This problem often occurs when there is either a problem with the model or with the data. In both cases this may result in a poor initial likelihood. RISE attempts to find a good starting value but fails. 

- Explosion  limit reached, most likely, refers to the solving of the initial covariance matrix. If the model is nonstationary, for some reason, then the covariance matrix does not exist. What you could do in that case is to initialize the filter with a large variance. You do so by setting the option "kf_init_variance" to some arbitrary number, say 5, 10 or 100.

- Maximum Number of iterations reached or multiple solutions means a solution could not be found for that particular parameterization.

Cheers,

Junior

**Comment by addsam004** [comment]
Dear Junior,
Great! it has worked.  Am now enjoying the software and the dynamics of the output.

Best,
Sam

**Comment by jmaih** [comment]
The tutorial you've been looking at needs updating. Unfortunately I am currently overstretched and do not have extra time on hands to update it. Hopefully soon I will have the opportunity to look at it again. The other tutorials/examples should work.

**Comment by addsam004** [comment]
Dear Junior,
sure the others are working
Many thanks

Sam
