### ISSUE TITLE
error using simulate

### ISSUE THREAD

**Issue by mhardinga** [jmaih/RISE_toolbox#39]
Hi Junior,

I'm getting an error message when using the `simulate` RISE command in the context of a RS-DSGE model with endogenous probabilities. The error reads:

`Error using generic/simulate (line 166)
Problem in transition matrix
Error in dsge/simulate (line 21)
[varargout{1:nargout}]=simulate@generic_switch(obj,varargin{:}); `

I find it puzzling that the error appears only in certain configurations. It may or may not appear depending on the parameters governing the probability functions, the way to compute the steady state (i.e., whether it is imposed, unique or regime-specific), and the number of periods in the simulation. E.g., in a particular exercise, the error does not appear if I use 10.000 or less periods, but it shows up if I use 11.000 or more periods. 

Do you know what could be going on?

Cheers,
Martin

**Comment by jmaih** [comment]
Hi Martin,

what do the transition probabilities look like? Could it be the case that for some combinations of parameter values and endogenous variables, the probabilities are undefined, negative or do not sum to 1?

Cheers,

J.

**Comment by mhardinga** [comment]
Hi Junior,

you are right, the probability functions allowed (in very rare cases) for values greater than one, and I guess that's when the code crashed. 

Many thanks!

Martin
