### ISSUE TITLE
Error Tao Zha Tutorial2 - rise_save_macro

### ISSUE THREAD

**Issue by angelaabbate** [jmaih/RISE_toolbox#4]
I am the first :)

I am trying to run now Tutorial 2:
RISE_toolbox-master/examples/VariousModels/TaoZha/Tutorials/DSGE/Tutorial2

after fixing 
/RISE_toolbox-master/examples/VariousModels/TaoZha/Tutorials/DSGE/Tutorial2/Models/fwz_est.rs
by removing the (linear) specification

howto.m (line 67) is calling for a property which is no longer available (I guess). I get the following error message:

Error using rise_generic/set/set_one_at_a_time (line 139)
'rise_save_macro' is not a settable option or property of class rise 

I have tried commenting out the following line (68), the code runs but the results look very strange (very persistent smoothed probabilities) and not at all in line with the pdf available.

I guess this line is needed (as it stores the results). How can we fix this problem?

Best,

Angela

**Comment by jmaih** [comment]
Hi Angela,

You are the first indeed. I have updated the tutorial you are talking about but I have not re-run the estimation. The objective function is typically very non-gaussian and fmincon usually lands on a local peak. One way to see whether you get the same profile for the transition probabilities is to run the filter with the parameters set to the estimated values in the pdf. Alternatively, one may want to run a more robust optimizer than fmincon.

Best,

Junior
