### ISSUE TITLE
Problems in simulating model with ZLB

### ISSUE THREAD

**Issue by andrewsun90** [jmaih/RISE_toolbox#40]
Hi Junior,

I tried to use RISE to solve and simulate a DSGE model with the ZLB, but it seems not working.

The model I use is a nonlinear version of the Smets and Wouters (2007) model. If no ZLB constraint is imposed, then the results obtained from RISE is the same as the results obtained from Dynare.

To include the ZLB constraint, four new parameters are introduced:
`parameters ocb_tp_1_2 ocb_tp_2_1`
`parameters(ocb,2) bind`

They are calibrated as follows:
`p.bind_ocb_1 = 0;`
`p.bind_ocb_2 = 1;`
`p.ocb_tp_1_2 = 0;`
`p.ocb_tp_2_1 = 0;`

In the original model, the nominal interest rate is expressed as `R = Robs/100`, with a steady state value of 0.0159. To include the ZLB constraint, I changed this expression to `R = bind*0 + (1 - bind)*Robs/100;`. Besides, I also added `? R >= 0;` in the `model` part.

Finally, I extended the `solve` command, so that
`m = solve(m,'solve_occbin',1,'steady_state_imposed',true,'steady_state_unique',true);`.

There was no problem in solving this model. However, when I was trying to simulate the model using
`mysims = simulate(m,'simul_honor_constraints',true);`
I got the following error messages

> Error using generic/simulate (line 166)
> forecast: constraint violation

> Error in dsge/simulate (line 21)
> [varargout{1:nargout}] = simulate@generic_switch(obj,varargin{:});

I don't know where the problem comes from. Could you help me with this please? Thanks!

Best,
Zexi

**Comment by jmaih** [comment]
Hi Zexi,

The only programs that work with the max operator are perfect foresight and extended path as we saw in the course.

You should not mix occbin, max, R>=0, etc. All of those things have specific meanings again, as we saw in the course.

Check the files we ran during the course!

Cheers,

Junior

**Comment by andrewsun90** [comment]
Hi Junior,

Thanks for your kind reply. I just checked the files we ran in the course. In fact, I was trying to follow your example codes.

In `occbin.rz`, you wrote the following:
`parameters r_zlb ocb_tp_1_2 ocb_tp_2_1`
`parameters(ocb,2) bind`
and the following two equations in the `model` part:
`? R>=1;`
`R = bind*r_zlb + (1-bind)*R_TAYLOR;`

In `assgn13_occbin.m`, you RISEed the model, set the parameter values, pushed the steady state, solved the model and finally simulated the model by:
`mysims = simulate(m,'simul_periods',1000,'simul_honor_constraints',true);`
From the simulated series we can see that R is always higher than or equal to one, and if instead we use
`mysims = simulate(m,'simul_periods',1000);`
then R can sometimes be lower than one.

It was strange that I almost repeated what you did above, but could not get the same result. Could you help me find what is wrong?


Cheers,
Zexi

**Comment by andrewsun90** [comment]
Hi Junior,

Sometimes when I even ran the code you shown in class, the error message will pop out.

For example, I uploaded a zip-file containing the original code you have written. I barely changed anything, but you will find the error message sometimes when running this line:

`mysims = simulate(m,'simul_periods',1000,'simul_honor_constraints',true);`

The error message is still the same:

> Error using generic/simulate (line 166)
> forecast: constraint violation

> Error in dsge/simulate (line 21)
> [varargout{1:nargout}] = simulate@generic_switch(obj,varargin{:});

The strange thing is, sometimes it happens, and sometimes it doesn't. So it is fairly hard to say where the problem is coming from.

[Day3.zip](https://github.com/jmaih/RISE_toolbox/files/796532/Day3.zip)


Cheers,
Zexi

**Comment by jmaih** [comment]
On your previous message, this is a simulation and so it is expected that you will get different results all the time.

On your last message, this sometimes occur with the way the transition probabilities are specified. Unfortunately because of the limited time we did not get to talk about all the small details.

Cheers,

J.

**Comment by andrewsun90** [comment]
Thanks for your comments Junior.

Could you tell me more about the relationship between the transition probabilities and the simulation results? Or if there is any paper/books that I can find an explanation about this?

Best,
Zexi

**Comment by jmaih** [comment]
This would require going into the very functional forms for the transition probabilities and their parameterizations. Not something I can do in an email or an online message.

If you do not know how to modify the probabiliites a stopgap would be to put a try catch statement and get the simulations that work

```
success=false;

while ~success

   try

      mysims=simulate(m);

      success=true;

   end

end

```

Cheers,

J.

**Comment by andrewsun90** [comment]
Thanks Junior, your suggestion is really helpful!

Best,
Zexi
