### ISSUE TITLE
Problem plot_posteriors

### ISSUE THREAD

**Issue by lusantos1971** [jmaih/RISE_toolbox#42]
Hi Junior, 

I followed your instructions for Xiaofeng but I did not have success. The instructions are reproduced following:
**create an objective function for posterior simulation**
[objective,lb,ub,x0,SIG]=pull_objective(mest);

**Set up the options for the Metropolis Hasting algorithm**
ndraws_mcmc = 1500; % number of parameter draws through MCMC.
ndraws_burnin = floor(0.1*ndraws_mcmc); % number of parameter draws to be burned
mcmc_options=struct('burnin',ndraws_burnin,'N',ndraws_mcmc,'thin',1);

**Run the Metropolis hastings algorithm to sample from the posterior distribution**
Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG);

**Plot the posterior distribution of the parameters**
plot_posteriors(mest,Results.pop)

I tried to follow these steps to plot the posterioris, but I got the following error message: 

Error using mh_sampler>(parfor body) (line 560)
Matrix must be positive definite.

Error in mh_sampler/scale_times_sqrt_covariance_updating (line 542)
            parfor (ichain=1:nchain,NumWorkers)

Error in mh_sampler (line 368)
scale_times_sqrt_covariance_updating()

Caused by:
    Error using chol
    Matrix must be positive definite.
 
Someone could help me?

Thank you very much in advance
Best
Luís

**Comment by lusantos1971** [comment]
Hi Junior, 
Apparently, worked. But when I use plot_posterior, this error message appears:

>> plot_posteriors(m,Results.pop)
Error using set
Bad property value found.
Object Name: axes
Property Name: 'XLim'
Values must be increasing and non-NaN.

Error in axis>LocSetLimits (line 201)
    set(ax,...

Error in axis (line 93)
                LocSetLimits(ax(j),cur_arg);

Error in utils.plot.prior_posterior (line 117)
axis([ss.x_min ss.x_max bottom 1*top]);

Error in generic/plot_posteriors/plotfunc (line 290)
        [~,legend_,tex_name]=utils.plot.prior_posterior(pdata.(pname),vargs{:});

Error in generic/plot_posteriors>@(xname)plotfunc(xname,pdata_) (line 242)
    tmphdl=utils.plot.multiple(@(xname)plotfunc(xname,pdata_),...

Error in utils.plot.multiple (line 111)
                [tex_name,legend_]=plotfunc(vnames{par_id});

Error in generic/plot_posteriors (line 242)
    tmphdl=utils.plot.multiple(@(xname)plotfunc(xname,pdata_),...

**Comment by jmaih** [comment]
It would be difficult for me to debug this kind of error without being able
to replicate the problem.

Do you have enough simulations and enough variation in the simulations?


--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by lusantos1971** [comment]
Hi Junior, 

I am trying to run the Frank & Schorfheide example (Loss Function JAE2000). 


%% housekeeping
clear classes
clc
close all
%% "rise" the model
m=rise('fs2000_rise');
%% pushing the particular vector (different from the initial estimation point)
% Note we have to declare the regime of the parameter

calibration=struct();
	calibration.alp=0.330;
	calibration.bet=0.990;
	calibration.gam=0.003;
	calibration.mst=1.011;
	calibration.rho=0.700;
	calibration.psi=0.787;
	calibration.del=0.020;
	calibration.sig_a=0.014;
	calibration.sig_m=0.005;
m=set(m,'parameters',calibration); 

%% solve the model and 
m=solve(m);

%% print the solution 

m.print_solution

disp('This should be identical to the dynare solution (see folder dynare_version)')

%% lets do some estimation: we need the data
% get the data from the dynare_version folder

run dynare_version\fsdat_simul

% rise needs data to be passed as a ts object with dates and
% names of the variables. So we proceed to constructing the database

% we use the same start date as in the Schorfheide paper even though the
% data are not the same
startdate='1950q1';
database=ts(startdate,[gp_obs,gy_obs],{'gp_obs','gy_obs'});

%% pass the data to the rise object

% 192 observations are used in dynare
end_date= obs2date(startdate,192);
% the loglinear option of dynare implies:
% 1- we have to take the log of our data. 
% 2- we have to exponentiate the corresponding variables in the rise model
% file. Dynare does this by taking the log of the steady state during
% estimation and this does not ring too transparent to me.

% In rise, we can just take the log of the whole database. This is  
% what we do in passing the data. But we also need to tell ts
% that the logged variables should have the same names as the original
% ones. In order to do that, we add set the flag to true when taking the
% log.
vnames=database.varnames;
database=log(database);
database.varnames=vnames;
m=set(m,'data',database,'estim_end_date',end_date);

%% estimate the model
profile off
profile on
m=estimate(m);%,'optimizer',@csminwellwrap,'debug',true
profile off
profile viewer

%% do posterior simulation
[objective,lb,ub,x0,SIG]=pull_objective(m)
SIG=utils.cov.nearest(SIG)
mcmc_options=struct('burnin',ndraws_burnin,'N',draws_mcmc,'thin',1);
draws_mcmc = 15000; % number of parameter draws through MCMC.
ndraws_burnin = floor(0.1*draws_mcmc);
mcmc_options=struct('burnin',ndraws_burnin,'N',draws_mcmc,'thin',1);
Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG)
plot_posteriors(m,Results.pop)

**Comment by jmaih** [comment]
I still could not replicate the problem.

Are you using the latest version of RISE?

If you re-run the codes to you still fail?

J.

--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)
