### ISSUE TITLE
Problem with example "LWZ_Econometrica2013"

### ISSUE THREAD

**Issue by zhuzixiang** [jmaih/RISE_toolbox#43]
Dear Junior,
I use your RISE_toolbox to run the Zha Tao's example "LWZ_Econometrica2013",the m file master.m, but the results show that:

file2blocks:: (gentle warning): I is also a matlab function
file2blocks:: (gentle warning): Le is also a matlab function
file2blocks:: (gentle warning): Mu is also a matlab function
file2blocks:: (gentle warning): Psi is also a matlab function
file2blocks:: (gentle warning): alpha is also a matlab function
Error using parser.capture_equations/capture_equations_engine (line 124)
capture_equations:: attributes to model block no longer permitted in file lwz_model at
line 73

Error in parser.capture_equations (line 58)
    [block,equation]=capture_equations_engine(block,listing(ii,:),block_name,equation);

Error in parser.parse_model (line 25)
[Model_block,dictionary]=parser.capture_equations(dictionary,blocks(current_block_id).listing,'model');

Error in parser.parse (line 195)
[Model_block,dictionary,blocks]=parser.parse_model(dictionary,blocks);

Error in dsge (line 320)
            dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});

Error in master (line 5)
m=rise('lwz_model');

So what does "model block no longer permitted in file lwz_model" mean?Is it because dynare has been installed in my matlab, thus the command "model(linear)" conflicts with your toolbox? Should I uninstall dynare in order to run this example?

Thanks!

I am looking forward to your reply.

Zixiang Zhu

School of Economics and Management
Southwest Jiaotong University,Chengdu,P.R. China

**Comment by jmaih** [comment]
Dear Zixiang,

I have updated the example. It should run fine now.

Please let me know if it does not.

Best,

Junior

--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by zhuzixiang** [comment]
Dear Junior,
Thanks! The previous problem is solved, but a new problem emerge:

parameter: SIG_EPS_XITHETA, density:INV_GAMMA, hyperparameters: [0.3261 0.00014518],convergence 1.4533e-13
prior_setting_engine(GENTLE WARNING):: upper bound of inverse gamma distribution truncated at 10
Operands to the || and && operators must be convertible to logical scalar values.

Error in dsge/compute_steady_state>check_residuals (line 366)
flag=all(isfinite(r)) && max(abs(r))<tol;

Error in dsge/compute_steady_state>divide_and_conquer (line 583)
if check_residuals(r,optimopt.TolFun)

Error in dsge/compute_steady_state>run_one_regime (line 426)
    [y,g,p,r,retcode]=divide_and_conquer(y0,g0,p,x,d,unsolved,dq_blocks);

Error in dsge/compute_steady_state (line 247)
            run_one_regime(y0(:,istate),g0(:,istate),p(:,istate),x,...

Error in dsge/solve/solve_zeroth_order (line 533)
            [obj,structural_matrices,retcode]=compute_steady_state(obj);

Error in dsge/solve (line 300)
retcode=solve_zeroth_order();

Error in likelihood_markov_switching_dsge (line 31)
[obj,retcode]=solve(obj);

Error in generic/log_posterior_kernel (line 53)
    [log_lik,Incr,retcode,obj]=likelihood_func(param,obj);

Error in generic/estimation_wrapper/fh_wrapper (line 154)
                [fval(mo),~,~,~,retcode,obj(mo)]=log_posterior_kernel(obj(mo),x);

Error in generic/estimation_wrapper (line 111)
        [f1,retcode_0,max_pen]=fh_wrapper(x0);

Error in generic/find_posterior_mode (line 44)
[x0(:,1),f0(1),~,retcode0,viol,obj,funevals]=estimation_wrapper(obj,[],x0(:,1),lb,ub,funevals);

Error in generic/estimate (line 283)
[x1,f1,H,x0,f0,viol,funevals,issue,obj]=find_posterior_mode(obj,x0,lb_short,ub_short);
%#ok<ASGLU>

Error in dsge/estimate (line 47)
    obj=estimate@generic_switch(obj,varargin{:});

Error in master (line 21)
ms=estimate(m,'data',data,...

What does "Operands to the || and && operators must be convertible to logical scalar values."  mean?

Thank you!

Zixiang Zhu

**Comment by jmaih** [comment]
Everything should work now.

Cheers,

Junior

>

**Comment by zhuzixiang** [comment]
Exactly,it works! Thanks! :)

**Comment by jmaih** [comment]
Many thanks,

J.
