### ISSUE TITLE
A list of Problems about the Examples

### ISSUE THREAD

**Issue by zhuzixiang** [jmaih/RISE_toolbox#44]
Dear Junior,
Right now I am systematicly learning about how to use RISE as it really lowers the threshold about how to solve and estimate Markov-DSGE model. This is very good for beginners, thanks!

Now I am trying to run several examples included in the RISE and encountered some problems. Here they are:

**(1)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/TaoZha/Tutorials/DSGE/Tutorial1**

The results are:
....
Regime    2 : const = 1 & nk = 2 
                PAI          R          X         ZD       ZS  
              ________    _______    ________    ____    ______

    R{-1}     -0.70877    0.34035    -0.60807       0         0
    ZD{-1}      1.6535     0.5933      1.2358    0.68         0
    ZS{-1}      2.2564    0.70276     0.11434       0      0.82
    ED         0.65652    0.23558      0.4907    0.27         0
    ER         -0.2717    0.13047    -0.23309       0         0
    ES          2.3943     0.7457     0.12133       0    0.8701
              ________    _______    ________    ____    ______

                PAI          R          X         ZD       ZS  

Error using isfield
Too many input arguments.

Error in dsge/print_solution (line 91)
    if ~isfield(obj.solution,'Tz')||isempty(obj.solution.Tz{1})

Error in howto (line 71)
print_solution(m)

**(2)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/TaoZha/Tutorials/DSGE/Tutorial3**

The results are:

List of issues
 
none 
*--------------------------------------------------------------*
*----------- MCMC for svar_constant model-------------*
*--------------------------------------------------------------*
Undefined function or variable 'posterior_simulator'.

Error in howto (line 121)
        [obj{imod},postSims{imod}]=posterior_simulator(estim_models{imod},'mcmc_number_of_simulations',... 

**(3)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/MarkovSwitching/FarmerWaggonerZha2010**

The results are:

Parameterization ::1, solver ::mfi

MODEL  HAS NOT BEEN SOLVED AT LEAST UP TO THE FIRST ORDER
SOLVER :: mfi
Reference to non-existent field 'Tz'.

Error in dsge/print_solution>print_solution_engine/build_printing_array (line 211)
                Tz=obj.solution.(Tzname){regime_index}(ids,:).';

Error in dsge/print_solution>print_solution_engine (line 152)
    build_printing_array(ii,myprologue);

Error in dsge/print_solution (line 102)
    print_solution_engine(obj(iobj),varlist,compact_form,orders);

Error in howto (line 62)
        eval(['models_with_solver_',int2str(solver),'(ii,1).print_solution'])

**(4)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/PeterIreland/Endogenous_JME2003**

The results are:

none 
file2blocks:: (gentle warning): I is also a matlab function
file2blocks:: (gentle warning): MU is also a matlab function
file2blocks:: (gentle warning): beta is also a matlab function
file2blocks:: (gentle warning): alpha is also a matlab function
Error using parser.capture_equations/capture_equations_engine (line 124)
capture_equations:: attributes to model block no longer permitted in file
emosp_linear at line 23

Error in parser.capture_equations (line 58)
    [block,equation]=capture_equations_engine(block,listing(ii,:),block_name,equation);
    
Error in parser.parse_model (line 25)
[Model_block,dictionary]=parser.capture_equations(dictionary,blocks(current_block_id).listing,'model');

Error in parser.parse (line 195)
[Model_block,dictionary,blocks]=parser.parse_model(dictionary,blocks);

Error in dsge (line 320)
            dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});

Error in master (line 59)
ml=rise('emosp_linear','rise_flags',{'original',true});

**(5)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/PeterIreland/NKperspective_JMCB2011**

The results are:

Error using generic/set/set_one_at_a_time (line 232)
forecast_start_date' is not a settable option or property of class rise

Error in generic/set (line 178)
        set_one_at_a_time();

Error in dsge/set (line 132)
obj=set@generic_switch(obj,varargin{:});

Error in generic/forecast (line 107)
obj=set(obj,varargin{:});

Error in master (line 115)
        fkst=forecast(mest,'data',pageify(serials(2)-1,db),...

**(6)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/PeterIreland/productivity_RED2008**

The results are:

Insufficient number of outputs from right hand side of equal sign to satisfy
assignment.

Error in
parser.preparse>process_flow_controls/process_flow_control_engine/do_for/update_set
(line 324)
                sset=info.set;

Error in parser.preparse>process_flow_controls/process_flow_control_engine/do_for
(line 308)
            update_set()

Error in parser.preparse>process_flow_controls/process_flow_control_engine (line
289)
                do_for()

Error in parser.preparse>process_flow_controls (line 279)
    process_flow_control_engine()

Error in parser.preparse>preparse_expand (line 140)
[rawfile,has_macro]=process_flow_controls(rawfile,definitions,has_macro);

Error in parser.preparse (line 105)
[output,has_macro]=preparse_expand(RawFile,parsing_definitions);

Error in parser.parse (line 137)
RawFile=parser.preparse(FileName,DefaultOptions.rise_flags);

Error in dsge (line 320)
            dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});

Error in master (line 6)
m=rise('pdk','rise_flags',{'Sektors',{'C','I'}},...

**(7)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/PeterIreland/sgusea_JEEA2013**

The results are:

Insufficient number of outputs from right hand side of equal sign to satisfy
assignment.

Error in
parser.preparse>process_flow_controls/process_flow_control_engine/do_for/update_set
(line 324)
                sset=info.set;

Error in parser.preparse>process_flow_controls/process_flow_control_engine/do_for
(line 308)
            update_set()

Error in parser.preparse>process_flow_controls/process_flow_control_engine (line 289)
                do_for()

Error in parser.preparse>process_flow_controls (line 279)
    process_flow_control_engine()

Error in parser.preparse>preparse_expand (line 140)
[rawfile,has_macro]=process_flow_controls(rawfile,definitions,has_macro);

Error in parser.preparse (line 105)
[output,has_macro]=preparse_expand(RawFile,parsing_definitions);

Error in parser.parse (line 137)
RawFile=parser.preparse(FileName,DefaultOptions.rise_flags);

Error in dsge (line 320)
            dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});

Error in master12 (line 17)
m=rise('sgusea12',...

That's all.

Best

Zixiang Zhu

**Comment by jmaih** [comment]
Hi Zixiang,

Thank you for reporting. There are many examples that need updating with
the new syntax of RISE. But I have addressed the issues you've raised:

*(1)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/TaoZha/Tutorials/DSGE/Tutorial1*

Fixed

*(2)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/TaoZha/Tutorials/DSGE/Tutorial3*

You should use howto_new instead of howto

*(3)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/MarkovSwitching/FarmerWaggonerZha2010*

Fixed

*(4)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/PeterIreland/Endogenous_JME2003*

Fixed

*(5)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/PeterIreland/NKperspective_JMCB2011*

Fixed

*(6)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/PeterIreland/productivity_RED2008*

Fixed

*(7)/Users/zhuzixiang/Desktop/RISE_toolbox-master/examples/VariousModels/PeterIreland/sgusea_JEEA2013*

Fixed

Cheers,

Junior

**Comment by zhuzixiang** [comment]
Many thanks!:)
