### ISSUE TITLE
rfvar

### ISSUE THREAD

**Issue by addsam004** [jmaih/RISE_toolbox#45]
Dear Junior
Trusting you are doing well.  I tried using rfvar and reports the bug below
Struct contents reference from a non-struct array object.
Error in generic_switch/reset/mark_parameters (line 65)
                n=obj.parameters.number;
Error in generic_switch.reset (line 55)
            mark_parameters()
Error in svar (line 87)
            obj=generic_switch.reset(obj,out.endogenous,out.exogenous,...
Error in rfvar (line 76)
            obj=obj@svar(varargin{:});
Error in howto (line 32)
rv=rfvar(tmpl,'data',data);

How to fix it.
Best, 
Sam

**Comment by jmaih** [comment]
Hi Sam,

The rfvar and the svar modules are currently under revisions. There are
lots of improvements and flexibility that have been added but I am not
ready to push them yet on the public domain. I need to finish up the
interface and given my workload this might take a few weeks. But in the end
I hope you will be happy to see the changes.

Best,

Junior


--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)
