### ISSUE TITLE
A simple question about "parameterization"

### ISSUE THREAD

**Issue by zhuzixiang** [jmaih/RISE_toolbox#47]
Dear Junior,

I just want to know what does each entry represent in parameterization. For example, in the example “volatilityOnly_expanded”, there are:

....
parameterization
	tau          ,    0.5376,     0.1000,    0.5000,  gamma_pdf(.90);
	kappa        ,    0.5800,     0.0500,    1.0000,  gamma_pdf(.90);
	beta_trans   ,    0.1000,     0.2000,    0.4000,  beta_pdf(.90);
...

What does "0.5376" mean? Is  it initial prior value?
What do "0.1000" and "0.5000" mean respectively? Are they the lower bound and upper bound of 90 percent confidence interval of gamma_pdf?

Thanks!
Zixiang Zhu

**Comment by jmaih** [comment]
Hi Zixiang,

Why are you so smart? :)

Your intuition is exactly right. You don't need me to understand the
notation.

If you want to set things in terms of means and standard deviations
instead, you can also do that. In that case the syntax is

paramName , start, mean, standardDev, distrib;

while the other syntax is

paramName , start, LQ, UQ, distrib(prob);

So then, the interpretation of the 3rd and 4th elements depend on whether
there is a parenthesis after the distribution or not.

Cheers,

Junior


--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by zhuzixiang** [comment]
Thanks again:)
I closely follow your example volatilityOnly_expanded.dsge in Zhatao's tutorials 2 and write my code.
The first several parts seem run smoothly but the estimation parts go wrong:

*--------------------------------------------------------------*
*---------Estimation of volatilityOnly_zhu model-----------*
*--------------------------------------------------------------*
Error using levenbergMarquardt (line 16)
Objective function is returning undefined values at initial point. lsqnonlin cannot
continue.

Error in lsqncommon (line 162)
    [xC,FVAL,JACOB,EXITFLAG,OUTPUT,msgData] = ...

Error in lsqnonlin (line 237)
[xCurrent,Resnorm,FVAL,EXITFLAG,OUTPUT,LAMBDA,JACOB] = ...

Error in dsge/compute_steady_state>optimization_center (line 864)
    [ssc1,resnorm,~,exitflag]=lsqnonlin(objfun,ssc0,[],[],optimopt);

Error in dsge/compute_steady_state>divide_and_conquer (line 665)
        [z,retcode]=optimization_center(@small_system,z0,arg_zero_solver,optimopt);

Error in dsge/compute_steady_state>run_one_regime (line 426)
    [y,g,p,r,retcode]=divide_and_conquer(y0,g0,p,x,d,unsolved,dq_blocks);

Error in dsge/compute_steady_state (line 246)
        [y(:,istate),g(:,istate),r(:,istate),p(:,istate),retcode]=...

Error in dsge/solve/solve_zeroth_order (line 533)
            [obj,structural_matrices,retcode]=compute_steady_state(obj);

Error in dsge/solve (line 300)
retcode=solve_zeroth_order();

Error in likelihood_markov_switching_dsge (line 31)
[obj,retcode]=solve(obj);

Error in generic/log_posterior_kernel (line 53)
    [log_lik,Incr,retcode,obj]=likelihood_func(param,obj);

Error in generic/estimation_wrapper/fh_wrapper (line 154)
                [fval(mo),~,~,~,retcode,obj(mo)]=log_posterior_kernel(obj(mo),x);

Error in generic/estimation_wrapper (line 111)
        [f1,retcode_0,max_pen]=fh_wrapper(x0);

Error in generic/find_posterior_mode (line 44)
[x0(:,1),f0(1),~,retcode0,viol,obj,funevals]=estimation_wrapper(obj,[],x0(:,1),lb,ub,funevals);

Error in generic/estimate (line 283)
[x1,f1,H,x0,f0,viol,funevals,issue,obj]=find_posterior_mode(obj,x0,lb_short,ub_short);
%#ok<ASGLU>

Error in dsge/estimate (line 47)
    obj=estimate@generic_switch(obj,varargin{:});

Error in zhu (line 85)
    estim_models{imod}=estimate(estim_models{imod},'optimizer','fmincon');

**Here are the attached code and data:**
[Uploading china_1992Q2_2015Q4.zip…]()

Is it because my prior design inappropriate?

Best,
Zixiang Zhu

**Comment by jmaih** [comment]
I can't see your attachments...

--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)
