### ISSUE TITLE
Variance Decomposition

### ISSUE THREAD

**Issue by zhuzixiang** [jmaih/RISE_toolbox#48]
Dear Junior,
In Liu, Waggoner and Zha(2011)’s paper ,they distinguish V.D. for regime 1 and regime 2. But in your @generic switch V.D., there’s only one. Does it matter? Or how could I get different V.D. results for two regimes?
Thanks!
Best!
Zixiang Zhu

**Comment by jmaih** [comment]
Hi Zixiang,

You just option "vardec_ergodic" to false.

Cheers,

J.


--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)
