### ISSUE TITLE
Problem in simulating threshold-switching models

### ISSUE THREAD

**Issue by andrewsun90** [jmaih/RISE_toolbox#49]
Hi Junior,

Hope everything is going well.

Recently I have been using RISE to build Markov-switching models with endogenous probabilities, and I am particularly interested in the threshold-switching model, where the regime is determined by whether a variable takes a value above or below some threshold level. It seems that RISE can solve but cannot simulate such kind of models.

As an example, the endogenous probabilities in such models are
`! ocb_tp_1_2  = 1 - normcdf(var, 0, sigma)`
`! ocb_tp_2_1  = normcdf(var, 0, sigma)`

where `var` is just an endogenous or exogenous variable. Ideally, to build a threshold-switching model, the parameter `sigma` should approach zero. When I set a high value for `sigma` (e.g. 0.1), the model can be solved and be simulated. But when I set a low value for `sigma` (e.g. 0.01) the model can only be solved by cannot be simulated.

Initially I thought the problem was coming from the algorithm you used, so I wrote a Matlab code myself to solve and simulate a model with threshold switching using exactly the algorithm you introduced in Maih (2015). Fortunately, it worked even for very low values of `sigma` (e.g. 0.0001). But then I don't understand the reason why it doesn't work in RISE. Do you have any thoughts on where the problem is coming from? Also, could you tell me where to find the Matlab codes for algorithms MFI, MN and MNK in the toolbox? Thanks!

Best,
Zexi

**Comment by jmaih** [comment]
Hi Zexi,

Can you send me a copy of the model you are not able to simulate?

If you cannot post it directly to the forum, send it to me privately.

NB: I do not have extra time on hands right now. I am currently teaching an
intensive course and might not be able to get back to you swiftly.

Cheers,

J.

**Comment by andrewsun90** [comment]
Hey Junior,

Thanks so much for your reply!

I think I've found where the problem came from. Previously I defined two variables `prob12` and `prob21` to track endogenous probabilities. Then, in the threshold-switching case, the endogenous probabilities are specified as

`prob12 = 1 - normcdf(var, 0, sigma)`
`prob21 = normcdf(var, 0, sigma)`
`! ocb_tp_1_2 = prob12`
`! ocb_tp_2_1 = prob21`

It turned out that if I choose a very low value for `sigma` in such specification (e.g. 0.001) then the simulation does not work (Error message: `Problem in transition matrix`).

However, if I specify endogenous probabilities directly as

`! ocb_tp_1_2 = 1 - normcdf(var, 0, sigma)`
`! ocb_tp_2_1 = normcdf(var, 0, sigma)`

then even when the value of  `sigma` is very low, the model can be simulated!

I don't know exactly why this would happen, but I guess it might have something to with the approximation of the endogenous probabilities.

Finally, if possible, could you send me some course materials you used for other intensive courses from time to time? I wish to learn RISE more!


Many thanks,
Zexi
