### ISSUE TITLE
Solution algorithms while running the SW07 model with switch in the Taylor Rule parameters

### ISSUE THREAD

**Issue by angelaabbate** [jmaih/RISE_toolbox#5]
Hi, me again :)

I am working with the example of the Smets and Wouters 07 model, with switches in the Taylor rule coefficients, found in this subfolder examples/MarkovSwitching/SmetsWouters

After changing usmodel.rs by removing the linear attribute to the model block, I get the following error when running line 14 in howto.m

> Non-overloaded subscripting can produce only one result.
> Error in dsge_solver_first_order_autoregress_h (line 152)
>                 [Tz_pb,~,retcode]=options.solver(Gplus01,A0,Aminus,Q,T0);
> Error in solve_first_order (line 11)
> [Tz_pb,eigval,retcode,options]=dsge_solver_first_order_autoregress_h(dbf_plus,...
> Error in dsge_solver_h (line 66)
>     [T.Tz,others,eigval,retcode,obj.options]=solve_first_order(structural_matrices,...
> Error in dsge/solve (line 356)
>             [T,eigval,retcode,obj]=...
> Error in howto (line 13)
> sw=solve(sw,'solver','newton_kronecker_iteration'); 

It is a problem with the solver. Perhaps it just syntax. 
I have tried running
(1) sw=solve(sw)
(2) sw=solve(sw,'solver', 'mfi');

In both cases I get the following when looking at the model solution

MODEL HAS NOT BEEN SOLVED AT LEAST UP TO THE FIRST ORDER 

Any idea how to solve this? 

Since I am here, what is the syntax to solve at different orders?

Thanks in advance,

Angela

**Comment by jmaih** [comment]
Hi Angela,

The example has been updated. The solver that was listed no longer exists, it has been modified and renamed. 

Algorithm mfi that you tried to use is a functional iteration algorithm. It has its advantage in the sense that it is memory efficient and works reasonably fast when it does work even in the face of a large system. Its main drawback, however, is that it does not always find a solution.

Newton algorithms also have their problems but their main advantage is that they are locally stable around a solution and as a result, they converge more often than functional iteration for the same initial conditions.

Happy Easter,

Junior

**Comment by angelaabbate** [comment]
Thank you! Happy Easter to you too!
