### ISSUE TITLE
"Nans in Jacobian"

### ISSUE THREAD

**Issue by zhuzixiang** [jmaih/RISE_toolbox#50]
Dear Junior,
I wrote a modified model of LWZ(2013) and set two independent switching-regime for both structural parameters and volatility, but got the result,

dsge:: Exogenous Switching DSGE model in 4 regimes detected
dsge:: model has both backward and forward-looking components
*--------------------------------------------------------------*
*---------Estimation of SP_zhu9 model-----------*
*--------------------------------------------------------------*
Looking for good enough start values. Please wait...
  1 :: Nans in Jacobian
  2 :: Nans in Jacobian
  3 :: Nans in Jacobian
....
497 :: Nans in Jacobian
498 :: Nans in Jacobian
499 :: Nans in Jacobian
错误使用 generic/find_posterior_mode (line 78)
find_posterior_mode:: No admissible starting value after 500 trials

出错 generic/estimate (line 283)
[x1,f1,H,x0,f0,viol,funevals,issue,obj]=find_posterior_mode(obj,x0,lb_short,ub_short);
%#ok<ASGLU>

出错 dsge/estimate (line 47)
    obj=estimate@generic_switch(obj,varargin{:});

出错 SP_Only_zhu (line 103)
    estim_models{imod}=estimate(estim_models{imod},'optimizer','fmincon');

What's wrong with this? Are my initial value inappropriate?

[SP_zhu9.txt](https://github.com/jmaih/RISE_toolbox/files/970814/SP_zhu9.txt)

Another question is whether RISE have alternative optimization routine like 'csminwel' or 'fminsearch'?

Thank you!
Zixiang Zhu

**Comment by jmaih** [comment]
Hi Zixiang,

The parameters 'coef_tp_1_2'  and 'coef_tp_2_1' have not been assigned a
value.

Cheers,

Junior
