### ISSUE TITLE
On finding a solution to RS-DSGE with analytical steady state

### ISSUE THREAD

**Issue by mhardinga** [jmaih/RISE_toolbox#51]
Dear Junior,
I am working with a RS-DSGE model and using a steady state file where I have analytically computed the model’s steady states (the model has 2 steady states, determined by the switching parameters). However, RISE does not find a solution when using any of the algorithms for regime switching models. It only solves the model when using the “rise_1” algorithm. If I use any other algorithm, the “solve” function will run and the “solution” structure that RISE produces will have the “ss” structure containing the steady state values of all variables in both regimes; however, the “Tz” structure is not created.
The model files are attached. Do you have any idea on what could be causing the problem and possible ways to get around this?
Many thanks,
Martin
[cmr_model_rise.zip](https://github.com/jmaih/RISE_toolbox/files/978670/cmr_model_rise.zip)

**Comment by jmaih** [comment]
Hi Martin,

I could not replicate the problem with the current version of RISE.

I ran the following lines and got a result

m=rise('cmr_model_rise')
ms=solve(m,'steady_state_file','cmr_model_steadystate')
ms.print_solution

cheers,

Junior

**Comment by mhardinga** [comment]
Dear Junior,
many thanks, it was indeed an issue with my version of RISE. 
Cheers,
Martin

**Comment by jmaih** [comment]
Thanks for letting me know Martin.

Cheers,

J,
