### ISSUE TITLE
Different steady-state values for different regimes?

### ISSUE THREAD

**Issue by andrewsun90** [jmaih/RISE_toolbox#53]
Hi Junior,

Hope everything is going well with you.

Recently I encountered two problems in specifying steady-state values in the `steady_state_model` block, and I was wondering if you could help me with them.

1. I know how to specify different parameters values for different regimes in the `parameterization` block (e.g. `bind(zlb,1), 0;` and `bind(zlb,2), 0;`), but could I specify different steady-state values for different regimes in the `steady_state_model` block?

2. It seems that if I only specify the steady-state values for a subset of endogenous variables in the `steady_state_model`, then RISE will automatically set the steady-state values for the rest of endogenous variables to zero. Is that true?

Cheers,
Zexi

**Comment by jmaih** [comment]
Hi Zexi,

You write the steady state block as if the model was a constant-parameter model. RISE will call the block with the parameters of each regime and if a parameter is changed in the block, the changed value will be assigned to the corresponding regime and not to the others unless you impose the steady state in which case the value calculated will be assigned to all regimes. In brief you don't need to think about whether the model is switching or not when writing the steady state block. 

Your intuition concerning the values for the variables you do not declare is correct. RISE will try zero. This means you do not need to declare the variables for which the steady state is zero. 

Cheers

J.

**Comment by andrewsun90** [comment]
Got it! Thanks so much for your help Junior!


Best,
Zexi
