### ISSUE TITLE
error in 'simul_regime'

### ISSUE THREAD

**Issue by mhardinga** [jmaih/RISE_toolbox#54]
Hi Junior,

after updating to the last version of RISE, I started getting an error when using the 'simul_regime' option of the simulate command. Eg., in a 2 regime model, when running 

`mysims = simulate(m,'simul_periods',1000,'simul_regime',1)`

I get the following error:

`Index exceeds matrix dimensions.
Error in generic/simulate/set_transition_probabilities (line 309)
                bigq(iter,:)=squeeze(Qt(i_reg,j_reg,:));
Error in generic/simulate (line 249)
[all_Q,all_names_i_j,nshifts]=set_transition_probabilities();
Error in dsge/simulate (line 30)
[varargout{1:nargout}]=simulate@generic_switch(obj,varargin{:}); `

I'm not sure what is the reason for this.

Cheers,
Martin

**Comment by jmaih** [comment]
Hi Martin,

It is now possible to see the history of the transition probabilities both
for the regimes and for the states over the simulation horizon. There was a
small residual problem that is now fixed.

Let me know if there is any additional problem

Cheers,

Junior


--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by mhardinga** [comment]
Hi Junior,
yeah, I saw that now you can see the transition probabilities, that's great! The problem is now fixed, thanks!
Martin
