### ISSUE TITLE
MS-DSGE filtering

### ISSUE THREAD

**Issue by ksdffe** [jmaih/RISE_toolbox#55]
Hi,
I have estimated the Tao Zha Tutorial3. Everything worked fine except that the filtering did not work. At least, there is not information in the estim_models{1,1}.filtering section. Do I have to set it up somewhere? 
Best,
Karlo

**Comment by jmaih** [comment]
Hi Karlo,

I could not replicate the problem.

Cheers,

Junior

**Comment by ksdffe** [comment]
Thanks for your reply, Junior. This seems to be a Mac problem only. On a Windows machine everything works fine. 

One question still: where can I find the filtered variable/shock values, regime probabilities etc? Under "estim_models{1,x}.filtering.smoothed_shocks.EI", for example, I only find information about the variable name, its frequency, no. of obs., pages and variables as well as start and finish quarters.

**Comment by jmaih** [comment]
try

double(estim_models{1,x}.filtering.smoothed_shocks.EI)

Cheers,

Junior

**Comment by ksdffe** [comment]
Thank you!
