### ISSUE TITLE
Conditional Forecast based on several exogenous shocks

### ISSUE THREAD

**Issue by matthias1705** [jmaih/RISE_toolbox#56]
Hi

I am currently try to run a simulation based on prespecified exogenous shock series. I have found the oppurtunity to include one shock from another issue here. 

`db = initial_conditions(m, 1, 'steady', 1);
db.eps_a(1, 1, 1+1) = 10;
sim_result = simulate(m, 'simul_historical_data', db,'forecast_cond_exo_vars','eps_a');`

However is there an option to base the forecast at the same time on a prespecified series of two or more  exogenous shocks?

Thank you!

Best,
Matthias

**Comment by jmaih** [comment]
Hi Matthias,

sim_result = simulate(m, 'simul_historical_data',
db,'forecast_cond_exo_vars',{'eps_a','eps_b','eps_c'});

will do it.

cheers,

Junior

**Comment by matthias1705** [comment]
Thank you very much for your fast help!
