### ISSUE TITLE
Posterior mean

### ISSUE THREAD

**Issue by anettbor** [jmaih/RISE_toolbox#58]
Dear Junior,
I would like the estimation results to report the posterior mean instead of the mode, or possibly just get hold of the posterior means somehow. How can I make that happen?

Thank you, 
Anette

**Comment by jmaih** [comment]
Dear Anette,

As you may know there are two different aspects to estimation. One is
posterior maximization, the results of which gives (an estimation of) the
mode of the distribution. RISE displays the results of posterior
maximization.

The second aspect is posterior simulation where samples from the posterior
distribution are generated. These samples are either stored on disk or kept
in memory. There are different ways you can go about getting hold of the
draws but you would have to compute the quantities you are interested in
yourself.

If your simulations are in memory, typically they will be stored in a
structure whose one of the fields is called "pop". pop itself is going to
be a structure with fields f and x. f is the value of the log posterior and
x is for the parameter vectors. you can collect the parameter vectors as
x=[pop.x]; Then you can easily compute the mean M=mean(x,2)

Another easy way to get hold of the draws, is to construct an mcmc object.

obj= mcmc(pop,pnames)

But in this case pop is either the draws kept in memory as in the previous
case or the location of those draws where they are saved on disk. pnames
are the names of the estimated parameters

Now one of the fields of the mcmc object is called "draws". This will
collect all the draws in a matrix in which the rows are the different
parameters and the columns the various simulations. Then to get the mean
you can simply do M=mean(obj.draws,2).

Please let me know about the progress you make.

Cheers,

Junior

**Comment by anettbor** [comment]
Thank you for your quick response and the clarification. I followed your explanation in issue #10 to  simulate the posterior distribution. Have I understood it correctly, that it is the numbers now stored in 'Results.pop.x' I am to use to calculate the mean?

Thanks again,

Anette

**Comment by jmaih** [comment]
Anette:

Your intuition is exactly right!

Well done!

Cheers,

Junior

>

**Comment by anettbor** [comment]
Great, thank you!:) 

Anette
