### ISSUE TITLE
Error while simulating a model in "examples"

### ISSUE THREAD

**Issue by giannilmbd** [jmaih/RISE_toolbox#59]
Dear Junior,
working within RISE_toolbox-master/examples/Nonlinear3rdOrder/Binning
I've created the following howto.m file (along your examples)
`%% housekeeping
close all
clear
clc
%% add the necessary paths
rise_startup()
%% read the model and add the name of the steady state file
mwssf=rise('small_nk');

%% solve the model
mwssf=solve(mwssf,'simul_order',2,'simul_pruned',false);

%% SEE ALSO: NonlinearModels
% options={'simul_periods',500};
% ff=rise
% [db,states,retcode] = simulate(ff,'simul_periods',500)
[db,states,retcode] = simulate(mwssf,'simul_periods',500);
`
When I run it I get

> Index exceeds matrix dimensions.
Error in utils.forecast.one_step_engine (line 114)
        y01(:,iy)=y01(:,iy)+ifact(io)*T{io}*zkz;
Error in utils.forecast.one_step_fbs/multi_step_shooting (line 195)
            y1k(icol_)=utils.forecast.one_step_engine(T,y1k(icol_-1),ss,...
Error in utils.forecast.one_step_fbs (line 50)
[~,first_viol]=multi_step_shooting(shocks,true);
Error in utils.forecast.multi_step/condition_on_shocks_only/one_step (line 498)
            y1=utils.forecast.one_step_fbs(myorder{:});
Error in utils.forecast.multi_step/condition_on_shocks_only (line 394)
                        one_step();
Error in utils.forecast.multi_step (line 160)
    shocks__=condition_on_shocks_only(tmp);
Error in generic/simulate (line 175)
[y,states,retcode,Qt,myshocks]=utils.forecast.multi_step(y0(1),...
Error in dsge/simulate (line 30)
[varargout{1:nargout}]=simulate@generic_switch(obj,varargin{:}); 

Any idea what I'm doing wrong?
I'm trying to understand how to simulate a dsge to 3rd order (is fourth now available?)
Dynare++ gives me strange results (explodes even if shocks are zero all the time and start from steady state, although transition matrices are finite, ie don't multiply by inf etc.)
Best,
Gianni

**Comment by jmaih** [comment]
Hi Gianni,

Good to hear from you.


   1. Your howto file has some problems
      1. Let RISE know, WHILE RISING THE MODEL, that you will be
      needing/using higher-order SYMBOLIC derivatives :
      *m=rise('small_nk','max_deriv_order',3)*;
      2. or alternatively, if you have "rise-ned" the model without
      specifying the order of differentiation (which by default is 1), then you
      can change the type of derivatives from symbolic to automatic :
      *m=solve(m,'solve_derivatives_type','automatic')*
      3. If you do not do first order, then do not forget to explicitly
      specify the order at which you want to solve the model:
      *m=solve(m,'solve_order',3)* or with automatic derivatives
      *m=solve(m,'solve_order',3,'solve_derivatives_type','automatic')* .
      4. Although the model is solved say at order 3, you can decide that
      you want to simulate it at a lower order. That's when you can change the
      simul_order option : *db = simulate(m,'simul_order',2)*;.
   2. Because of the nature of the polynomial used in the approximation of
   the true solution, simulations produced using higher-orders of
   approximation will explode... if the order of approximation does not expand
   the region of stability enough for the simulations to live in for a given
   size of shocks.
   3. I guess this is why dynare++ explodes and if my intuition is correct,
   reducing the standard deviations of the shocks might lead to potentially
   more stable simulations.
      1. You have to keep reducing them until the simulations stop
      exploding.
      2. Alternatively you either have to increase the order of
      approximation until the stability region is sufficiently expanded or
      3. resort to cheating, sorry, pruning :).
   4. In theory, RISE can solve models up to fifth order but I still have
   to improve on efficiency especially because my main interest is with regime
   switching and in that respect some of the nice algorithms that can improve
   efficiency for constant-parameter models are not applicable.


 Cheers,

Junior

>

**Comment by giannilmbd** [comment]
Hi Junior,
Thanks!
I'll follow your suggestions.
Best
Gianni

**Comment by giannilmbd** [comment]
... a bit more.
In your file
aplanar.m
at line 846 I've added
            if ispc
                ss=memory;
                max_bytes=ss.MaxPossibleArrayBytes/8;
            else
                [~,out]=system('vmstat -s -S M | grep "free memory"');
                tmp=regexp(out,'[0-9]*','match');
                max_bytes=str2double(tmp{1})/8;
            end
(I have a Linux machine)
I still get error messages somewhere else... but still hoping :-)

**Comment by giannilmbd** [comment]
These lines of code crash on Matlab (2016b) Linux (Fedora)
`close all
clear
clc
%% add the necessary paths
rise_startup()
%% read the model and add the name of the steady state file
mwssf=rise('small_nk','max_deriv_order',3);

%% solve the model
mwssf=solve(mwssf,'solve_order',3,'simul_pruned',false,'solve_derivatives_type','automatic');`

with the error message

>Error using bsxfun
>Operands must be numeric arrays.
>Error in dsge_tools.evaluate_all_derivatives (line 215)
>                       bsxfun(@times,G01{io},zkz);%
>Error in dsge/solve (line 304)

>[structural_matrices,retcode]=dsge_tools.evaluate_all_derivatives(obj,structural_matrices);
>Error in howto (line 11)
>mwssf=solve(mwssf,'solve_order',3,'simul_pruned',false,'solve_derivatives_type','automatic');

**Comment by jmaih** [comment]
Hi Gianni,

I mostly use windows machines and occasionally macs. I have never used a
linux and unfortunately some of the codes I write might not work on such a
system.

All I can do for now is to keep my fingers crossed for you :)

Cheers,

Junior

>

**Comment by jmaih** [comment]
This is a modified version of your howto file. Could you, please, let me
know if you get some errors from running it?

-----------------------------------
%% housekeeping
close all
clear
clc

%% add the necessary paths
% rise_startup()

%% read the model

m=rise('small_nk','max_deriv_order',3);

%% solve the model
m=solve(m,'solve_order',2);

%% Simulate the model

[db,states,retcode] = simulate(m,'simul_periods',500,...
    'simul_order',2,'simul_pruned',false);

>
>

**Comment by giannilmbd** [comment]
Excellent. This seems to work fine.
Also, it occurred to my why dynare++ screws with zero shocks. There is this
bad habit to calibrate the varcov to the varcov matrix, without keeping
into account of the scaling (normalization) factor loading the innovations
onto the model (e.g. std_x*epsilon_x).
If I reduce std_x, still screws. If I reduce varco it doesn't.

Does RISE control for this issue?

Thanks
Best
Gianni

**Comment by jmaih** [comment]
1. RISE does not have variances and covariances. There is no shocks
   block like in dynare and there is no varcov matrix as in dynare++.
   2. All shocks are uncorrelated, have mean zero and standard deviation 1.
   3. The way then to generate non-unit variances is to scale the shocks by
   a constant, which ultimately is a parameter from RISE's viewpoint. That is,
   in all RISE models you will typically encounter expressions like
   std_x*epsilon_x
   4. Nothing prevents you for adding a common scaling factor
   common*std_1*epsilon_1, common*std_2*epsilon_2, ...,
   common*std_n*epsilon_n. In this way, you can scale all the shocks by the
   same amount simply by playing with parameter "common".

Cheers,

Junior

**Comment by giannilmbd** [comment]
Perfect. I find this representation preferable too.
Cheers
Gianni

**Comment by jmaih** [comment]
Should you want to scale the shocks or more generally change a parameter
value, I hope you know you can do that on the fly without having to re-rise
the model or modify the model file.

Cheers,

Junior

>

**Comment by giannilmbd** [comment]
Cool. No, I didn't know

**Comment by giannilmbd** [comment]
Thanks!
Oslo+January... well, might be worth :-)
Also, check out our visiting schemes for central bankers. We are having
many people from around the world for approx 3 months per visit!
Best
Gianni

**Comment by jmaih** [comment]
I would be glad to visit you Gianni.

I will try to remember to send you the call for papers for the conference.

All the very best,

Junior

>

**Comment by giannilmbd** [comment]
Thanks,
Gianni
