### ISSUE TITLE
Steady state specification

### ISSUE THREAD

**Issue by angelaabbate** [jmaih/RISE_toolbox#6]
Hi!

in RISE_toolbox-master/examples/MarkovSwitching/GavinKeenRichterThrockmorton/globdynzlb.rs

The steady state block has the (imposed) attribute: `steady_state_model(imposed)`

RISE does not like this attribute, so I have removed it. But then the program cannot find the steady state anymore

```
Error using dsge/compute_steady_state>prepare_steady_state_program (line 968)
With an initial guess for the steady state, the parameters cannot be modified in the steady state model or file
Error in dsge/compute_steady_state (line 129)
[obj,sscode,blocks,unsolved]=prepare_steady_state_program(obj);
Error in dsge/solve/solve_zeroth_order (line 593)
            [obj,structural_matrices,retcode]=compute_steady_state(obj);
Error in dsge/solve (line 312)
retcode=solve_zeroth_order(); 

```
Which syntax should we use at this stage?

Thanks!

Angela

**Comment by jmaih** [comment]
Hi Angela,

The example has been updated. Your intuition was exactly right, RISE no longer accepts attributes to model and steady_state_model blocks. Every option relating to those blocks has to be passed at execution time. Check the howto file associated with the example.

Best,

Junior

**Comment by mhardinga** [comment]
Hi Junior,

I get this same error message in a different context:

`Error using dsge/compute_steady_state>prepare_steady_state_program (line 1028)
With an initial guess for the steady state, the parameters cannot be modified in the steady state model or file
Error in dsge/compute_steady_state (line 129)
[obj,sscode,blocks,unsolved]=prepare_steady_state_program(obj);
Error in dsge/solve/solve_zeroth_order (line 551)
            [obj,structural_matrices,retcode]=compute_steady_state(obj);
Error in dsge/solve (line 340)
retcode=solve_zeroth_order(); `

I'm working with a steady state file and I want to set some of the parameters in that file. I haven't found an example that does this properly, and I wanted to ask you whether the logic is correct. Below is an extract of the code to set the parameter `LambdaYd`, where all other parameters in the RHS are defined in the `parameterization` block of the .rs file.

retcode=0;
if nargin==1
    % list of endogenous variables to be calculated
                               
    ss={'Rk','EtRk1','R','RL','s','rk','k_e','N','v','Q','inve','w','K','Ch','Y','F','sigmae','omega',...
        'PI','PIstar','PIstarw','g1','g2','f_l','mc','vp','vw','u','l','ld','wstar','phi','d','x','mu_z','mu_A','mu_I',...
        'U','Uc','eps_s_ke','Gamma','Gamma_1','Gamma_2','G','G_1','G_2','f','g','f_1','g_1',...
        'lambda_om','lambda_om_prime','z','psi','psi_prime','d_m_e'}; 
    

    % list of parameters to be computed during steady state calculation
    %-------------------------------------------------------------------
    newp={'LambdaYd'};
else
    % no parameters to update or create in the steady state file
    %-----------------------------------------------------------
    newp=[];
    % computation of the steady state
    %--------------------------------

    pp.LambdaYd = (pp.LambdaA+pp.ca*pp.Lambdamu)/(1-pp.ca);

Thank you in advance.
Martin

**Comment by jmaih** [comment]
Hi Martin,

1-) In that case you may want to set the option steady_state_imposed to true. 

2-) replace pp.LambdaYd with  newp.LambdaYd 

Cheers

**Comment by mhardinga** [comment]
Thanks Junior, that works just fine!
Martin
