### ISSUE TITLE
RISE has exploding shocks, Dynare has not

### ISSUE THREAD

**Issue by la8pw** [jmaih/RISE_toolbox#60]
Hi Junior! 

Hope that you're having a wonderful Wednesday!

I am attempting to implement the basic model of Iacoviello (2014, Review of Economic Dynamics) in RISE, but I am encountering some problems when it comes to obtaining IRFs with a 2nd order approximation. The shocks simply explode. However, Dynare returns non-explosive and nicely behaved output when faced with the same model setup, steady state, parameterisation and shock size. 

I was hoping that you could shed some light upon what might be going on here. I have attached the .rs-file and the .mod-file if you wish to take a look at it.

I run the following lines of code in MATLAB to initialise the model for RISE, solve and obtain IRFs:

```
model = rise('iacoviello');
model1 = solve(model,'solve_order',2,'solve_derivatives_type','automatic');
print_solution(model1);
irfs = irf(model1,'simul_order',2, 'irf_shock_sign',0.001,'irf_periods',40);

epsilon = values(irfs.iota.epsilon);
plot(epsilon(2:end))
xlim([1 40])
```

[iacoviello.zip](https://github.com/jmaih/RISE_toolbox/files/1318186/iacoviello.zip)

Best,

**Comment by jmaih** [comment]
My friend,

Simulations with higher order of approximations will explode with high
probability unless you apply pruning. By default RISE does not prune and so
you have to ask for it to get it.

Below is a revised version of your program, where I have set the
"simul_pruned" option to true

----------------
m0 = rise('iacoviello');
m1 = solve(m0,'solve_order',2,'solve_derivatives_type','automatic');
print_solution(m1);
irfs = irf(m1,'simul_order',2, 'irf_shock_sign',0.001,'irf_periods',40,...
    'simul_pruned',true);
epsilon = values(irfs.iota.epsilon);
plot(epsilon(2:end))
xlim([1 40])
----------------

Cheers,

Junior

>

**Comment by la8pw** [comment]
Hi again Junior,

Thank you very much for the explanation, although I was not aware that Dynare applied pruning by default. 

Best,
