### ISSUE TITLE
Question on estimation 

### ISSUE THREAD

**Issue by leonardabagnale** [jmaih/RISE_toolbox#62]
Hi Junior,

Just a simple question. I've seen that in the example files (Prof. Tau zha tutorials) there is an implementation using the parallel computing toolbox to estimate various models simultaneously. My question is, does RISE have a form to do the parallel computation in the estimation process just for one model (to do more efficient the procedure)? 
Many thanks in advance.

Leonard A.

**Comment by jmaih** [comment]
Hi Leo,

I am so sorry this issue fell through the cracks...

At the moment we do not have a parallelization set for the estimation of
one single model. Note however that the user can, if they wish, easily use
their own optimization algorithm instead of the ones used in RISE.

Cheers,

Junior

**Comment by leonardabagnale** [comment]
Thanks for your response, Junior!

regards,

Leonard.
