### ISSUE TITLE
Some errors with solve and vardecomposition

### ISSUE THREAD

**Issue by leonardabagnale** [jmaih/RISE_toolbox#65]
Hi Junior, 
I am using the latest RISE version, but some of the features of the previous one were affected and I cannot use these now.

1. For example, if I use the variance decomposition function [variance_decomposition(estimation)], I get the following error:

Reference to non-existent field 'solve_time_consistent_switch'.

Error in dsge_tools.evaluate_all_derivatives (line 13)
solve_time_consistent_switch=obj.options.solve_time_consistent_switch;

Error in dsge/solve (line 320)
    [structural_matrices,retcode]=dsge_tools.evaluate_all_derivatives(obj,structural_matrices);

Error in generic/variance_decomposition (line 84)
[obj,retcode]=solve(obj);
 
 2. If I try to solve a RISE model object, I get the following error:

Reference to non-existent field 'solve_time_consistent_switch'.

Error in dsge_tools.evaluate_all_derivatives (line 13)
solve_time_consistent_switch=obj.options.solve_time_consistent_switch;

Error in dsge/solve (line 320)
    [structural_matrices,retcode]=dsge_tools.evaluate_all_derivatives(obj,structural_matrices);

Error in generic/simulate (line 149)
[obj,retcode]=solve(obj,varargin{:});

Error in dsge/simulate (line 30)
[varargout{1:nargout}]=simulate@generic(obj,varargin{:});

Error in generic/forecast (line 148)
cond_fkst_db=simulate(obj);

The previous errors didn't appear in the previous version of RISE. Do you have any idea of what would have happened?

Thanks in advance.

Regards,
Leonard A.

**Comment by jmaih** [comment]
Hi Leo,

Are you trying to run solve and variance decomposition on a model object that was constructed using an old version of RISE?

J.

**Comment by leonardabagnale** [comment]
Hi Junior,

Yes, I am using model object obtained with an old version of RISE. Do I have to re-estimate the model with the latest version to use the new solve and variance decomposition functions or this object does still usable?

regards,
L.A.

**Comment by jmaih** [comment]
Hi Leo,

You don’t need to re-estimate. 

Before doing anything try doing 

m=refresh(m)

If that doesn’t work then the object might be too old. In that case you should still be able to extract the estimated parameters and use them in your simulations. 

p=get(m_old,’parameters’)

m=rise(modelFile)

m=set(m,’parameters’,p)

Where m_old is the old model object and m the new one. 

Cheers 

Junior

**Comment by leonardabagnale** [comment]
Many thanks for your response Junior. It works with the refresh function. 

Leonard
