### ISSUE TITLE
How many regimes does the Markov Switching DSGE estimation support?

### ISSUE THREAD

**Issue by laserahao** [jmaih/RISE_toolbox#66]
Hi Junior,

I'm using the latest RISE toolbox to estimate the Linde (2005, JME) DSGE model with Markov Switching parameters, which is very similar to the estimation in the RISE folder "examples\VariousModels\TaoZha\Tutorials\DSGE\Tutorial2". 

My concern is that I'm estimating a Markov chain with 3 regimes, but the example has 2 regimes only. My estimation with 2 regimes looks fine, but the estimation with 3 regimes looks erroneous. The estimated probabilities of each state are flat, with one state always having almost probability 1, and others 0. The prior distributions for the 2-state and 3-state models are the same, so I don't think adding a state should change the filtered probabilities too much.

Question: Is RISE able to estimate Markov Switching Linear Rational Expectations models with 3 states or more? 

Thank you,

Zehao Li

**Comment by jmaih** [comment]
Zehao,

The simple answer to your question is yes. It is possible to estimate
models with 3 states or more.

There are several considerations though:

   1. the computational burden increases.
   2. the number of optima potentially increases, sometimes making it hard
   for simple optimization routines to find a satisfactory mode
   3. it is not just about having a big number of states, it is about
   thinking hard about how identification is going to occur
   4. it is not just about having a big number of states, it is ultimately
   about how those states are going to be interpreted
   5. freely estimating parameters will not necessarily give you the type
   of results you expect. If you have good priors, it often eases the
   estimation burden.


Cheers,

Junior

**Comment by laserahao** [comment]
Thank you, Junior. 

One more question about the identification.
In the example, the states are identified by ranking the values of a coefficient in each state. Is it also what we do with more states? Are there any other ways to achieve identification?

Zehao

**Comment by jmaih** [comment]
Zehao,

The states ARE NOT identified by ranking the values of the coefficients in each state. 

The question to answer is what restrictions and what information in the model and in the data will help the procedure identify the observation, say,  1970Q1 as a state of high inflation. 

Again, It is more than just running an estimation and expecting that the regimes will identify themselves and tell you what happened. 

Cheers 

J.

**Comment by laserahao** [comment]
Thank you for all the prompt and detailed answers.

Zehao Li

2017-11-22 21:53 GMT-06:00 Junior Maih <notifications@github.com>:

> Zehao,
>
> The states ARE NOT identified by ranking the values of the coefficients in
> each state.
>
> The question to answer is what restrictions and what information in the
> model and in the data will help the procedure identify the observation,
> say, 1970Q1 as a state of high inflation.
>
> Again, It is more than just running an estimation and expecting that the
> regimes will identify themselves and tell you what happened.
>
> Cheers
>
> J.
>
