### ISSUE TITLE
Plot: Variance Decomp and H shocks

### ISSUE THREAD

**Issue by leonardabagnale** [jmaih/RISE_toolbox#67]
Hi Junior,

Does RISE have a function to generate(automatically) a plot for the historical shocks and variance decomposition?
I've already checked the examples but may I am missing something.

Regards,

Leonard

**Comment by leonardabagnale** [comment]
Hi again Junior, 
I already found the  plot_decomp function to do the plot. But I don't know very well the algorithm to calculate the approximation of the historical decomposition (switch appear on it), so and I want to figure out which formulas correspond to the algorithm. 
So I wonder If you can help me to clarify this topic.

Many thanks in advance.

L

**Comment by jmaih** [comment]
Hi Leo,

The decomposition with regime switching is not exact because the process is
nonlinear. The approximation considered gives a role to the fact that the
process may switch over time and therefore the variable with name "switch"
tries to account for that fact.

Cheers,

J.
