### ISSUE TITLE
Differences between hd and historical_decomposition functions

### ISSUE THREAD

**Issue by cjrodriguez453** [jmaih/RISE_toolbox#69]
Hi again, Junior

Exploring the toolbox, I found out that there are two functions to get the historical decompositions: "hd" and "historical_decompositions". Even though I didn't look very deep into both functions, I get different results depending on when I use one or other. 
For "hd", I get the historical decomposition in terms of: Y0, switch and the shocks of the model. 
For "historical_decomposition", I get the historical decomposition in terms of: Y0, ss, SIG and the shocks of the model, but there is no switch component included.

Is it appropriate to use just one of them, or it depends on the model that I use?

Thanks.

Carlos

**Comment by jmaih** [comment]
Hi Carlos,

The problem of decomposition in a nonlinear model is not defined. A regime
switching model is de facto a nonlinear model and all one can do is
approximations if one insists in doing decompositions. The two functions
you are referring to would yield the same results in a constant parameter
linear model. In a regime switching context they make two different
assumptions about how to take the decomposition. "hd" is the most recent
one.

cheers,

Junior

**Comment by cjrodriguez453** [comment]
Many thanks for your response Junior.
Do you recommend any source (or literature) to get in the details of these assumptions to construct the decomposition (additional to the functions)? I would like to understand a little bit more about this topic. 

Regards,
Carlos

**Comment by jmaih** [comment]
The problem, as I said earlier, is not defined and not surprisingly there
is, to the best of my knowledge, no literature on the subject.

**Comment by cjrodriguez453** [comment]
Many thanks for your response.

Regards,

Carlos
