### ISSUE TITLE
Time-Varying Transition Probabilities BVAR

### ISSUE THREAD

**Issue by matthias1705** [jmaih/RISE_toolbox#70]
Hi Junior,

Thank you very much for organising the course and conference in Oslo. It was really great and I learned a lot. 

I am using RISE to estimate a MS-BVAR based on the files that you distributed in the course. The examples that you discussed only applied constant transition probabilities for the Markov Chains. However, I would like to use a time-varying transition probabilities for the BVAR. For instance, I would like that the switching probability depends on output:
syncoef_tp_1_2 = exp(gamma1*y)/(1+ gamma1*y )
syncoef_tp_2_1 = 1/(1+ gamma2*y )
where gamma1 and gamma2 are parameters and y is output.

How can I integrate this in RISE? Do you have a related maybe example?

Thanks a lot!

Best,
Matthias

**Comment by jmaih** [comment]
Hi Matthias,

It was fun to teach the course.

Here is the syntax to follow:

% markov chain creation
%----------------------
mc=struct();
mc.endogenous_probabilities={
    'syncvol_tp_1_2=1/(1+exp(a12-b12*S))'
    'syncvol_tp_2_1=a21'
    };
mc.probability_parameters={'a12','b12','a21'};
mc.controlled_parameters={'s'};

% setting priors for the parameters affecting the endogenous probabilities
%-------------------------------------------------------------------------
switch_prior=struct();
switch_prior.a12={0.1,0,5,'normal'};
switch_prior.b12={0.1,2,5,'gamma'};
switch_prior.a21={0.2,0.2,0.2,'beta'};
priors=struct();
priors.nonvar=switch_prior;
% setting priors for the VAR parameters
%--------------------------------------
priors.var=svar.prior_template();
priors.var.type='sz';

% creating the svar
%------------------
sv=svar(varlist,{},4,true,[],mc);

% Finding the posterior mode
%---------------------------
restrictions=[]; % restrictions if any
sv=estimate(sv,data,date_range,priors,restrictions);

Cheers,

Junior

>

**Comment by matthias1705** [comment]
Hi Junior,

please apologize the late response. Thank you so much for sending the code!

Best,
Matthias
