### ISSUE TITLE
dirichlet parameterization

### ISSUE THREAD

**Issue by leonardabagnale** [jmaih/RISE_toolbox#71]
Hi Junior,

A quick question:
I want to include a parametrization for the transition probabilities of a four states markov chains in a dsge model.
For this case, as I know, I cannot use the beta distribution. How can I introduce the parameterization of the Dirichlet distribution, since RISE does not recognize it in the standard way(as the other distributions).

Thank you in Advance.

Leonard

**Comment by jmaih** [comment]
Hi Leo,

The syntax for the dirichlet in RISE is the following

	dirichlet_1,0.1,mj_tp_1_2,0.0294,mj_tp_1_3,0.0294;

	dirichlet_2,0.03,mj_tp_2_1,0.0053,mj_tp_2_3,0.0054;

	dirichlet_3,0.1,mj_tp_3_1,0.0271,mj_tp_3_2,0.0262;

Here I have three groups of parameters that are jointly dirichlet. I write "dirichlet_1" for the first group, "dirichlet_2" for the second group,..., "dirichlet_n" for the nth group

- after each parameter name is the mean of the corresponding parameter
- right after dirichlet_j is the standard deviation of the diagonal element (a parameter never listed by RISE) of the dirichlet distribution.

Cheers,

Junior

**Comment by leonardabagnale** [comment]
Works!
Thank you, Junior.

Regards,
Leonardo.

**Comment by leonardabagnale** [comment]
Hi again Junior,

Another question about this matter.
After a RISE estimation of the model with the dirichlet distribution in the transition probabilities, I get the following error when I request the results of the estimation (i.e print_estimation_results(estimation):

```
Error using fieldnames
Invalid input argument of type 'double'. Input must be a structure or a Java or COM object.
Error in save_filters (line 23)
Fields=fieldnames(obj.filtering);
Error in dsge/conclude_estimation (line 36)
    obj=save_filters(obj);
Error in generic/estimate (line 373)
    [log_post,log_lik,log_prior,~,~,obj(ii),xmode]=conclude_estimation(obj(ii),x1);
Error in dsge/estimate (line 47)
    obj=estimate@generic(obj,varargin{:}); 
```

I think this problem is related to the introduction of the Dirichlet distribution. Otherwise, for example, If I use incorrectly the beta distribution, the results are reported in the standard way. Maybe I am wrong. Do you have an idea of how to correct this?

thanks,

Leo

**Comment by jmaih** [comment]
Hi Leo,

This seems unrelated to the dirichlet distribution. It happens at the moment estimation attempts to conclude. Something happens when the filters are being saved.

Would it be possible for you to send me your files so that I can investigate the issue more closely?

J.

**Comment by leonardabagnale** [comment]
Hi Junior,

I already sent you the files by email.

Leo

**Comment by jmaih** [comment]
Hi Leo,

I will take a look and get back to you. 

Cheers,

Junior
