### ISSUE TITLE
Problems when RISING the model

### ISSUE THREAD

**Issue by JB93** [jmaih/RISE_toolbox#73]
Hi Junior,

First and foremost thank you for the course at BI i January.

I am writing my master thesis at the moment, where I am using Iacoviello and Neri (2010).

I have coded the model up myself - not log-linearized it - but I am not sure how to understand the following error message, when RISING the model:

Error using utils.code.code2func>@(x)str2func([main_string,x]) (line 74)
Error: ()-indexing must appear last in an index expression.

Error in utils.code.code2func (line 74)
func=cellfun(@(x)str2func([main_string,x]),code,'uniformOutput',false);

Error in parser.parse (line 418)
routines.dynamic=utils.code.code2func(dynamic.shadow_model);

Error in dsge (line 320)
            dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});

Can you possibly tell, what I am doing wrong?

The dropbox link should be available here: https://www.dropbox.com/s/tgknsd9wygo0c7b/IN2010_CP.rs?dl=0

Best,

Jeppe Bro

**Comment by jmaih** [comment]
Hi Jeppe,

Do you have the possibility of sending me your model at my private email
address so that I can take a look? I do not understand the error message.

Cheers,

Junior

**Comment by JB93** [comment]
Thank you. I have sent you an email.

**Comment by jmaih** [comment]
And I have replied to your email.

Cheers,

J.
