### ISSUE TITLE
Two chains for coefficients in VAR model

### ISSUE THREAD

**Issue by C1587S** [jmaih/RISE_toolbox#74]
Hi Junior,

I want to introduce, say two independent Markov-chains for coefficients in two different equations. 
I use the following syntax:
```
markov_chains=struct('name','chain_1',...
    'number_of_states',2,...
    'controlled_parameters',{{'c(1)','a1(1)','a2(1)'}},...
    'endogenous_probabilities',[],...
    'probability_parameters',[]);
markov_chains(2)=struct('name','chain_2',...
    'number_of_states',2,...
    'controlled_parameters',{{'c(2)','a1(2)','a2(2)'}},...
    'endogenous_probabilities',[],...
    'probability_parameters',[]);
```
Then, I create the VAR model....
But, to set up the restrictions, I'm not sure about the syntax for the respective chain "chain_i" in the line:

`which_chain=strcmp('chain_i',{markov_chains.name});`

What is the right way to introduce both chains?

Thank you in advance,

S.

**Comment by jmaih** [comment]
Hi S,

I do not understand the statement " which_chain=strcmp('chain_i',{
markov_chains.name}); "

You can set restrictions as follows

a1(2,1,chain_2,1)>= a1(2,1,chain_2,2)

Here I am saying that the value of the parameter in state 1 must be greater
than its value in state 2.

Cheers,

Junior

**Comment by C1587S** [comment]
Junior,
Thanks for your clarification. 

Best regards,

S.
