### ISSUE TITLE
Matlab 2017a

### ISSUE THREAD

**Issue by AnasZa** [jmaih/RISE_toolbox#75]
Hi Junior,

I switched to Matlab2017a and there is an error popping up when estimating a model in my code as well as in the examples (like for example the one of Smets and Wouters). Here is the error:  

 `Undefined function 'betacdf' for input arguments of type 'double'.

Error in distributions.beta>cumulative_density_function (line 198)
cdf=betacdf((theta-c)./d,a,b);

Error in distributions.hyperparameter_residuals (line 26)
resid=[cdfn(plb,a,b,varargin{:})-.5*alpha;

Error in distributions.find_hyperparameters/rich_man (line 113)
        fval=objective(x,cdfn,plb,pub,prob,callingfunc,varargin{:});

Error in lsqnonlin (line 196)
            initVals.F = feval(funfcn{3},xCurrent,varargin{:});

Error in distributions.find_hyperparameters (line 59)
    [ab,fval,~,exitflag]=lsqnonlin(@rich_man,x0(:,iter),lb,ub,options,'lsqnonlin');

Error in distributions.beta (line 82)
        [ab,fval,retcode]=distributions.find_hyperparameters(space,cdfn,lowerquantileORmean,upperquantileORstdev,prob,c,d);

Error in utils.prior.prior_setting_engine (line 51)
[parray.a,parray.b,moments,ffinal]=distributions.(parray.prior_distrib)(lqtl_mean,uqtl_std,parray.prior_prob);

Error in generic/setup_priors/do_one_typical (line 251)
        priors=utils.prior.prior_setting_engine(priors,block,est_id,prior_trunc);

Error in generic/setup_priors (line 157)
        do_one_typical()

Error in format_parameters (line 53)
obj=setup_priors(obj,ParameterizationArray.Priors,ParameterizationArray.error_control);

Error in dsge (line 395)
            obj=format_parameters(obj,dictionary.Parameterization_block);

Error in rise (line 64)
            obj=obj@dsge(varargin{:});

Error in howto (line 16)
sw=rise('usmodel','data',data,...

Caused by:
    Failure in initial objective function evaluation. LSQNONLIN cannot continue.`

Could you help me please?

**Comment by jmaih** [comment]
Hi,

I can't see the error.

**Comment by AnasZa** [comment]
Thank you for yor fast reply.

I think the metter is in the machine then. When I typre"help betacdf" in the machine with matlab 2017a, I have 
" 
>> help betacdf
--- help for splanar/betacdf ---

  betacdf - overloads betacdf for splanar

    Other functions named betacdf

       distributed/betacdf

       distributed/betacdf

 betacdf  Beta cumulative distribution function.
    P = betacdf(X,A,B)
    P = betacdf(X,A,B,'upper')
 
    See also betacdf, distributed.
"

**Comment by jmaih** [comment]
I still don't understand what you are talking about.

Could you at least point me to the example that you are trying to run?

**Comment by AnasZa** [comment]
Sure,
As I mentioned for as example when running ...RISE_toolbox-master\examples\VariousModels\SmetsWouters, the rerror pops up:
``

**Comment by jmaih** [comment]
It runs perfectly fine on my machine, I can't replicate whatever problem
you had.

**Comment by AnasZa** [comment]
Thanks. The issue solved. It was a bug on my computer.

**Comment by jmaih** [comment]
Thanks for letting me know. 

Cheers,

J.
