### ISSUE TITLE
MSVAR questions

### ISSUE THREAD

**Issue by C1587S** [jmaih/RISE_toolbox#77]
Hi Junior,

I hope everything is going great. 
I have two question about the MSVAR estimation procedure.

1. To estimate any model, the default optimization procedure is "fmincon", am I right? I'm trying to use the blockwise algorithm, just adding to the "estimate" function, the option <'optimizer','blockwise_optimization'>, but it seems that the estimation procedure keeps using "fmincon". This is the proper way to do this?
2. I want to compute the MDD to compare various models. As an example, I was looking the old examples of professor Zha, already deprecated (\GitHub\RISE_toolbox\examples\VariousModels\TaoZha\Tutorials\SVAR\+deprecated). But, when I run:

`[objective,lb,ub,x0,SIG]=pull_objective(mest);

ndraws_mcmc         = 1500;  % number of parameter draws through MCMC.
ndraws_burnin       = floor(0.1*ndraws_mcmc); % number of parameter draws to be burned
mcmc_options=struct('burnin',ndraws_burnin,'N',ndraws_mcmc,'thin',1);

Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG);`

I get the following error:

`Undefined function 'pull_objective' for input arguments of type 'svar'` 

Do you know what is the updated form to do this?

Thank you in advance.

Best regards,

S.

**Comment by jmaih** [comment]
Hi S.

The VAR routines are currently under upgrade and that is the reason why the
deprecated files are still there. They are scheduled for removal as soon as
I am done updating the new routines.

The current limitations, as you've rightly realized, are that it is not
possible at the moment to use a different optimization algorithm than
fmincon and the MCMC and MDD are currently not working.

I hope to find time to update the routines soon. In the meantime you would
have to make do with an analysis conducted at the mode.

Sorry for the inconvenience,

J.

**Comment by C1587S** [comment]
Thanks for your response Junior.

Best,

Sebastián
