### ISSUE TITLE
RS-DSGE estimation: filtered, updated and smoothed variables

### ISSUE THREAD

**Issue by mhardinga** [jmaih/RISE_toolbox#78]
Hi Junior,

Regarding RS-DSGE model estimation, in particular the output that is stored in the structure "filtering" after estimation, is the terminology as in the Dynare output? I.e., is it correct that filtered_variables are one step ahead forecast (t+1) for the endogenous variables given information up to time t; updated_variables are the best guess for the endogenous variables at t given information up to time t; and smoothed_variables are best guess for the endogenous variables given all available information? 

Regarding the “Expected” concepts of the "filtering" output, what is the relation between the smoothed_state_probabilities, updated_state_probabilities and filtered_state_probabilities and the Expected_smoothed, Expected_updated and Expected_filtered variables?  

Many thanks!

Cheers,
Martin

**Comment by jmaih** [comment]
Hi Martin,

Your intuition is exactly right:
1- filtered_variables refer to one-step ahead forecasts: a_{t|t-1}
2- updated_variables refer to the updates a_{t|t}
3- smoothed_variables refer to the final estimates conditional on all
available information a_t{t|n}

As for the expected counterparts, they are averages across all regimes.
This means that in a regime switching model, you will have for every
variable, as many series as the number of regimes. The weights used to
compute those averages are the probabilities.

Cheers,

J.

**Comment by jmaih** [comment]
Correct!!!
