### ISSUE TITLE
Confidence bands for IRF's 

### ISSUE THREAD

**Issue by scekin** [jmaih/RISE_toolbox#8]
Hi Junior,

I couldn't find a built-in function in RISE to generate confidence bands for IRF's in estimated models. Am I missing it or is this something that has not been incorporated yet into RISE?

Many thanks in advance,

Semih

**Comment by jmaih** [comment]
Hi Semih,
There is no such a function. One has to loop around the irf method several times to construct the desired confidence bands. At each step, the parameters are changed and a new set of irfs is recomputed. Doing it several times, one can construct confidence bands.

**Comment by scekin** [comment]
Thank you very much for your response Junior!

Semih

**Comment by jmaih** [comment]
You are most welcome Semih

Best,

Junior
