### ISSUE TITLE
Bayesian estimation results

### ISSUE THREAD

**Issue by AnasZa** [jmaih/RISE_toolbox#80]
Dear Junior,

I have a question about Bayesian estimation results. Say, I run 
**_Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG);_**

Now, I would like to look at the transitional probabilities or historical decompositions using sim-mode, or mean of the posterior distribution. How can I implement it? 

Is there a way to create an object like **_m = ?(model_m, Results.pop)_**, where **_model_m = estimate( rise(model), 'optimizer','fmincon')_**, so that I could treat object **_m_** as **_model_m_**?

And another question : how can I plot transitional probabilities with error bands?

Thank you!

**Comment by jmaih** [comment]
Dear Aaz,


   1. You should not try to look at the properties of the model using the
   mean of the posterior distribution. The mean of the posterior distribution,
   which would be approximated by the average  of the parameter sampled may
   not be a valid parameter vector in the sense that there is no guarantee
   that the model will solve for that particular parameter vector
   2. There is a function whose syntax
   is [draw,m1]=draw_parameter(m0,simulation_folder) that can help in what you
   are trying to do. Check out help dsge/draw_parameter . "m0" is the model
   object and "m1" is a new parameterized model object, parameterized with
   "draw".  " simulation_folder " is either the folder in which the
   simulations are stored or the content of "Results.pop".
   3. You can then go ahead and write a loop over  [~,m1]=draw_parameter(m0,
   Results.pop),. Inside the loop, at each iteration, you collect m1 and do
   whatever you want to do with it and store the results.
   4. It is then the concatenation of results from multiple draws that you
   will use to plot error bands, etc.

Cheers,

J.

**Comment by jmaih** [comment]
Dear Aaz,

1.  m1 is not the same as m0. m1 is parameterized with a new parameter vector drawn from Results.pop. You can check this in two ways.  First, check isequal(m0,m1), secondly run the operation m2=set(m0,'parameters',draw) and then check isequal(m1,m2)

1. In order to push in the parameters of a particular vector from the draws, you need to locate the structure containing the parameter vector. Do the following:  f=[Results.pop.f]; best=f==min(f);  [~,m1]=draw_parameter(m0,Results.pop(best));

Cheers,

J.

**Comment by AnasZa** [comment]
Thank you very much, Junior!
And the last thing that bothers me is that filtering structures that contains predicted, updated and smoothed series of the models are the same for **m1** and **m0**. I guess if I run **filter(m1)**, then I will update the **smoothed_state_probabilities** conditional of the new parameter set (=Results.pop(best)). Right? Are there any options to care about when running this function?

**Comment by Kairey** [comment]
Hi Maih,
    I am confused with some fundamental issues.
    1. Does the command m=estimate(m) depend on Maximum likelihood estimation(MLE)?
    2. About Bayesian estimation. If I wanna do some further analysis (such as IRFs) based on the Bayesian post-mean,  After running Results=mh_sampler(objective,lb,ub,mcmc_options,x0,SIG), what specific commonds should I run by turn?
    3.  Since many important commonds based on specific RISE object, such as irfs=irf(m), histdec=historical_decomposition(m). If I wanna do the same analysis based on Bayesian estimation, should I create an new object (new_m) after running Results=mh_sampler(..), and then just running irfs=irf(new_m), histdec=historical_decomposition(new_m)? How to create the new object (new_m)?
    Best,
    Kairey
