### ISSUE TITLE
Problem "Rising" models

### ISSUE THREAD

**Issue by C1587S** [jmaih/RISE_toolbox#81]
Hi Junior,

I'm using the last version of RISE, but after the update,  an error is appearing just after attempt to "rise" any model -m = rise('model')-:

```
Error using rise/Contents
Attempt to execute SCRIPT Contents as a function:
...\GitHub\RISE_toolbox\classes\models\@rise\Contents.m
Error in generic/set/set_all_options (line 443)
            this_options=dum_obj.(method_list{imeth});
Error in generic/set (line 136)
    set_all_options()
Error in dsge/set (line 133)
obj=set@generic(obj,varargin{:});
Error in dsge (line 368)
            obj=set(obj,varargin{:});
Error in rise (line 64)
            obj=obj@dsge(varargin{:}); 
```

Regards,

S.

**Comment by sehyoun** [comment]
I probably introduced that error. Let me track it down.

**Comment by sehyoun** [comment]
It wasn't from me actually, but it should be fixed now. I just made an update; could you check if that resolves your problem?

**Comment by C1587S** [comment]
Hi SeHyoun,
Problem solved. Thanks

Regards,
S.

**Comment by C1587S** [comment]
Hi again,
I am re-opening this issue because a new problem appears when trying to "rise" any model-m = rise('model')-, which is the following:
`Error using horzcat
Dimensions of matrices being concatenated are not consistent.
Error in parser.build_markov_regimes/update_markov_chains_info_add_regimes (line 191)
            reg_info.regime_names(:),num2cell(tmp)
Error in parser.build_markov_regimes (line 64)
    [markov_chain_info,Journal_check]=update_markov_chains_info_add_regimes(...
Error in parser.transition_probabilities (line 135)
[~,markov_chain_info,myifelseif]=parser.build_markov_regimes(transition_matrix_symbolic,markov_chains);
Error in parser.parse (line 521)
    ]=parser.transition_probabilities(...
Error in dsge (line 318)
            dictionary=parser.parse(model_filename,cmfArgins{:});
Error in rise (line 64)
            obj=obj@dsge(varargin{:});`

Thanks in advance.
Regards,

S.

**Comment by jmaih** [comment]
Please try again.

J.

**Comment by C1587S** [comment]
It works now.
Thanks, Junior.

S.

**Comment by C1587S** [comment]
Hi Junior, 
I'm using the last version of RISE, but trying to run any example (m=rise('anymodel')), the following error shows up:

`Error using horzcat
Dimensions of matrices being concatenated are not consistent.

Error in parser.build_markov_regimes/update_markov_chains_info_add_regimes (line 191)
            reg_info.regime_names(:),num2cell(tmp)

Error in parser.build_markov_regimes (line 64)
    [markov_chain_info,Journal_check]=update_markov_chains_info_add_regimes(...

Error in parser.transition_probabilities (line 135)
[~,markov_chain_info,myifelseif]=parser.build_markov_regimes(transition_matrix_symbolic,markov_chains);

Error in parser.parse (line 521)
    ]=parser.transition_probabilities(...

Error in dsge (line 318)
            dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});`


regards, 

S.

**Comment by jmaih** [comment]
>
> Dear SC187,


I am not able to replicate the problem. Could you point to an example where
the problem occurs?

Thanks,

Junior

**Comment by anettbor** [comment]
Hi,
using the latest version of RISE , and trying to run any example (m=rise('anymodel')), the following error shows up:

 Error using parser.file2blocks
Error: File: file2blocks.m Line: 733 Column: 1
Function definitions in a script must appear at the end of the file.
Move all statements after the "construct_list" function definition to before the first local function definition.

Error in parser.parse (line 241)
[blocks,dictionary.markov_chains]=parser.file2blocks(RawFile);

Error in dsge (line 334)
            dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});

Is anyone else experiencing the same error, or is it perhaps because I use Matlab R2017a? 

Best,
Anette

**Comment by jmaih** [comment]
Could you please email me the programs you are trying to run?

Cheers,

J.

**Comment by anettbor** [comment]
I get the same issue when running the howto.m-files in /examples/VariousModels/TaoZha/Tutorials/DSGE/Tutorial1 and Tutorial2, in addition to VariousModels/SmetsWouters. So I don't think it matters which programs I try to run.. 
If you don't get the same error, I'll try to update to the latest matlab version.

thanks,
Anette

**Comment by jmaih** [comment]
Let me know if you encounter further problems. 

Cheers,

J. 

Sendt fra min iPhone
