### ISSUE TITLE
rrf_sampler

### ISSUE THREAD

**Issue by AnasZa** [jmaih/RISE_toolbox#82]
Dear Junior,

I would like to compare the posterior distribution obtained with mh_sampler with the rrf_sampler.
However after running **Results=rrf_sampler(objective,lb,ub,options,best(1).x,Sig);**  I got an error message: 

```
Error using utils.mcmc.initial_draws (line 89)
no valid parameter after 50 attempts
Error in rrf_sampler (line 208)
[genpop,funevals,log_I_old,~,NumWorkers]=utils.mcmc.initial_draws(logf,lb,ub,N,penalty,mu); 
```
What may it mean? is it about my hessian matrix Sig? but it is the same I used for mh_sample which is important because as far as I understood the initial draws for rrf_sampler are computed as in MH algorithm. 

Please let me know if you have an idea how to debug it. 

Cheers,

**Comment by sehyoun** [comment]
Dear AnasZa,

 Junior can answer better, but mh_sampler and rrf_sampler have different option sets and different default option values. It would expedite things if you could provide the option settings that you are using.

 Alternately, you can also try setting 

options.penalty = 1e+8;

and try rrf_sampler again. I presume that's the main difference in this case.

**Comment by jmaih** [comment]
Dear Aaz,

If you don't make any progress after SeHyoun's suggestion, please save and
send me your estimated model object.

Cheers,

J.
