### ISSUE TITLE
Filter to compute likelihood

### ISSUE THREAD

**Issue by anettbor** [jmaih/RISE_toolbox#83]
Dear Junior,
When estimating a regime-switching DSGE model in RISE, what filtering algorithm is used to compute the likelihood? 

Thanks,
Anette

**Comment by jmaih** [comment]
Dear Anette,

The filtering algorithm in the first-order perturbation or linear case is a
modification of the Kim and Nelson (1999) filter. RISE uses a different
collapsing rule, which saves some computation and produces the same results
as the KN filter.

Cheers,

J.

**Comment by anettbor** [comment]
Of course, now I remember being told this at the BI-course in January. Instead of checking my notes however, I managed to get lost in your codes. 
Thanks for clarifying!

Anette
