### ISSUE TITLE
filtered and smoothed endogenous regime probabilities

### ISSUE THREAD

**Issue by mhardinga** [jmaih/RISE_toolbox#89]
Hi Junior,

I am working with a RS-DSGE model with endogenous switching probabilities. The probability functions have the following form:

```
    ! nk_tp_1_2 = alp1/(alp1 + exp(-gamma1*(s_obs - s_bar1)/s_std));
    ! nk_tp_2_1 = alp2/(alp2 + exp(gamma2*(s_obs - s_bar2)/s_std));
```
where s_obs is an endogenous variable, alp1, alp2, gamma1, gamma2, s_bar1, s_bar2 and s_std are parameters. I observe s_obs and I am trying to estimate some of the parameters of the probability functions. In this context, I have the following question: how do these probability functions relate to the smoothed and filtered regime probabilities produced by RISE? In particular, in a 2-regime model, the smoothed and filtered concepts of one regime are the complement of the alternative, i.e., the smoothed probability of regime 1 is (1-smoothed probability of regime 2), which need not be the case in the functions described above. 

Since I observe s_obs, I can compute nk_tp_1_2 and nk_tp_2_1 exactly using the functions above, and I would like to understand how these values should compare to the smoothed and filtered probabilities that RISE produces, regardless of whether I estimate or calibrate the parameters ruling the probability functions. 

s_obs has different steady state values in regime 1 and 2, and ultimately I am interested in comparing the dynamics of a RS model with exogenous (constant) switching probabilities, and a model with endogenous switching probabilities as described above.

Many thanks!
Martin

**Comment by jmaih** [comment]
Hi Martin


   1. nk_tp_1_2 is the probability of going from state 1 to state 2. When
   you are in state 1, this tells you the likelihood that you will be in state
   2 in the next period
   2. The smoothed probabilities are the probabilities of being in one
   particular state or regime at each point in time. The two things are
   different
   3. nk_tp_1_2 is not to be compared with the smoothed probabilities.

Cheers,

J.

**Comment by mhardinga** [comment]
Many thanks Junior.
Martin
