### ISSUE TITLE
Error on IRF's of 2nd order approximation.

### ISSUE THREAD

**Issue by farukakbal** [jmaih/RISE_toolbox#9]
Hi all,
I am currently working on a NK model with regime switch. I constructed my model using Gali(2008) and added a fiscal rule with gov'n buget constraint.
The problem is that, when i try to solve model with 1st order approximation, i get the responses as usual. If i switch to 2nd order, IRF's goes to 10^270 etc. which does not make sense.
 I am using the following lines in my main code:
`m=rise(Nonlinear_NK_Gali_MF_2,'max_deriv_order',2)
m=solve(m,'solve_order',2)`
And here is my model:

[Nonlinear_NK_Gali_MF_2.txt](https://github.com/jmaih/RISE_toolbox/files/246448/Nonlinear_NK_Gali_MF_2.txt)

Thanks for your help.

**Comment by jmaih** [comment]
Hi Omer,

there are potentially different issues.

1. The steady state program you provide, does it really solve the steady state or is it just a guess?
2. In general, if the shocks are big, they can push the system outside its convergence region. This is why people resort to pruning.
3. The theory of pruning is not developed for regime switching models and in that world, there are different types of IRFs that can be computed. 
3.a. regime-specific IRFs are computed on the assumption that you stay in the same regime over the entire simulation period although there is a probability of switching
3.b. Generalized IRFs are automatically triggered when the model is nonlinear, but they can also be called when the model has more than one regime, which makes it nonlinear.

It is important to clarify these points before going any further.

cheers,

Junior


nda

**Comment by farukakbal** [comment]
Thanks for that answer, The steady state values are guess values more than calculated ones. Based on your explanations i will check the steady state values before going further, and will inform this issue topic about progress.
