### ISSUE TITLE
Filtering field in RISE cells

### ISSUE THREAD

**Issue by C1587S** [jmaih/RISE_toolbox#93]
Hi Junior,

I have a quick question. Using the last version of RISE I'm trying to get the smoothed probabilities of an estimation procedure. However, the RISE cell structure has changed, and there is no "Model. filtering" field. What is the correct way to extract this information? 

Thanks in advance

S.

**Comment by jmaih** [comment]
Hi S.

f=filter(m);

cheers,

J.

**Comment by C1587S** [comment]
Thank you, Junior!

Regards,

S.
