### ISSUE TITLE
Endogenous Priors Option

### ISSUE THREAD

**Issue by KonstantinosTheodoridis** [jmaih/RISE_toolbox#94]
Dear Junior,
I trust you are well. I have just updated RISE and I am getting the error message below when I am trying to use the endogenous_prior option.
Many thanks in advance for your time and help.
Kostas

[Junior.zip](https://github.com/jmaih/RISE_toolbox/files/2516250/Junior.zip)

Error using std_corr_endo_uk_priors
Too many input arguments.

Error in generic/log_prior_density (line 79)
            pp=obj.options.estim_endogenous_priors(obj,filtration);

Error in generic/log_posterior_kernel (line 131)
        [log_prior(2),retcode(1)]=log_prior_density(obj,'endogenous',filtration);

Error in generic/estimation_wrapper/fh_wrapper (line 197)
                [fval(mo),loglik,~,~,retcode,obj(mo)]=log_posterior_kernel(obj(mo),x);
                
Error in generic/estimation_wrapper (line 130)
        [f1,retcode_0,max_pen]=fh_wrapper(x0);

Error in generic/find_posterior_mode (line 40)
[x0(:,1),f0(1),~,retcode0,viol,obj,funevals]=estimation_wrapper(obj,[],x0(:,1),lb,ub,funevals);

Error in generic/estimate (line 191)
[x1,f1,H,x0,f0,viol,funevals,issue,obj]=find_posterior_mode(obj,x0,lb_short,ub_short);
%#ok<ASGLU>

Error in dsge/estimate (line 217)
    [obj,filtration]=estimate@generic(obj,varargin{:});

Error in exe_Aus_estim_benchmark (line 26)
model=estimate(model,'estim_endogenous_priors',@std_corr_endo_uk_priors);

**Comment by jmaih** [comment]
Hi Kostas,

Just add a second input to the  std_corr_endo_uk_priors.m function although
in your specific example it won't be used given that kf_filtering_level is
set to 0.

Best,

J.

**Comment by KonstantinosTheodoridis** [comment]
Hi Junior,
Many thanks for your prompt reply. It is working now 👍 
Many thanks again.
Kostas

**Comment by jmaih** [comment]
Keep up the good work!
