### ISSUE TITLE
limited commitment

### ISSUE THREAD

**Issue by KonstantinosTheodoridis** [jmaih/RISE_toolbox#95]
Dear Junior,
I trust you are well. I am really to bother you again. We are getting the following error message when we are trying to solve the model under limited commitment.
Many thanks in advance for your time and help.
Kostas

Error using parser.transition_probabilities/transtion_matrix_to_function (line 230)
Error: Invalid expression. When calling a function or indexing a variable, use parentheses.
Otherwise, check for mismatched delimiters.

Error in parser.transition_probabilities (line 189)
    transition_matrix_shadow.(chain)=transtion_matrix_to_function(...

Error in parser.parse (line 527)
    ]=parser.transition_probabilities(...

Error in dsge (line 334)
            dictionary=parser.parse(model_filename,cmfArgins{:});

Error in rise (line 64)
            obj=obj@dsge(varargin{:});

Error in howto_modified (line 7)
m=rise('SOE_modified');

[Junior.zip](https://github.com/jmaih/RISE_toolbox/files/2542289/Junior.zip)

**Comment by jmaih** [comment]
Kostas,

I was not able to replicate the error using "soe_estim.rs".

J.

**Comment by KonstantinosTheodoridis** [comment]
Junior,
I am really sorry to bother you about this again. We have tried to run the code on four different machines and we always are getting the same error.  We have some more information if we use the following expressions
planner_objective{discount = 0.99,commitment=1} -.5*(1*PAI^2+lossy*Y^2+0.1*DI^2;
or
planner_objective{discount = 0.99,commitment=0} -.5*(1*PAI^2+lossy*Y^2+0.1*DI^2);
we are able to solve the model
If we use the following expression
planner_objective{discount = 0.99,commitment=0.9} -.5*(1*PAI^2+lossy*Y^2+0.1*DI^2);
we are getting the following message

Unable to perform assignment because the size of the left side is 1-by-1 and the size of the right
side is 1-by-2.

Error in expand_optimal_policy_solution (line 32)
    T.Tz(:,:,isol)=one_solution(T.Tz(:,:,isol));

Error in dsge/solve (line 469)
            [obj,T]=expand_optimal_policy_solution(obj,T,loose_com_col,nsols);

Error in howto_modified (line 10)
m=solve(m,'solve_linear',true);

Many thanks in advance for your time and help.
Kostas

**Comment by jmaih** [comment]
Kostas,

Unless I am mistaken, you did not send me the RISE file that generates the error. 

J.

**Comment by KonstantinosTheodoridis** [comment]
Apologies about that. It is attached now.
Many thanks
Kostas
[Junior.zip](https://github.com/jmaih/RISE_toolbox/files/2558193/Junior.zip)

**Comment by jmaih** [comment]
The file you sent does not include de instructions about optimal policy.

**Comment by KonstantinosTheodoridis** [comment]
Apologies again!
Kostas
[Junior.zip](https://github.com/jmaih/RISE_toolbox/files/2558546/Junior.zip)

**Comment by jmaih** [comment]
Kostas,

I am currently busy teaching in Mexico. Will you, please, update RISE and
try again?

Thanks,

J.

**Comment by KonstantinosTheodoridis** [comment]
It is working now! Many many thanks
Kostas
