### ISSUE TITLE
Specify a x% shock 

### ISSUE THREAD

**Issue by hledamany** [jmaih/RISE_toolbox#96]
Hello Mr Maih,

I am currently using the TaoZha(tutorial 3) codes and I wanted to try a shock of x% on only one variable.  In a previous post, you mentionned that "RISE does not have a concept for standard deviations and variances. They are always equal to 1. We have to scale the shocks by multiplying them with a constant that RISE treats as a parameter. " 
I understand what you meant but I didn't succed to implement it. 

May I ask you your help ?
Many thanks

Hugo

**Comment by jmaih** [comment]
Hi Hugo,

the option controling for the sign and size of irfs is called
"irf_shock_sign" and it can be invoked when computing irfs as in the
following example

myirfs=irf(m,'irf_shock_sign',2)

In this example, I am setting the size of the irf shocks to 2 (positive)
standard deviations.

Cheers,

Junior
