### ISSUE TITLE
Issue about regime switching parameterization

### ISSUE THREAD

**Issue by hledamany** [jmaih/RISE_toolbox#97]
Hello Junior,

We try to implement a ZLB as in Gavin, Keen, Richter & Trockmorton. Nonetheless, we have the following error "Operands to the || and && operators must be convertible to logical scalar values." 

Without (zlb_tp_1_2 ,   0.1,    0.1,    0.05,   beta_pdf; zlb_tp_2_1 ,   0.15,    0.1,    0.05,   beta_pdf; ),
the code reads the model but there is problem in transition matrix. If I only keep one, this is the same. If i keep both, there is the error message.

It seems the errors comes from the parameterization block but I do not know what can be change ...

Do you have any idea ?
Thank you very much for you help.

**Comment by jmaih** [comment]
Hi,

I do not understand the error message. I ran the tutorial and cannot
reproduce the problem.

J.

**Comment by hledamany** [comment]
Hi,
Thank you for you quick answer. 
Actually, we try to estimate our model based on GKRT's example and we have this error: "Operands to the || and && operators must be convertible to logical scalar values."

If you need more details, I join the codes to the post.

[esat_core_ii_lt_zlb.txt](https://github.com/jmaih/RISE_toolbox/files/2595541/esat_core_ii_lt_zlb.txt)
[v_github.txt](https://github.com/jmaih/RISE_toolbox/files/2595543/v_github.txt)

Thank you for your help.

Hugo

**Comment by jmaih** [comment]
Hi Hugo,

I am still unable to generate the error message. Are you using the latest
version of RISE?

**Comment by hledamany** [comment]
The error came from the version I downloaded two weeks ago. 
Thank you for you availiability. 

Hugo

**Comment by jmaih** [comment]
will you try with the current version?

**Comment by hledamany** [comment]
Yes, I tried and it works.
Thanks
Hugo
