### ISSUE TITLE
UKF implementation

### ISSUE THREAD

**Issue by jonathancantor101** [jmaih/RISE_toolbox#98]
Hi Junior,
I'm facing problems when doing a UKF implementation. I'm not sure how to use the switching_unscented_kalman_filter() function. Specifically, I don't know how to call  the arguments of the function (syst,data_y,U,z,options) after having the second order solution of my model (i.e m = solve(m1, 'solve_order',2)). Could you help me, please? Do you have an example of this type of exercise? 

Many thanks,

Jonathan

**Comment by jonathancantor101** [comment]
Hi Junior,

Thanks for your response. After passing the option to the object as you said, I ran the estimation process in a standard way (i.e. m = estimate(m)), however, there appears to be an error:

```
Undefined function or variable 'likt'.

Error in switching_unscented_kalman_filter (line 296)
    Incr(t)=log(likt);

Error in dsge/filter/filtering_engine (line 334)
            [LogLik,Incr,retcode,Filters]=user_filter(init,y,U,z,obj.options,vargs{:});

Error in dsge/filter (line 235)
    [LogLik,Incr,filtration,retcode]=filtering_engine(init);

Error in likelihood_markov_switching_dsge (line 33)
    [filtration,LogLik,Incr,retcode]=filter(obj);

Error in generic/log_posterior_kernel (line 125)
    [log_lik,Incr,retcode,obj,filtration]=likelihood_func(param,obj);

Error in generic/estimation_wrapper/fh_wrapper (line 197)
                [fval(mo),loglik,~,~,retcode,obj(mo)]=log_posterior_kernel(obj(mo),x);

Error in generic/estimation_wrapper (line 130)
        [f1,retcode_0,max_pen]=fh_wrapper(x0);

Error in generic/find_posterior_mode (line 40)
[x0(:,1),f0(1),~,retcode0,viol,obj,funevals]=estimation_wrapper(obj,[],x0(:,1),lb,ub,funevals);

Error in generic/estimate (line 191)
[x1,f1,H,x0,f0,viol,funevals,issue,obj]=find_posterior_mode(obj,x0,lb_short,ub_short); %#ok<ASGLU>

Error in dsge/estimate (line 217)
    [obj,filtration]=estimate@generic(obj,varargin{:});

Error in driver_estimation (line 131)
m = estimate(m_est)
```

Do you have a guess of what I am doing wrong?

Thanks,

Jonathan

**Comment by jonathancantor101** [comment]
Hi Junior, 

Unfortunately, the error persists and seems to be exactly the same.

Regards,

Jonathan

**Comment by jmaih** [comment]
Did you update RISE?

**Comment by jonathancantor101** [comment]
Yes, I did it several times, but in fact, but surprisingly the error is the same.

**Comment by jmaih** [comment]
You don't need to do it several times. You need to do it once and refresh
matlab.

If you have not closed and re-opened matlab, then do one (or all) of the
following
- clear classes
- rehash

**Comment by jonathancantor101** [comment]
Hi again Junior,

I tried both options and switched my machine to check that the error was not due to my pc. Unfortunately, the error persists and is the same:

```
Undefined function or variable 'likt'.

Error in switching_unscented_kalman_filter (line 296)
    Incr(t)=log(likt);

Error in dsge/filter/filtering_engine (line 334)
            [LogLik,Incr,retcode,Filters]=user_filter(init,y,U,z,obj.options,vargs{:});

Error in dsge/filter (line 235)
    [LogLik,Incr,filtration,retcode]=filtering_engine(init);

Error in likelihood_markov_switching_dsge (line 33)
    [filtration,LogLik,Incr,retcode]=filter(obj);

Error in generic/log_posterior_kernel (line 125)
    [log_lik,Incr,retcode,obj,filtration]=likelihood_func(param,obj);

Error in generic/estimation_wrapper/fh_wrapper (line 197)
                [fval(mo),loglik,~,~,retcode,obj(mo)]=log_posterior_kernel(obj(mo),x);

Error in generic/estimation_wrapper (line 130)
        [f1,retcode_0,max_pen]=fh_wrapper(x0);

Error in generic/find_posterior_mode (line 40)
[x0(:,1),f0(1),~,retcode0,viol,obj,funevals]=estimation_wrapper(obj,[],x0(:,1),lb,ub,funevals);

Error in generic/estimate (line 191)
[x1,f1,H,x0,f0,viol,funevals,issue,obj]=find_posterior_mode(obj,x0,lb_short,ub_short); %#ok<ASGLU>

Error in dsge/estimate (line 217)
    [obj,filtration]=estimate@generic(obj,varargin{:});

Error in driver_estimation (line 135)
me = estimate(m);
```
Does it work on your pc? 

regards,

Jonathan

**Comment by jmaih** [comment]
Hi Jonathan,

Do you have the possibility of sending me your files?

J. 

Sendt fra min iPhone

**Comment by jonathancantor101** [comment]
Hi Junior, 
Thanks.
I was trying with TaoZha\Tutorials\DSGE\Tutorial2\Models\volatilityOnly example, and solving it at 2nd order for doing the estimation. I'm not sure about what was the problem, but now the filter is working on my computer.

By the way, I have an additional question, is there a new form to introduce the parameter restrictions on dsge models?
For instance, in the same example, the restriction is as follows:
```
parameter_restrictions
	sigd(vol,2)>=sigd(vol,1);
```
but the following error appears:
`Error: Unbalanced or unexpected parenthesis or bracket. between line 24 and line 24 in "switching_volatility"`

So I ended dropping this part to be able to run the example. 

Regards,

Jonathan

**Comment by jmaih** [comment]
Hi Jonathan,

Please update RISE and try again.

Cheers,

J.

**Comment by jonathancantor101** [comment]
Solved. Thank you, Junior.

Best,

Jonathan
