### ISSUE TITLE
calling historical_decomposition and variance_decomposition

### ISSUE THREAD

**Issue by dingliumath** [jmaih/RISE_toolbox#99]
Hi Junior,
This is my first time using RISE. To start, I just ran the codes for your AEJ Macro paper. Everything works fine, except calling historical_decomposition (replicating figure 6) and variance_decomposition. Matlab says "Undefined function 'historical_decomposition' for input arguments of type 'struct'." and "Undefined function 'variance_decomposition' for input arguments of type 'struct'". Is this due to version conflicts or something else? Thanks a lot. 

By the way, a minor issue: I followed your instructions to install RISE and ran rise_startup. Matlab says that "MiKTeX: Not installed (no reporting possible)" and "pdflatex/epstopdf (Miktex) could not be located!!!" However, I installed MikTex on my computer (C:\Program Files\MiKTeX 2.9) and it works well. Could you please give me some hints for this issue?  Thanks a lot.

**Comment by jmaih** [comment]
Hi
Historical and variance decomposition functions are to be called on model
objects and not on structures. Make sure the input to the function is an
object of class "rise" or "dsge"

It is also possible that the version we use for writing the paper is not
the one you are using, in which case you will need to update the codes.

If Miktex is installed on your computer, then RISE should be able to detect
it unless, perhaps you are using an operating system that RISE does not
understand well. Windows and Mac should be fine.

Cheers,

J.

**Comment by dingliumath** [comment]
Hi Junior,
Thank you very much for your timely reply. 
I will look into the issues with your advice. 
Cheers,
Ding
